import type { NamedModelAlias } from '../types/named-model-request.types';

/**
 * Words that turn a model name into an instruction: "use nano banana to make
 * a poster", "ask grok", "@veo". A bare mention ("what is Grok?", "Gemini
 * vs GPT") never routes, because the name must follow one of these.
 */
export const NAMED_MODEL_DIRECTIVES: readonly string[] = [
  'use',
  'using',
  'try',
  'trying',
  'ask',
  'asking',
  'via',
  'through',
  'with',
  'let',
  'have',
  'prefer',
  'switch to',
  'go with',
  'powered by',
  'generate with',
  'generated by',
  'made by',
  'made with',
];

/**
 * A directive word (or "@") followed by an optional "the" / "model". A subject
 * in front ("I use claude", "we use grok") describes habit, it is not an order.
 */
export const NAMED_MODEL_DIRECTIVE_PATTERN = new RegExp(
  String.raw`(?<![\p{L}\p{N}])(?<!(?:^|[^\p{L}\p{N}])(?:i|we|they|he|she|people|everyone|you)\s+)(?:(?:${NAMED_MODEL_DIRECTIVES.join('|')})\s+(?:the\s+)?(?:model\s+)?|@)`,
  'gu',
);

/** "compare X with Y" and friends name models without addressing them. */
export const NAMED_MODEL_COMPARISON_PATTERN =
  /(?<![\p{L}\p{N}])(?:compare|compared|comparison|versus|vs|difference between|differences between|better than|worse than|alternative to|alternatives to|instead of|rather than|against)(?![\p{L}\p{N}])/u;

/** The shortest catalog-derived phrase that may name a model (a bare "gpt" must not). */
export const NAMED_MODEL_MIN_PHRASE_LENGTH = 5;

/** Characters in a model id that a person writes as a space ("gpt-4o", "gemini 2.5"). */
export const NAMED_MODEL_SEPARATORS = /[-_./:]+/gu;

/** Decorations a person leaves off a model name: a date stamp, "latest", "preview". */
export const NAMED_MODEL_ID_DECORATIONS: readonly RegExp[] = [
  /\s+\d{8}$/u,
  /\s+\d{4}\s+\d{2}\s+\d{2}$/u,
  /\s+(?:latest|preview|exp|experimental|cloud)$/u,
];

/** How far after a directive the model name may start (characters scanned). */
export const NAMED_MODEL_TAIL_CHARS = 64;

/**
 * Names a person says that the catalog stores under technical ids. They are
 * hints resolved against the live catalog: only models the catalog actually
 * holds, healthy and allowed by the plan, can win. Adding a model to the
 * catalog needs no change here when its id is what people say; add an entry
 * only for a name that differs from the id.
 */
export const NAMED_MODEL_ALIASES: readonly NamedModelAlias[] = [
  {
    phrases: ['nano banana pro', 'nanobanana pro'],
    provider: 'GEMINI',
    modelPattern: /(?:nano-banana-pro|gemini-3[\w.-]*-pro-image)/u,
  },
  {
    phrases: ['nano banana', 'nanobanana', 'nano-banana'],
    provider: 'GEMINI',
    modelPattern: /(?:nano-banana|gemini-[\w.-]*-image)/u,
  },
  { phrases: ['imagen'], provider: 'GEMINI', modelPattern: /imagen/u },
  { phrases: ['veo'], provider: 'GEMINI', modelPattern: /veo/u },
  {
    phrases: ['grok imagine', 'grok image'],
    provider: 'GROK',
    modelPattern: /imagine/u,
  },
  {
    phrases: ['gpt image', 'chatgpt image', 'dall e', 'dalle'],
    provider: 'OPENAI',
    modelPattern: /(?:gpt-image|chatgpt-image|dall-e)/u,
  },
  { phrases: ['sora'], provider: 'OPENAI', modelPattern: /sora/u },
  // Provider-level names: "use grok" means a Grok model, picked by what is asked.
  { phrases: ['grok'], provider: 'GROK' },
  { phrases: ['gemini'], provider: 'GEMINI' },
  { phrases: ['claude'], provider: 'ANTHROPIC' },
  { phrases: ['chatgpt', 'openai'], provider: 'OPENAI' },
  { phrases: ['deepseek'], provider: 'DEEPSEEK' },
];

/** The model a provider-level name falls back to when the catalog holds it. */
export const NAMED_MODEL_PROVIDER_DEFAULTS: ReadonlyMap<string, string> = new Map([
  ['GROK', 'grok-3-mini'],
  ['GEMINI', 'gemini-2.5-flash'],
  ['ANTHROPIC', 'claude-sonnet-4'],
  ['OPENAI', 'gpt-4o-mini'],
]);

/**
 * Providers whose deployments are not named in a decision by their own name
 * (local runtimes are `local-ollama`; Ollama Cloud and Bedrock go through
 * their own mapping), so a name never routes to them.
 */
export const NAMED_MODEL_UNROUTABLE_PROVIDERS: readonly string[] = [
  'OLLAMA',
  'OLLAMA_CLOUD',
  'LLAMACPP',
  'AWS_BEDROCK',
];
