export enum AiActionQueueStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  AUTO_APPROVED = 'AUTO_APPROVED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXECUTING = 'EXECUTING',
  EXECUTED = 'EXECUTED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  EDITED = 'EDITED',
  DENIED = 'DENIED',
}
