export enum WorkspaceActionType {
  CREATE_ISSUE = 'CREATE_ISSUE',
  CREATE_ISSUE_COMMENT = 'CREATE_ISSUE_COMMENT',
  CREATE_PR_DESCRIPTION = 'CREATE_PR_DESCRIPTION',
  CREATE_TICKET = 'CREATE_TICKET',
  ADD_TICKET_COMMENT = 'ADD_TICKET_COMMENT',
  SEND_SLACK_MESSAGE = 'SEND_SLACK_MESSAGE',
}
