export enum WorkspaceObjectType {
  REPOSITORY = 'REPOSITORY',
  ISSUE = 'ISSUE',
  PULL_REQUEST = 'PULL_REQUEST',
  MESSAGE = 'MESSAGE',
  CHANNEL = 'CHANNEL',
  DOCUMENT = 'DOCUMENT',
  FILE = 'FILE',
  TICKET = 'TICKET',
  COMMENT = 'COMMENT',
  USER = 'USER',
  PROJECT = 'PROJECT',
  EMAIL = 'EMAIL',
  MEETING_NOTE = 'MEETING_NOTE',
  SPREADSHEET = 'SPREADSHEET',
  // Stream 23 — Calendar
  MEETING = 'MEETING',
}
