export enum WorkspaceProvider {
  GITHUB = 'GITHUB',
  GITLAB = 'GITLAB',
  BITBUCKET = 'BITBUCKET',
  SLACK = 'SLACK',
  JIRA = 'JIRA',
  CONFLUENCE = 'CONFLUENCE',
  FIGMA = 'FIGMA',
  CLICKUP = 'CLICKUP',
  GOOGLE_DRIVE = 'GOOGLE_DRIVE',
  GMAIL = 'GMAIL',
  MICROSOFT_SHAREPOINT = 'MICROSOFT_SHAREPOINT',
  MICROSOFT_ONEDRIVE = 'MICROSOFT_ONEDRIVE',
  // Stream 23 — Calendar providers (read-only)
  GOOGLE_CALENDAR = 'GOOGLE_CALENDAR',
  OUTLOOK_CALENDAR = 'OUTLOOK_CALENDAR',
}
