export enum WorkspaceObjectLinkType {
  JIRA_REFERENCE = 'JIRA_REFERENCE',
  GITHUB_PR_REFERENCE = 'GITHUB_PR_REFERENCE',
  GITHUB_ISSUE_REFERENCE = 'GITHUB_ISSUE_REFERENCE',
  SLACK_MENTION = 'SLACK_MENTION',
  URL_REFERENCE = 'URL_REFERENCE',
  PARENT_CHILD = 'PARENT_CHILD',
}
