import { apiClient } from '@/services/shared/api-client';
import type {
  BillingPlan,
  BillingUsage,
  CheckoutSessionView,
  CurrentSubscription,
  InvoiceView,
  PaymentMethodSetupSessionView,
  PaymobCompletionView,
  PaymentMethodView,
  ProrationQuoteView,
} from '@/types/billing.types';

// The only place the browser talks to the billing API.
//
// Note what is NOT sent anywhere below: an amount, a currency, or a user id.
// The server resolves the price from the immutable PlanPriceVersion and the
// user from the JWT. A browser that could name its own price would be able to
// buy Unlimited for a cent.
class BillingRepository {
  async listPlans(): Promise<BillingPlan[]> {
    const response = await apiClient.get<BillingPlan[]>('/billing/plans');
    return response.data;
  }

  async getCurrent(): Promise<CurrentSubscription | null> {
    const response = await apiClient.get<CurrentSubscription | null>('/billing/me');
    // Nest/Express serializes a controller's `null` result as an empty 200
    // response. Axios represents that body as an empty string at runtime even
    // though the declared API contract is `CurrentSubscription | null`.
    return response.data || null;
  }

  // Usage lives in auth-service, not payment-service: quota counters and
  // feature allowances are an entitlement concern, and routing this through
  // billing would put a second service on the path for data it does not own.
  async getUsage(): Promise<BillingUsage> {
    const response = await apiClient.get<BillingUsage>('/auth/me/usage');
    return response.data;
  }

  // `idempotencyKey` is generated by the caller and reused on retry, so a
  // double-submit returns the SAME session instead of creating a second
  // payable order.
  async createCheckoutSession(input: {
    planId: string;
    billingInterval: string;
    gateway: string;
    idempotencyKey: string;
  }): Promise<CheckoutSessionView> {
    const response = await apiClient.post<CheckoutSessionView>('/billing/checkout-sessions', input);
    return response.data;
  }

  async getCheckoutSession(id: string): Promise<CheckoutSessionView> {
    const response = await apiClient.get<CheckoutSessionView>(`/billing/checkout-sessions/${id}`);
    return response.data;
  }

  async completePaypalCheckout(
    id: string,
    input: { providerOrderId: string; state: string },
  ): Promise<CheckoutSessionView> {
    const response = await apiClient.post<CheckoutSessionView>(
      `/billing/checkout-sessions/${id}/complete-paypal`,
      input,
    );
    return response.data;
  }

  async completePaymobCheckout(id: string): Promise<PaymobCompletionView> {
    const response = await apiClient.post<PaymobCompletionView>(
      `/billing/checkout-sessions/${id}/complete-paymob`,
    );
    return response.data;
  }

  // Quote and confirm are separate calls on purpose: the user is shown an exact
  // amount and confirms THAT number. Re-deriving it at confirm time would let
  // the price move between the two steps.
  async quotePlanChange(input: {
    targetPlanId: string;
    billingInterval: string;
  }): Promise<ProrationQuoteView> {
    const response = await apiClient.post<ProrationQuoteView>(
      '/billing/subscription/change/quote',
      input,
    );
    return response.data;
  }

  async confirmPlanChange(input: {
    quoteId: string;
    gateway: string;
    idempotencyKey: string;
  }): Promise<CheckoutSessionView | null> {
    const response = await apiClient.post<CheckoutSessionView | null>(
      '/billing/subscription/change/confirm',
      input,
    );
    return response.data;
  }

  async cancel(input: { atPeriodEnd: boolean }): Promise<CurrentSubscription> {
    const response = await apiClient.post<CurrentSubscription>(
      '/billing/subscription/cancel',
      input,
    );
    return response.data;
  }

  async resume(): Promise<CurrentSubscription> {
    const response = await apiClient.post<CurrentSubscription>('/billing/subscription/resume');
    return response.data;
  }

  async listInvoices(): Promise<InvoiceView[]> {
    const response = await apiClient.get<InvoiceView[]>('/billing/invoices');
    return response.data;
  }

  async downloadInvoice(id: string): Promise<Blob> {
    const response = await apiClient.getBlob(`/billing/invoices/${id}/pdf`);
    return response.data;
  }

  async listPaymentMethods(): Promise<PaymentMethodView[]> {
    const response = await apiClient.get<PaymentMethodView[]>('/billing/payment-methods');
    return response.data;
  }

  async createPaymentMethodSetupSession(input: {
    idempotencyKey: string;
    consentToStore: true;
  }): Promise<PaymentMethodSetupSessionView> {
    const response = await apiClient.post<PaymentMethodSetupSessionView>(
      '/billing/payment-method-setup-sessions',
      input,
    );
    return response.data;
  }

  async deletePaymentMethod(id: string): Promise<void> {
    await apiClient.delete(`/billing/payment-methods/${id}`);
  }
}

export const billingRepository = new BillingRepository();
