export enum ResearchWorkflowKind {
  SEARCH_ONLY = 'SEARCH_ONLY',
  SEARCH_THEN_FETCH = 'SEARCH_THEN_FETCH',
  SEARCH_FETCH_EXTRACT = 'SEARCH_FETCH_EXTRACT',
  REPO_CLONE_ANALYZE = 'REPO_CLONE_ANALYZE',
}
