export enum SearchProviderKind {
  OLLAMA_WEB = 'OLLAMA_WEB',
  TAVILY = 'TAVILY',
  SEARXNG = 'SEARXNG',
  EXA = 'EXA',
  FIRECRAWL = 'FIRECRAWL',
  BRAVE = 'BRAVE',
  SERPAPI = 'SERPAPI',
  GENERIC_HTTP = 'GENERIC_HTTP',
}
