export enum PreflightReason {
  RAM_INSUFFICIENT = 'RAM_INSUFFICIENT',
  DISK_INSUFFICIENT = 'DISK_INSUFFICIENT',
  GPU_INSUFFICIENT = 'GPU_INSUFFICIENT',
  BINARY_NOT_INSTALLED = 'BINARY_NOT_INSTALLED',
  RUNTIME_INCOMPATIBLE = 'RUNTIME_INCOMPATIBLE',
}
