export enum PullReasonCode {
  OK = 'OK',
  DISK_FULL = 'DISK_FULL',
  SHA_MISMATCH = 'SHA_MISMATCH',
  NETWORK_TIMEOUT = 'NETWORK_TIMEOUT',
  USER_CANCELLED = 'USER_CANCELLED',
  HARDWARE_INSUFFICIENT = 'HARDWARE_INSUFFICIENT',
  HF_UNAVAILABLE = 'HF_UNAVAILABLE',
  UNKNOWN = 'UNKNOWN',
}
