export const RESEARCH_REQUEST_TIMEOUT_MS = 30_000;
export const SEARCH_ONLY_DEFAULT_MAX_RESULTS = 6;
export const SEARCH_THEN_FETCH_DEFAULT_MAX_RESULTS = 5;
export const SEARCH_FETCH_EXTRACT_DEFAULT_MAX_RESULTS = 4;
