FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npx prisma generate
COPY docker-entrypoint.dev.sh /app/docker-entrypoint.dev.sh
RUN chmod +x /app/docker-entrypoint.dev.sh
EXPOSE 4008
CMD ["/app/docker-entrypoint.dev.sh"]
