/**
 * Redis fan-out for the chat SSE bus, so any replica can serve any client.
 *
 * The problem this solves: RabbitMQ delivers a routed message to exactly ONE
 * replica (competing consumers on a shared durable queue), but the browser's SSE
 * connection is pinned to whichever replica nginx happened to route it to. With
 * an in-process event bus those are the same instance only by luck, and with
 * four replicas the answer streams into a void three times out of four.
 */

/**
 * One channel for every thread, rather than a channel per thread.
 *
 * A per-thread channel would mean subscribing when a client connects and
 * unsubscribing when it leaves, which introduces a race the single channel does
 * not have: a run can start before its subscribe lands, and those frames are
 * gone. The bus already filters by `threadId` on delivery, so a shared channel
 * costs each replica the deserialization of frames it will discard.
 *
 * Revisit if a replica ever spends real CPU discarding frames — that is the
 * signal to move to per-thread channels, not a message count.
 */
export const CHAT_STREAM_CHANNEL = 'claw:chat:stream';

/** Per-thread monotonic counter backing `sequence` and `eventId`. */
export const CHAT_STREAM_SEQUENCE_KEY_PREFIX = 'claw:chat:seq:';

/** Per-thread replay buffer, read once when a client attaches. */
export const CHAT_STREAM_REPLAY_KEY_PREFIX = 'claw:chat:replay:';

/**
 * Frames kept for replay. Matches the in-memory limit this replaced, so a
 * reconnecting client sees exactly what it saw before.
 */
export const CHAT_STREAM_REPLAY_LIMIT = 100;

/**
 * How long a thread's sequence and replay buffer outlive their last frame.
 *
 * Long enough to cover a reconnect and a slow run, short enough that abandoned
 * threads cannot accumulate. The sequence shares the TTL deliberately: if the
 * counter expired while the replay buffer lived, a new run would restart at 1
 * and the frontend's stale-stage guard (`nextStage.sequence < existingStage
 * .sequence`) would silently discard the new frames.
 */
export const CHAT_STREAM_KEY_TTL_SECONDS = 3600;

/**
 * Threads ids are generated by Prisma (cuid) and must stay inside this set.
 *
 * Enforced because the id is concatenated into a JSON string inside Lua below.
 * A quote or backslash in a thread id would produce a malformed frame for every
 * client on that thread, so the value is checked before it can reach the script
 * rather than escaped after.
 */
export const CHAT_STREAM_THREAD_ID_PATTERN = /^[A-Za-z0-9_-]{1,128}$/u;

/**
 * Assigns the sequence, records the frame for replay and fans it out — atomically.
 *
 * Deliberately does NOT `cjson.decode` the event. Splicing the two fields onto
 * the front of the object leaves every other byte exactly as the service
 * serialized it, which matters for one reason that is easy to miss: cjson
 * cannot tell an empty array from an empty object and encodes both as `{}`.
 * `StreamEvent` happens to have no array fields today, so a decode/encode
 * round-trip was measured to be lossless — including on `estimatedCostUsd`,
 * whose precision survived. The day someone adds an array to the type, that
 * stops being true silently, for every frame, with no test that would catch it.
 * Not parsing is also simply cheaper per frame.
 *
 * The splice is safe because a StreamEvent always carries at least `threadId`
 * and `type`, so `ARGV[2]` is never the empty object `{}` and the trailing comma
 * always has a field to precede.
 *
 * KEYS: [1] sequence key, [2] replay key
 * ARGV: [1] channel, [2] event JSON, [3] thread id, [4] replay limit, [5] ttl seconds
 */
export const CHAT_STREAM_PUBLISH_SCRIPT = `
local sequence = redis.call('INCR', KEYS[1])
redis.call('EXPIRE', KEYS[1], ARGV[5])
local payload = '{"eventId":"' .. ARGV[3] .. ':' .. sequence .. '","sequence":' .. sequence .. ',' .. string.sub(ARGV[2], 2)
redis.call('RPUSH', KEYS[2], payload)
redis.call('LTRIM', KEYS[2], -tonumber(ARGV[4]), -1)
redis.call('EXPIRE', KEYS[2], ARGV[5])
redis.call('PUBLISH', ARGV[1], payload)
return sequence
`;
