-- Stream 21 — Add 8 write-action enum values for OneDrive, SharePoint, ClickUp
ALTER TYPE "WorkspaceActionType" ADD VALUE IF NOT EXISTS 'UPLOAD_ONEDRIVE';
ALTER TYPE "WorkspaceActionType" ADD VALUE IF NOT EXISTS 'MOVE_ONEDRIVE';
ALTER TYPE "WorkspaceActionType" ADD VALUE IF NOT EXISTS 'UPLOAD_SHAREPOINT';
ALTER TYPE "WorkspaceActionType" ADD VALUE IF NOT EXISTS 'CREATE_SHAREPOINT_LIST_ITEM';
ALTER TYPE "WorkspaceActionType" ADD VALUE IF NOT EXISTS 'UPDATE_SHAREPOINT_LIST_ITEM';
ALTER TYPE "WorkspaceActionType" ADD VALUE IF NOT EXISTS 'CREATE_CLICKUP_TASK';
ALTER TYPE "WorkspaceActionType" ADD VALUE IF NOT EXISTS 'UPDATE_CLICKUP_TASK';
ALTER TYPE "WorkspaceActionType" ADD VALUE IF NOT EXISTS 'COMMENT_CLICKUP_TASK';
