import type { CountryDialCode } from '@/types/phone.types';

export const COUNTRY_DIAL_CODES: ReadonlyArray<CountryDialCode> = [
  { iso2: 'US', dialCode: '+1', name: 'United States', flag: '🇺🇸' },
  { iso2: 'CA', dialCode: '+1', name: 'Canada', flag: '🇨🇦' },
  { iso2: 'GB', dialCode: '+44', name: 'United Kingdom', flag: '🇬🇧' },
  { iso2: 'IE', dialCode: '+353', name: 'Ireland', flag: '🇮🇪' },
  { iso2: 'DE', dialCode: '+49', name: 'Germany', flag: '🇩🇪' },
  { iso2: 'FR', dialCode: '+33', name: 'France', flag: '🇫🇷' },
  { iso2: 'ES', dialCode: '+34', name: 'Spain', flag: '🇪🇸' },
  { iso2: 'IT', dialCode: '+39', name: 'Italy', flag: '🇮🇹' },
  { iso2: 'PT', dialCode: '+351', name: 'Portugal', flag: '🇵🇹' },
  { iso2: 'NL', dialCode: '+31', name: 'Netherlands', flag: '🇳🇱' },
  { iso2: 'BE', dialCode: '+32', name: 'Belgium', flag: '🇧🇪' },
  { iso2: 'CH', dialCode: '+41', name: 'Switzerland', flag: '🇨🇭' },
  { iso2: 'AT', dialCode: '+43', name: 'Austria', flag: '🇦🇹' },
  { iso2: 'SE', dialCode: '+46', name: 'Sweden', flag: '🇸🇪' },
  { iso2: 'NO', dialCode: '+47', name: 'Norway', flag: '🇳🇴' },
  { iso2: 'DK', dialCode: '+45', name: 'Denmark', flag: '🇩🇰' },
  { iso2: 'FI', dialCode: '+358', name: 'Finland', flag: '🇫🇮' },
  { iso2: 'PL', dialCode: '+48', name: 'Poland', flag: '🇵🇱' },
  { iso2: 'CZ', dialCode: '+420', name: 'Czechia', flag: '🇨🇿' },
  { iso2: 'GR', dialCode: '+30', name: 'Greece', flag: '🇬🇷' },
  { iso2: 'RO', dialCode: '+40', name: 'Romania', flag: '🇷🇴' },
  { iso2: 'HU', dialCode: '+36', name: 'Hungary', flag: '🇭🇺' },
  { iso2: 'RU', dialCode: '+7', name: 'Russia', flag: '🇷🇺' },
  { iso2: 'UA', dialCode: '+380', name: 'Ukraine', flag: '🇺🇦' },
  { iso2: 'TR', dialCode: '+90', name: 'Turkey', flag: '🇹🇷' },
  { iso2: 'EG', dialCode: '+20', name: 'Egypt', flag: '🇪🇬' },
  { iso2: 'SA', dialCode: '+966', name: 'Saudi Arabia', flag: '🇸🇦' },
  { iso2: 'AE', dialCode: '+971', name: 'United Arab Emirates', flag: '🇦🇪' },
  { iso2: 'QA', dialCode: '+974', name: 'Qatar', flag: '🇶🇦' },
  { iso2: 'KW', dialCode: '+965', name: 'Kuwait', flag: '🇰🇼' },
  { iso2: 'BH', dialCode: '+973', name: 'Bahrain', flag: '🇧🇭' },
  { iso2: 'OM', dialCode: '+968', name: 'Oman', flag: '🇴🇲' },
  { iso2: 'JO', dialCode: '+962', name: 'Jordan', flag: '🇯🇴' },
  { iso2: 'LB', dialCode: '+961', name: 'Lebanon', flag: '🇱🇧' },
  { iso2: 'IQ', dialCode: '+964', name: 'Iraq', flag: '🇮🇶' },
  { iso2: 'IL', dialCode: '+972', name: 'Israel', flag: '🇮🇱' },
  { iso2: 'MA', dialCode: '+212', name: 'Morocco', flag: '🇲🇦' },
  { iso2: 'DZ', dialCode: '+213', name: 'Algeria', flag: '🇩🇿' },
  { iso2: 'TN', dialCode: '+216', name: 'Tunisia', flag: '🇹🇳' },
  { iso2: 'LY', dialCode: '+218', name: 'Libya', flag: '🇱🇾' },
  { iso2: 'ZA', dialCode: '+27', name: 'South Africa', flag: '🇿🇦' },
  { iso2: 'NG', dialCode: '+234', name: 'Nigeria', flag: '🇳🇬' },
  { iso2: 'KE', dialCode: '+254', name: 'Kenya', flag: '🇰🇪' },
  { iso2: 'GH', dialCode: '+233', name: 'Ghana', flag: '🇬🇭' },
  { iso2: 'ET', dialCode: '+251', name: 'Ethiopia', flag: '🇪🇹' },
  { iso2: 'IN', dialCode: '+91', name: 'India', flag: '🇮🇳' },
  { iso2: 'PK', dialCode: '+92', name: 'Pakistan', flag: '🇵🇰' },
  { iso2: 'BD', dialCode: '+880', name: 'Bangladesh', flag: '🇧🇩' },
  { iso2: 'LK', dialCode: '+94', name: 'Sri Lanka', flag: '🇱🇰' },
  { iso2: 'NP', dialCode: '+977', name: 'Nepal', flag: '🇳🇵' },
  { iso2: 'CN', dialCode: '+86', name: 'China', flag: '🇨🇳' },
  { iso2: 'JP', dialCode: '+81', name: 'Japan', flag: '🇯🇵' },
  { iso2: 'KR', dialCode: '+82', name: 'South Korea', flag: '🇰🇷' },
  { iso2: 'TW', dialCode: '+886', name: 'Taiwan', flag: '🇹🇼' },
  { iso2: 'HK', dialCode: '+852', name: 'Hong Kong', flag: '🇭🇰' },
  { iso2: 'SG', dialCode: '+65', name: 'Singapore', flag: '🇸🇬' },
  { iso2: 'MY', dialCode: '+60', name: 'Malaysia', flag: '🇲🇾' },
  { iso2: 'ID', dialCode: '+62', name: 'Indonesia', flag: '🇮🇩' },
  { iso2: 'TH', dialCode: '+66', name: 'Thailand', flag: '🇹🇭' },
  { iso2: 'VN', dialCode: '+84', name: 'Vietnam', flag: '🇻🇳' },
  { iso2: 'PH', dialCode: '+63', name: 'Philippines', flag: '🇵🇭' },
  { iso2: 'AU', dialCode: '+61', name: 'Australia', flag: '🇦🇺' },
  { iso2: 'NZ', dialCode: '+64', name: 'New Zealand', flag: '🇳🇿' },
  { iso2: 'BR', dialCode: '+55', name: 'Brazil', flag: '🇧🇷' },
  { iso2: 'MX', dialCode: '+52', name: 'Mexico', flag: '🇲🇽' },
  { iso2: 'AR', dialCode: '+54', name: 'Argentina', flag: '🇦🇷' },
  { iso2: 'CL', dialCode: '+56', name: 'Chile', flag: '🇨🇱' },
  { iso2: 'CO', dialCode: '+57', name: 'Colombia', flag: '🇨🇴' },
  { iso2: 'PE', dialCode: '+51', name: 'Peru', flag: '🇵🇪' },
  { iso2: 'VE', dialCode: '+58', name: 'Venezuela', flag: '🇻🇪' },
  { iso2: 'EC', dialCode: '+593', name: 'Ecuador', flag: '🇪🇨' },
  { iso2: 'UY', dialCode: '+598', name: 'Uruguay', flag: '🇺🇾' },
] as const;

export const DEFAULT_COUNTRY_ISO2 = 'US';
