export const MIN_CHAIN_STEPS = 2;
export const MAX_CHAIN_STEPS = 5;
export const ESCALATION_POLL_INTERVAL_MS = 3000;
export const ESCALATION_POLL_MESSAGES_LIMIT = 50;
export const ESCALATION_AUTO_NAVIGATE_DELAY_MS = 2000;
export const DEFAULT_QUALITY_THRESHOLD = 0.6;
