import { BillingInterval } from '@/enums/billing.enum';
import type { PublicPlan } from '@/types/public-pricing.types';

export const PUBLIC_PRICING_FALLBACK_PLANS: PublicPlan[] = [
  {
    id: 'fallback-free',
    slug: 'free',
    name: 'Free',
    description: 'Try every frontier model with a small daily allowance.',
    displayOrder: 0,
    isDefault: true,
    dailyTokenQuota: 5_000,
    weeklyTokenQuota: 20_000,
    monthlyTokenQuota: 50_000,
    maxChatsPerDay: 2,
    maxMessagesPerDay: 12,
    maxWorkspaceConnections: 0,
    maxContextPacks: 1,
    maxMemoryItems: 5,
    prices: [
      {
        id: 'fallback-free-monthly',
        planId: 'fallback-free',
        billingInterval: BillingInterval.MONTHLY,
        currency: 'USD',
        amountMinor: 0,
        version: 1,
        isActive: true,
      },
    ],
    features: [],
  },
  {
    id: 'fallback-starter',
    slug: 'starter',
    name: 'Starter',
    description: 'Everyday access to fast, low-cost frontier models.',
    displayOrder: 1,
    isDefault: false,
    dailyTokenQuota: 50_000,
    weeklyTokenQuota: 250_000,
    monthlyTokenQuota: 750_000,
    maxChatsPerDay: 10,
    maxMessagesPerDay: 100,
    maxWorkspaceConnections: 1,
    maxContextPacks: 5,
    maxMemoryItems: 50,
    prices: [
      {
        id: 'fallback-starter-monthly',
        planId: 'fallback-starter',
        billingInterval: BillingInterval.MONTHLY,
        currency: 'USD',
        amountMinor: 500,
        version: 1,
        isActive: true,
      },
      {
        id: 'fallback-starter-yearly',
        planId: 'fallback-starter',
        billingInterval: BillingInterval.YEARLY,
        currency: 'USD',
        amountMinor: 5_000,
        version: 1,
        isActive: true,
      },
    ],
    features: [],
  },
  {
    id: 'fallback-plus',
    slug: 'plus',
    name: 'Plus',
    description: 'More allowance and access to standard-tier models.',
    displayOrder: 2,
    isDefault: false,
    dailyTokenQuota: 100_000,
    weeklyTokenQuota: 600_000,
    monthlyTokenQuota: 1_750_000,
    maxChatsPerDay: 25,
    maxMessagesPerDay: 250,
    maxWorkspaceConnections: 2,
    maxContextPacks: 15,
    maxMemoryItems: 200,
    prices: [
      {
        id: 'fallback-plus-monthly',
        planId: 'fallback-plus',
        billingInterval: BillingInterval.MONTHLY,
        currency: 'USD',
        amountMinor: 1_000,
        version: 1,
        isActive: true,
      },
      {
        id: 'fallback-plus-yearly',
        planId: 'fallback-plus',
        billingInterval: BillingInterval.YEARLY,
        currency: 'USD',
        amountMinor: 10_000,
        version: 1,
        isActive: true,
      },
    ],
    features: [],
  },
  {
    id: 'fallback-pro',
    slug: 'pro',
    name: 'Pro',
    description: 'Premium models, deep reasoning and heavy orchestration.',
    displayOrder: 3,
    isDefault: false,
    dailyTokenQuota: 250_000,
    weeklyTokenQuota: 1_500_000,
    monthlyTokenQuota: 4_000_000,
    maxChatsPerDay: 75,
    maxMessagesPerDay: 750,
    maxWorkspaceConnections: 5,
    maxContextPacks: 50,
    maxMemoryItems: 1_000,
    prices: [
      {
        id: 'fallback-pro-monthly',
        planId: 'fallback-pro',
        billingInterval: BillingInterval.MONTHLY,
        currency: 'USD',
        amountMinor: 2_000,
        version: 1,
        isActive: true,
      },
      {
        id: 'fallback-pro-yearly',
        planId: 'fallback-pro',
        billingInterval: BillingInterval.YEARLY,
        currency: 'USD',
        amountMinor: 20_000,
        version: 1,
        isActive: true,
      },
    ],
    features: [],
  },
  {
    id: 'fallback-team',
    slug: 'team',
    name: 'Team',
    description: 'Shared workspaces and a large pooled allowance.',
    displayOrder: 4,
    isDefault: false,
    dailyTokenQuota: 750_000,
    weeklyTokenQuota: 4_000_000,
    monthlyTokenQuota: 11_000_000,
    maxChatsPerDay: 250,
    maxMessagesPerDay: 2_500,
    maxWorkspaceConnections: 15,
    maxContextPacks: 200,
    maxMemoryItems: 5_000,
    prices: [
      {
        id: 'fallback-team-monthly',
        planId: 'fallback-team',
        billingInterval: BillingInterval.MONTHLY,
        currency: 'USD',
        amountMinor: 5_000,
        version: 1,
        isActive: true,
      },
      {
        id: 'fallback-team-yearly',
        planId: 'fallback-team',
        billingInterval: BillingInterval.YEARLY,
        currency: 'USD',
        amountMinor: 50_000,
        version: 1,
        isActive: true,
      },
    ],
    features: [],
  },
  {
    id: 'fallback-scale',
    slug: 'scale',
    name: 'Scale',
    description: 'High-volume access across every model class.',
    displayOrder: 5,
    isDefault: false,
    dailyTokenQuota: 1_500_000,
    weeklyTokenQuota: 9_000_000,
    monthlyTokenQuota: 24_000_000,
    maxChatsPerDay: 1_000,
    maxMessagesPerDay: 10_000,
    maxWorkspaceConnections: 50,
    maxContextPacks: 1_000,
    maxMemoryItems: 25_000,
    prices: [
      {
        id: 'fallback-scale-monthly',
        planId: 'fallback-scale',
        billingInterval: BillingInterval.MONTHLY,
        currency: 'USD',
        amountMinor: 10_000,
        version: 1,
        isActive: true,
      },
      {
        id: 'fallback-scale-yearly',
        planId: 'fallback-scale',
        billingInterval: BillingInterval.YEARLY,
        currency: 'USD',
        amountMinor: 100_000,
        version: 1,
        isActive: true,
      },
    ],
    features: [],
  },
  {
    id: 'fallback-unlimited',
    slug: 'unlimited',
    name: 'Unlimited',
    description: 'Unlimited chats and messages, with fair-use on premium cloud.',
    displayOrder: 6,
    isDefault: false,
    dailyTokenQuota: 5_000_000,
    weeklyTokenQuota: 30_000_000,
    monthlyTokenQuota: null,
    maxChatsPerDay: null,
    maxMessagesPerDay: null,
    maxWorkspaceConnections: 200,
    maxContextPacks: 5_000,
    maxMemoryItems: 100_000,
    prices: [
      {
        id: 'fallback-unlimited-monthly',
        planId: 'fallback-unlimited',
        billingInterval: BillingInterval.MONTHLY,
        currency: 'USD',
        amountMinor: 20_000,
        version: 1,
        isActive: true,
      },
      {
        id: 'fallback-unlimited-yearly',
        planId: 'fallback-unlimited',
        billingInterval: BillingInterval.YEARLY,
        currency: 'USD',
        amountMinor: 200_000,
        version: 1,
        isActive: true,
      },
    ],
    features: [],
  },
];
