export const ROUTES = {
  // Public marketing home. Named so a link back to it never hardcodes '/'.
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  // Public marketing route. Also the entry point for organisations asking
  // about a private on-premise deployment.
  CONTACT: '/contact',
  PRICING: '/pricing',
  DASHBOARD: '/dashboard',
  CHAT: '/chat',
  CHAT_THREAD: (threadId: string) => `/chat/${threadId}` as const,
  CONNECTORS: '/connectors',
  CONNECTOR_DETAIL: (connectorId: string) => `/connectors/${connectorId}` as const,
  MODELS: '/models',
  MODELS_CATALOG: '/models/catalog',
  MODELS_DISCOVERY: '/models/discovery',
  MODELS_LOCAL_FRONTIER: '/models/local-frontier',
  ROUTING: '/routing',
  CHAT_COMPARE: '/chat/compare',
  CHAT_CONSENSUS: '/chat/consensus',
  CHAT_ESCALATION: '/chat/escalation',
  CHAT_REPAIR: '/chat/repair',
  CHAT_DECOMPOSE: '/chat/decompose',
  CHAT_BEST_OF_N: '/chat/best-of-n',
  CHAT_VERIFY: '/chat/verify',
  CHAT_PIPELINE: '/chat/pipeline',
  CHAT_COST_ENSEMBLE: '/chat/cost-ensemble',
  CHAT_ROLE_PACK: '/chat/role-pack',
  ROUTING_REPLAY: '/routing/replay',
  ROUTING_RECOVERY: '/routing/recovery',
  ROUTING_ADAPTIVE_INSIGHTS: '/routing/adaptive-insights',
  ROUTING_PLAYGROUND: '/routing/playground',
  ROUTING_DECISION_DETAIL: (id: string) => `/routing/decisions/${id}`,
  MEMORY: '/memory',
  CONTEXT: '/context',
  FILES: '/files',
  AUDITS: '/audits',
  LOGS: '/logs',
  OBSERVABILITY: '/observability',
  SETTINGS: '/settings',
  ADMIN: '/admin',
  RESEARCH_PROVIDERS: '/research/providers',
  RESEARCH_RUNS: '/research/runs',
  WORKSPACE: '/workspace',
  WORKSPACE_ACTIONS: '/workspace/actions',
  WORKSPACE_APPROVALS: '/workspace/approvals',
  WORKSPACE_PROVIDERS: '/workspace/providers',
  WORKSPACE_APP_CONFIGS: '/workspace/app-configs',
  WORKSPACE_SYNC_HEALTH: '/workspace/sync-health',
  WORKSPACE_CONNECTOR_DETAIL: (id: string) => `/workspace/connectors/${id}`,
  WORKSPACE_GMAIL: '/workspace/gmail',
  WORKSPACE_JIRA: '/workspace/jira',
  WORKSPACE_SOURCE_CONTROL: '/workspace/source-control',
  WORKSPACE_SLACK: '/workspace/slack',
  WORKSPACE_DOCS: '/workspace/docs',
  WORKSPACE_CONFLUENCE: '/workspace/confluence',
  WORKSPACE_FIGMA: '/workspace/figma',
  WORKSPACE_WORKFLOWS: '/workspace/workflows',
  WORKSPACE_INBOX: '/workspace/inbox',
  WORKSPACE_SEMANTIC_SEARCH: '/workspace/semantic-search',
  WORKSPACE_DIGEST: '/workspace/digest',
  WORKSPACE_AUTOMATION_PREFERENCES: '/workspace/automation-preferences',
  WORKSPACE_EMAIL_SIGNATURES: '/workspace/email-signatures',
  WORKSPACE_EMAIL_TEMPLATES: '/workspace/email-templates',
  WORKSPACE_IMPL_HANDOFFS: '/workspace/impl-handoffs',
  ADMIN_USERS: '/admin/users',
  ADMIN_AI_ACTION_POLICIES: '/admin/ai-action-policies',
  ADMIN_SUGGESTION_RULES: '/admin/suggestion-rules',
  ADMIN_WEBHOOK_DELIVERIES: '/admin/webhook-deliveries',
  ADMIN_REFUNDS: '/admin/refunds',
  ADMIN_BILLING: '/admin/billing',
  ADMIN_PAYMENT_GATEWAYS: '/admin/payment-gateways',
  ADMIN_PLANS: '/admin/plans',
  ADMIN_PLAN_NEW: '/admin/plans/new',
  ADMIN_PLAN_EDIT: (id: string) => `/admin/plans/${id}/edit` as const,
  ADMIN_PLAN_MODEL_ACCESS: (id: string) => `/admin/plans/${id}/model-access` as const,
  ADMIN_PLAN_PRICES: (id: string) => `/admin/plans/${id}/prices` as const,
  ADMIN_ROLES: '/admin/roles',
  ADMIN_ROLE_DETAIL: (id: string) => `/admin/roles/${id}` as const,
  ADMIN_RUNTIME_PROGRESS: '/admin/runtime-progress',
  ADMIN_DEPLOYMENT: '/admin/deployment',
  ADMIN_SMART_ROUTER: '/admin/smart-router',
  USAGE: '/usage',
  PLAN: '/plan',
  BILLING: '/billing',
  BILLING_CHECKOUT: '/billing/checkout',
  AGENT: '/agent',
  AGENT_TERMINAL: '/agent/terminal',
  AGENT_REPOS: '/agent/repos',
  AGENT_CAPABILITIES: '/agent/capabilities',
  AGENT_ACTIVITY: '/agent/activity',
  AGENT_RECIPES: '/agent/recipes',
  AGENT_RECIPE_RUN: (runId: string) => `/agent/recipe-runs/${runId}` as const,
  AGENT_MARKETPLACE: '/agent/marketplace',
  AGENT_ACTIVITY_MEMORY: '/agent/activity-memory',
} as const;

export const PUBLIC_ROUTES = [ROUTES.LOGIN, ROUTES.FORGOT_PASSWORD, ROUTES.RESET_PASSWORD] as const;
