export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  CHAT: '/chat',
  CHAT_THREAD: (threadId: string) => `/chat/${threadId}` as const,
  CONNECTORS: '/connectors',
  CONNECTOR_DETAIL: (connectorId: string) => `/connectors/${connectorId}` as const,
  MODELS: '/models',
  MODELS_CATALOG: '/models/catalog',
  MODELS_DISCOVERY: '/models/discovery',
  ROUTING: '/routing',
  CHAT_COMPARE: '/chat/compare',
  CHAT_CONSENSUS: '/chat/consensus',
  CHAT_ESCALATION: '/chat/escalation',
  CHAT_REPAIR: '/chat/repair',
  CHAT_DECOMPOSE: '/chat/decompose',
  CHAT_BEST_OF_N: '/chat/best-of-n',
  CHAT_VERIFY: '/chat/verify',
  CHAT_PIPELINE: '/chat/pipeline',
  CHAT_COST_ENSEMBLE: '/chat/cost-ensemble',
  CHAT_ROLE_PACK: '/chat/role-pack',
  ROUTING_REPLAY: '/routing/replay',
  ROUTING_RECOVERY: '/routing/recovery',
  ROUTING_ADAPTIVE_INSIGHTS: '/routing/adaptive-insights',
  MEMORY: '/memory',
  CONTEXT: '/context',
  FILES: '/files',
  AUDITS: '/audits',
  LOGS: '/logs',
  OBSERVABILITY: '/observability',
  SETTINGS: '/settings',
  ADMIN: '/admin',
  RESEARCH_PROVIDERS: '/research/providers',
  RESEARCH_RUNS: '/research/runs',
  WORKSPACE: '/workspace',
  WORKSPACE_ACTIONS: '/workspace/actions',
  WORKSPACE_PROVIDERS: '/workspace/providers',
  WORKSPACE_APP_CONFIGS: '/workspace/app-configs',
  WORKSPACE_CONNECTOR_DETAIL: (id: string) => `/workspace/connectors/${id}`,
  AGENT: '/agent',
  AGENT_TERMINAL: '/agent/terminal',
  AGENT_REPOS: '/agent/repos',
} as const;

export const PUBLIC_ROUTES = [ROUTES.LOGIN] as const;
