export const DECOMPOSE_POLL_INTERVAL_MS = 3000;
export const DECOMPOSE_POLL_MESSAGES_LIMIT = 50;
export const DECOMPOSE_AUTO_NAVIGATE_DELAY_MS = 3000;
export const MAX_DECOMPOSE_POLL_COUNT = 60;
export const DECOMPOSE_CONTENT_MIN_LENGTH = 10;
