export const VERIFIER_POLL_INTERVAL_MS = 2000;
export const MAX_VERIFIER_POLL_COUNT = 90;
export const VERIFIER_POLL_MESSAGES_LIMIT = 10;
export const VERIFIER_AUTO_NAVIGATE_DELAY_MS = 3000;
export const VERIFIER_CONTENT_MIN_LENGTH = 10;
