import { WorkspaceActionStatus } from '@/enums/workspace-action-status.enum';
import { WorkspaceActionType } from '@/enums/workspace-action-type.enum';

export const WORKSPACE_ACTION_STATUS_VARIANT: Record<
  WorkspaceActionStatus,
  'default' | 'secondary' | 'destructive' | 'outline'
> = {
  [WorkspaceActionStatus.PENDING_APPROVAL]: 'outline',
  [WorkspaceActionStatus.APPROVED]: 'secondary',
  [WorkspaceActionStatus.EXECUTING]: 'secondary',
  [WorkspaceActionStatus.EXECUTED]: 'default',
  [WorkspaceActionStatus.FAILED]: 'destructive',
  [WorkspaceActionStatus.REJECTED]: 'outline',
  [WorkspaceActionStatus.EXPIRED]: 'outline',
  [WorkspaceActionStatus.EDITED]: 'outline',
};

export const WORKSPACE_ACTION_STATUS_I18N_KEY: Record<WorkspaceActionStatus, string> = {
  [WorkspaceActionStatus.PENDING_APPROVAL]: 'workspaceActions.pendingApproval',
  [WorkspaceActionStatus.APPROVED]: 'workspaceActions.approved',
  [WorkspaceActionStatus.EXECUTING]: 'workspaceActions.executing',
  [WorkspaceActionStatus.EXECUTED]: 'workspaceActions.executed',
  [WorkspaceActionStatus.FAILED]: 'workspaceActions.failed',
  [WorkspaceActionStatus.REJECTED]: 'workspaceActions.rejected',
  [WorkspaceActionStatus.EXPIRED]: 'workspaceActions.expired',
  [WorkspaceActionStatus.EDITED]: 'workspaceActions.edited',
};

export const WORKSPACE_ACTION_TYPE_LABEL: Record<WorkspaceActionType, string> = {
  [WorkspaceActionType.CREATE_ISSUE]: 'Create Issue',
  [WorkspaceActionType.CREATE_ISSUE_COMMENT]: 'Add Issue Comment',
  [WorkspaceActionType.CREATE_PR_DESCRIPTION]: 'Create PR Description',
  [WorkspaceActionType.CREATE_TICKET]: 'Create Ticket',
  [WorkspaceActionType.ADD_TICKET_COMMENT]: 'Add Ticket Comment',
  [WorkspaceActionType.SEND_SLACK_MESSAGE]: 'Send Slack Message',
  [WorkspaceActionType.SEND_EMAIL]: 'Send Email',
  [WorkspaceActionType.REPLY_EMAIL]: 'Reply Email',
  [WorkspaceActionType.UPDATE_JIRA_ISSUE]: 'Update Jira Issue',
  [WorkspaceActionType.COMMENT_JIRA]: 'Comment on Jira Issue',
  [WorkspaceActionType.COMMENT_PR]: 'Comment on PR',
  [WorkspaceActionType.APPROVE_PR]: 'Approve PR',
  [WorkspaceActionType.ADD_PR_SUGGESTION]: 'Add PR Suggestion',
  [WorkspaceActionType.SEND_SLACK]: 'Send Slack',
  [WorkspaceActionType.REPLY_SLACK]: 'Reply Slack',
  [WorkspaceActionType.EDIT_CONFLUENCE]: 'Edit Confluence Page',
  [WorkspaceActionType.CREATE_CONFLUENCE]: 'Create Confluence Page',
  [WorkspaceActionType.UPLOAD_DRIVE]: 'Upload to Drive',
  [WorkspaceActionType.MOVE_DRIVE]: 'Move in Drive',
  [WorkspaceActionType.CREATE_USER_STORY_FROM_FIGMA]: 'Create User Story from Figma',
  [WorkspaceActionType.CREATE_JIRA_FROM_FIGMA]: 'Create Jira Ticket from Figma',
  [WorkspaceActionType.POST_FIGMA_COMMENT]: 'Post Figma Comment',
  [WorkspaceActionType.CREATE_DRAFT]: 'Create Email Draft',
  [WorkspaceActionType.CREATE_MR_COMMENT]: 'Comment on Merge Request',
  [WorkspaceActionType.APPROVE_MR]: 'Approve Merge Request',
  [WorkspaceActionType.CREATE_GITLAB_ISSUE]: 'Create GitLab Issue',
  [WorkspaceActionType.COMMENT_GITLAB_ISSUE]: 'Comment on GitLab Issue',
  [WorkspaceActionType.UPDATE_MR_DESCRIPTION]: 'Update Merge Request Description',
  [WorkspaceActionType.ADD_MR_SUGGESTION]: 'Add Merge Request Suggestion',
  [WorkspaceActionType.ADD_MR_IMAGE_COMMENT]: 'Add Merge Request Image Comment',
  [WorkspaceActionType.CREATE_PR_COMMENT_BB]: 'Comment on Bitbucket PR',
  [WorkspaceActionType.APPROVE_PR_BB]: 'Approve Bitbucket PR',
  [WorkspaceActionType.CREATE_BITBUCKET_ISSUE]: 'Create Bitbucket Issue',
  [WorkspaceActionType.UPLOAD_ONEDRIVE]: 'Upload to OneDrive',
  [WorkspaceActionType.MOVE_ONEDRIVE]: 'Move in OneDrive',
  [WorkspaceActionType.UPLOAD_SHAREPOINT]: 'Upload to SharePoint',
  [WorkspaceActionType.CREATE_SHAREPOINT_LIST_ITEM]: 'Create SharePoint List Item',
  [WorkspaceActionType.UPDATE_SHAREPOINT_LIST_ITEM]: 'Update SharePoint List Item',
  [WorkspaceActionType.CREATE_CLICKUP_TASK]: 'Create ClickUp Task',
  [WorkspaceActionType.UPDATE_CLICKUP_TASK]: 'Update ClickUp Task',
  [WorkspaceActionType.COMMENT_CLICKUP_TASK]: 'Comment on ClickUp Task',
  [WorkspaceActionType.CREATE_GOOGLE_CALENDAR_EVENT]: 'Create Google Calendar Event',
  [WorkspaceActionType.CREATE_OUTLOOK_CALENDAR_EVENT]: 'Create Outlook Calendar Event',
};
