import swc from 'unplugin-swc';
import { defineConfig } from 'vitest/config';

/**
 * Vitest for a NestJS service. Generated by tools/migration/jest-to-vitest.mjs.
 *
 * The swc plugin is not optional: Vitest transforms with esbuild, esbuild does
 * not emit decorator METADATA, and without it Test.createTestingModule resolves
 * every injected constructor parameter to undefined — dependency injection
 * fails silently rather than loudly. swc emits it.
 */
export default defineConfig({
  plugins: [
    swc.vite({
      module: { type: 'es6' },
      jsc: {
        target: 'es2022',
        parser: { syntax: 'typescript', decorators: true },
        transform: { legacyDecorator: true, decoratorMetadata: true },
      },
    }),
  ],
  test: {
    globals: true,
    environment: 'node',
    // Jest ran with rootDir '.' and a bare testRegex, so it also picked up
    // specs OUTSIDE src/ — prisma/seeders/__tests__ being the case that caught
    // this. Narrowing to src/** silently dropped them, which is the worst way
    // for a migration to lose coverage: green, and smaller.
    include: ['**/*.spec.ts'],
    exclude: ['**/node_modules/**', '**/dist/**', '**/.next/**'],
    // Nest reads decorator metadata through reflect-metadata's global shim.
    // Loading it here rather than relying on some import pulling it in first is
    // what the old Jest setupFiles entry was for.
    setupFiles: ['reflect-metadata'],
    testTimeout: 30_000,
    coverage: {
      provider: 'v8',
      reportsDirectory: './coverage',
      include: ['src/**/*.ts'],
      exclude: [
        'src/**/*.module.ts',
        'src/main.ts',
        'src/**/*.type.ts',
        'src/**/*.types.ts',
        'src/**/*.constants.ts',
        'src/**/*.enum.ts',
        'src/**/index.ts',
      ],
      thresholds: {"branches":50,"functions":70,"lines":55,"statements":55},
    },
  },
  resolve: {
    alias: {
      '@app': new URL('./src/app', import.meta.url).pathname,
      '@common': new URL('./src/common', import.meta.url).pathname,
      '@infrastructure': new URL('./src/infrastructure', import.meta.url).pathname,
      '@modules': new URL('./src/modules', import.meta.url).pathname,
    },
  },
});
