import { type CuratedCloudModelIntelligence } from '../types/model-intelligence.types';

/// Phase 3: Curated static intelligence table for well-known cloud models.
/// Used as the fallback source when connector-service doesn't expose a
/// `/internal/connectors/models` endpoint (or the endpoint returns a thin
/// snapshot without capabilities). Sync workers merge these entries into
/// `router_model_registry`, never overwriting the `adminOverrideJson` block.
///
/// Curation rules:
/// - Only known-true / known-false capabilities are filled. Unknown stays
///   undefined (the repo writes `null`) so the planner does not assume.
/// - Cost figures are USD per 1M tokens, sourced from public pricing pages
///   as of the lookup date (kept conservative — if pricing tier moves we
///   re-enrich, sync wins over stale entries for non-override fields).
/// - Latency class is "FAST" / "MEDIUM" / "SLOW" by observed p50 against
///   ClawAI's router benchmark suite (see qa/routing-latency-baseline/).
/// - `qualityTierLabel` uses the §6.1 vocabulary: BASIC / STANDARD / PRO /
///   FRONTIER. `costClassLabel` uses FREE / LOW / MEDIUM / HIGH / PREMIUM.
export const CURATED_CLOUD_MODEL_INTELLIGENCE: ReadonlyArray<CuratedCloudModelIntelligence> =
  Object.freeze([
    // ─── OpenAI ──────────────────────────────────────────────────────────
    {
      provider: 'OPENAI',
      modelKey: 'gpt-4o',
      displayName: 'GPT-4o',
      family: 'gpt-4o',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: true,
        supportsAudioInput: true,
        supportsAudioOutput: true,
        supportsVideoInput: false,
        supportsFileInput: true,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 128_000,
        maxOutputTokensIntel: 16_384,
        domainStrengths: ['general', 'coding', 'creative_writing', 'research'],
        roleStrengths: ['software_engineer', 'researcher', 'analyst'],
        weakDomains: ['ultra_long_legal', 'specialized_medical_imaging'],
        bestFor: ['multimodal_chat', 'vision_q_and_a', 'voice_input_chat'],
        avoidFor: ['privacy_first', 'frontier_math_proofs'],
        languageStrengths: ['en', 'es', 'fr', 'de', 'it', 'pt', 'zh', 'ja', 'ar'],
        qualityTierLabel: 'PRO',
        costClassLabel: 'MEDIUM',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 2.5,
        estimatedOutputCostPer1M: 10,
        latencyClassLabel: 'MEDIUM',
        privacyClassLabel: 'cloud',
      },
    },
    {
      provider: 'OPENAI',
      modelKey: 'gpt-4o-mini',
      displayName: 'GPT-4o Mini',
      family: 'gpt-4o',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: true,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: true,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 128_000,
        maxOutputTokensIntel: 16_384,
        domainStrengths: ['general', 'translation', 'summarization'],
        roleStrengths: ['support_agent', 'writer'],
        weakDomains: ['complex_reasoning', 'frontier_math'],
        bestFor: ['low_latency_chat', 'bulk_summarization', 'cheap_tool_use'],
        avoidFor: ['high_reasoning', 'legal_drafting'],
        languageStrengths: ['en', 'es', 'fr', 'de', 'it', 'pt'],
        qualityTierLabel: 'STANDARD',
        costClassLabel: 'LOW',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 0.15,
        estimatedOutputCostPer1M: 0.6,
        latencyClassLabel: 'FAST',
        privacyClassLabel: 'cloud',
      },
    },
    {
      provider: 'OPENAI',
      modelKey: 'o3-mini',
      displayName: 'OpenAI o3-mini',
      family: 'o-series',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: false,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: false,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 200_000,
        maxOutputTokensIntel: 100_000,
        domainStrengths: ['reasoning', 'coding', 'math', 'physics'],
        roleStrengths: ['software_engineer', 'mathematician', 'data_scientist'],
        weakDomains: ['casual_chat', 'translation'],
        bestFor: ['hard_reasoning', 'planning', 'code_review'],
        avoidFor: ['low_latency_chat', 'streaming_voice'],
        languageStrengths: ['en'],
        qualityTierLabel: 'FRONTIER',
        costClassLabel: 'HIGH',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 1.1,
        estimatedOutputCostPer1M: 4.4,
        latencyClassLabel: 'SLOW',
        privacyClassLabel: 'cloud',
      },
    },
    // ─── Anthropic ───────────────────────────────────────────────────────
    {
      provider: 'ANTHROPIC',
      modelKey: 'claude-sonnet-4',
      displayName: 'Claude Sonnet 4',
      family: 'claude-4',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: true,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: true,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 200_000,
        maxOutputTokensIntel: 8_192,
        domainStrengths: ['coding', 'reasoning', 'research', 'analysis'],
        roleStrengths: ['software_engineer', 'researcher', 'product_manager'],
        weakDomains: ['real_time_audio'],
        bestFor: ['code_authoring', 'long_context_reading', 'architecture_review'],
        avoidFor: ['voice_chat', 'image_generation'],
        languageStrengths: ['en', 'es', 'fr', 'de', 'it', 'pt', 'zh', 'ja'],
        qualityTierLabel: 'PRO',
        costClassLabel: 'MEDIUM',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 3,
        estimatedOutputCostPer1M: 15,
        latencyClassLabel: 'MEDIUM',
        privacyClassLabel: 'cloud',
      },
    },
    {
      provider: 'ANTHROPIC',
      modelKey: 'claude-opus-4',
      displayName: 'Claude Opus 4',
      family: 'claude-4',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: true,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: true,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 200_000,
        maxOutputTokensIntel: 8_192,
        domainStrengths: ['reasoning', 'legal', 'medical', 'finance', 'research', 'coding'],
        roleStrengths: ['lawyer', 'doctor', 'analyst', 'senior_engineer'],
        weakDomains: ['real_time_audio'],
        bestFor: ['high_risk_drafting', 'judge', 'deep_analysis'],
        avoidFor: ['low_latency_chat', 'bulk_summarization'],
        languageStrengths: ['en', 'es', 'fr', 'de', 'it', 'pt', 'zh', 'ja'],
        qualityTierLabel: 'FRONTIER',
        costClassLabel: 'PREMIUM',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 15,
        estimatedOutputCostPer1M: 75,
        latencyClassLabel: 'SLOW',
        privacyClassLabel: 'cloud',
      },
    },
    {
      provider: 'ANTHROPIC',
      modelKey: 'claude-haiku-4',
      displayName: 'Claude Haiku 4',
      family: 'claude-4',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: true,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: true,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 200_000,
        maxOutputTokensIntel: 4_096,
        domainStrengths: ['general', 'translation', 'summarization'],
        roleStrengths: ['support_agent', 'writer'],
        weakDomains: ['frontier_math', 'specialized_medical'],
        bestFor: ['low_latency_chat', 'bulk_classification', 'cheap_summarization'],
        avoidFor: ['high_risk_drafting'],
        languageStrengths: ['en', 'es', 'fr', 'de', 'it', 'pt'],
        qualityTierLabel: 'STANDARD',
        costClassLabel: 'LOW',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 0.25,
        estimatedOutputCostPer1M: 1.25,
        latencyClassLabel: 'FAST',
        privacyClassLabel: 'cloud',
      },
    },
    // ─── Gemini ──────────────────────────────────────────────────────────
    {
      provider: 'GEMINI',
      modelKey: 'gemini-2.5-flash',
      displayName: 'Gemini 2.5 Flash',
      family: 'gemini-2.5',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: true,
        supportsAudioInput: true,
        supportsAudioOutput: false,
        supportsVideoInput: true,
        supportsFileInput: true,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 1_000_000,
        maxOutputTokensIntel: 8_192,
        domainStrengths: ['multimodal', 'web_search', 'youtube_analysis', 'pdf_extraction'],
        roleStrengths: ['analyst', 'researcher', 'content_creator'],
        weakDomains: ['frontier_math'],
        bestFor: ['video_analysis', 'long_pdf', 'multimodal_chat', 'youtube_transcript'],
        avoidFor: ['privacy_first', 'high_risk_drafting'],
        languageStrengths: ['en', 'es', 'fr', 'de', 'it', 'pt', 'zh', 'ja', 'hi', 'ar'],
        qualityTierLabel: 'PRO',
        costClassLabel: 'LOW',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 0.3,
        estimatedOutputCostPer1M: 2.5,
        latencyClassLabel: 'FAST',
        privacyClassLabel: 'cloud',
      },
    },
    {
      provider: 'GEMINI',
      modelKey: 'gemini-2.5-pro',
      displayName: 'Gemini 2.5 Pro',
      family: 'gemini-2.5',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: true,
        supportsAudioInput: true,
        supportsAudioOutput: false,
        supportsVideoInput: true,
        supportsFileInput: true,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 2_000_000,
        maxOutputTokensIntel: 8_192,
        domainStrengths: ['reasoning', 'coding', 'multimodal', 'research'],
        roleStrengths: ['researcher', 'software_engineer', 'analyst'],
        weakDomains: [],
        bestFor: ['huge_context', 'multimodal_research', 'long_codebase_review'],
        avoidFor: ['low_latency_chat', 'privacy_first'],
        languageStrengths: ['en', 'es', 'fr', 'de', 'it', 'pt', 'zh', 'ja', 'hi', 'ar', 'ru'],
        qualityTierLabel: 'FRONTIER',
        costClassLabel: 'MEDIUM',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 1.25,
        estimatedOutputCostPer1M: 10,
        latencyClassLabel: 'MEDIUM',
        privacyClassLabel: 'cloud',
      },
    },
    // ─── DeepSeek ────────────────────────────────────────────────────────
    {
      provider: 'DEEPSEEK',
      modelKey: 'deepseek-v3.2',
      displayName: 'DeepSeek V3.2',
      family: 'deepseek-v3',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: false,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: false,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 128_000,
        maxOutputTokensIntel: 8_192,
        domainStrengths: ['coding', 'reasoning', 'math'],
        roleStrengths: ['software_engineer', 'data_scientist'],
        weakDomains: ['multimodal'],
        bestFor: ['cost_efficient_reasoning', 'code_review'],
        avoidFor: ['vision', 'audio_chat'],
        languageStrengths: ['en', 'zh'],
        qualityTierLabel: 'PRO',
        costClassLabel: 'LOW',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 0.27,
        estimatedOutputCostPer1M: 1.1,
        latencyClassLabel: 'MEDIUM',
        privacyClassLabel: 'cloud',
      },
    },
    {
      provider: 'DEEPSEEK',
      modelKey: 'deepseek-r1',
      displayName: 'DeepSeek R1',
      family: 'deepseek-r1',
      enrichment: {
        supportsStreaming: true,
        supportsTools: false,
        supportsStructuredOutput: true,
        supportsVision: false,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: false,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 64_000,
        maxOutputTokensIntel: 8_192,
        domainStrengths: ['reasoning', 'math', 'chain_of_thought'],
        roleStrengths: ['mathematician', 'researcher'],
        weakDomains: ['tool_use', 'multimodal'],
        bestFor: ['hard_math', 'planning', 'logic'],
        avoidFor: ['tool_calling', 'streaming_voice'],
        languageStrengths: ['en', 'zh'],
        qualityTierLabel: 'PRO',
        costClassLabel: 'LOW',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 0.55,
        estimatedOutputCostPer1M: 2.19,
        latencyClassLabel: 'SLOW',
        privacyClassLabel: 'cloud',
      },
    },
    // ─── Grok ────────────────────────────────────────────────────────────
    {
      provider: 'GROK',
      modelKey: 'grok-3',
      displayName: 'Grok 3',
      family: 'grok-3',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: true,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: true,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 131_072,
        maxOutputTokensIntel: 8_192,
        domainStrengths: ['general', 'reasoning', 'realtime_news'],
        roleStrengths: ['analyst', 'researcher'],
        weakDomains: [],
        bestFor: ['x_realtime_search', 'general_chat'],
        avoidFor: ['privacy_first'],
        languageStrengths: ['en'],
        qualityTierLabel: 'PRO',
        costClassLabel: 'MEDIUM',
        costConfidenceLabel: 'ESTIMATED',
        estimatedInputCostPer1M: 5,
        estimatedOutputCostPer1M: 15,
        latencyClassLabel: 'MEDIUM',
        privacyClassLabel: 'cloud',
      },
    },
    // ─── AWS Bedrock (Anthropic via Bedrock) ─────────────────────────────
    {
      provider: 'AWS_BEDROCK',
      modelKey: 'anthropic.claude-sonnet-4',
      displayName: 'Claude Sonnet 4 (Bedrock)',
      family: 'claude-4',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: true,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: true,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 200_000,
        maxOutputTokensIntel: 8_192,
        domainStrengths: ['coding', 'reasoning', 'enterprise_compliance'],
        roleStrengths: ['software_engineer', 'compliance_officer'],
        weakDomains: ['real_time_audio'],
        bestFor: ['enterprise_aws_residency', 'compliance_drafting'],
        avoidFor: ['low_latency_chat'],
        languageStrengths: ['en', 'es', 'fr', 'de', 'ja'],
        qualityTierLabel: 'PRO',
        costClassLabel: 'MEDIUM',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 3,
        estimatedOutputCostPer1M: 15,
        latencyClassLabel: 'MEDIUM',
        privacyClassLabel: 'cloud',
      },
    },
    // ─── Mistral (cloud) ─────────────────────────────────────────────────
    {
      provider: 'MISTRAL',
      modelKey: 'mistral-large-latest',
      displayName: 'Mistral Large',
      family: 'mistral-large',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: false,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: false,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 128_000,
        maxOutputTokensIntel: 8_192,
        domainStrengths: ['general', 'coding', 'translation'],
        roleStrengths: ['software_engineer', 'translator'],
        weakDomains: ['multimodal'],
        bestFor: ['multilingual_eu', 'cost_efficient_general'],
        avoidFor: ['vision', 'audio_chat'],
        languageStrengths: ['en', 'fr', 'de', 'es', 'it', 'pt'],
        qualityTierLabel: 'STANDARD',
        costClassLabel: 'LOW',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 2,
        estimatedOutputCostPer1M: 6,
        latencyClassLabel: 'MEDIUM',
        privacyClassLabel: 'cloud',
      },
    },
    // ─── Cohere ──────────────────────────────────────────────────────────
    {
      provider: 'COHERE',
      modelKey: 'command-r-plus',
      displayName: 'Cohere Command R+',
      family: 'command-r',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: false,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: false,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 128_000,
        maxOutputTokensIntel: 4_096,
        domainStrengths: ['rag', 'tool_use', 'enterprise_search'],
        roleStrengths: ['knowledge_worker', 'analyst'],
        weakDomains: ['multimodal'],
        bestFor: ['rag', 'grounded_qa', 'enterprise_search'],
        avoidFor: ['vision', 'streaming_voice'],
        languageStrengths: ['en', 'fr', 'de', 'es'],
        qualityTierLabel: 'STANDARD',
        costClassLabel: 'MEDIUM',
        costConfidenceLabel: 'EXACT',
        estimatedInputCostPer1M: 2.5,
        estimatedOutputCostPer1M: 10,
        latencyClassLabel: 'MEDIUM',
        privacyClassLabel: 'cloud',
      },
    },
    // ─── Qwen (cloud) ────────────────────────────────────────────────────
    {
      provider: 'QWEN',
      modelKey: 'qwen-max',
      displayName: 'Qwen Max',
      family: 'qwen',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: false,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: false,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 32_000,
        maxOutputTokensIntel: 8_192,
        domainStrengths: ['general', 'coding', 'reasoning'],
        roleStrengths: ['software_engineer', 'analyst'],
        weakDomains: ['real_time_audio'],
        bestFor: ['multilingual_zh', 'cost_efficient_reasoning'],
        avoidFor: ['vision', 'audio_chat'],
        languageStrengths: ['en', 'zh'],
        qualityTierLabel: 'PRO',
        costClassLabel: 'LOW',
        costConfidenceLabel: 'ESTIMATED',
        estimatedInputCostPer1M: 1.6,
        estimatedOutputCostPer1M: 6.4,
        latencyClassLabel: 'MEDIUM',
        privacyClassLabel: 'cloud',
      },
    },
    // ─── Kimi (Moonshot, cloud) ──────────────────────────────────────────
    {
      provider: 'MOONSHOT',
      modelKey: 'moonshot-v1-128k',
      displayName: 'Moonshot v1 128k',
      family: 'moonshot-v1',
      enrichment: {
        supportsStreaming: true,
        supportsTools: true,
        supportsStructuredOutput: true,
        supportsVision: false,
        supportsAudioInput: false,
        supportsAudioOutput: false,
        supportsVideoInput: false,
        supportsFileInput: false,
        supportsEmbeddings: false,
        supportsLongContext: true,
        maxContextTokens: 128_000,
        maxOutputTokensIntel: 8_192,
        domainStrengths: ['general', 'long_context_qa'],
        roleStrengths: ['researcher', 'analyst'],
        weakDomains: ['multimodal'],
        bestFor: ['long_context_qa', 'multilingual_zh'],
        avoidFor: ['vision', 'audio_chat'],
        languageStrengths: ['en', 'zh'],
        qualityTierLabel: 'STANDARD',
        costClassLabel: 'LOW',
        costConfidenceLabel: 'ESTIMATED',
        estimatedInputCostPer1M: 1.4,
        estimatedOutputCostPer1M: 1.4,
        latencyClassLabel: 'MEDIUM',
        privacyClassLabel: 'cloud',
      },
    },
  ]);

/// Lookup-by-key map keyed `${provider}::${modelKey}` for O(1) sync merges.
export const CURATED_CLOUD_MODEL_INTELLIGENCE_BY_KEY: ReadonlyMap<
  string,
  CuratedCloudModelIntelligence
> = new Map(
  CURATED_CLOUD_MODEL_INTELLIGENCE.map((entry) => [`${entry.provider}::${entry.modelKey}`, entry]),
);
