import { type ModelIntelligenceEnrichment } from '../types/model-intelligence.types';

/// Phase 3: Heuristics that map a local-model family/name fragment to a
/// default enrichment block. Sync uses these when ollama-service /
/// llamacpp-service expose only the model name without rich capabilities.
///
/// Keys are lowercased substrings matched against `family || modelKey`.
/// First match wins (most specific first). Unknown families return undefined
/// so the registry stores `null` capabilities (= unknown per §6.3).
export const LOCAL_FAMILY_HEURISTICS: ReadonlyArray<{
  match: string;
  enrichment: ModelIntelligenceEnrichment;
}> = Object.freeze([
  // Coding-specialist families
  {
    match: 'qwen3-coder',
    enrichment: {
      supportsStreaming: true,
      supportsTools: true,
      supportsStructuredOutput: true,
      supportsVision: false,
      supportsAudioInput: false,
      supportsAudioOutput: false,
      supportsVideoInput: false,
      supportsFileInput: false,
      supportsEmbeddings: false,
      supportsLongContext: true,
      domainStrengths: ['coding', 'reasoning'],
      roleStrengths: ['software_engineer'],
      weakDomains: ['multimodal', 'audio'],
      bestFor: ['local_code_completion', 'code_review'],
      avoidFor: ['vision', 'voice_chat'],
      languageStrengths: ['en', 'zh'],
      qualityTierLabel: 'PRO',
      costClassLabel: 'FREE',
      costConfidenceLabel: 'EXACT',
      estimatedInputCostPer1M: 0,
      estimatedOutputCostPer1M: 0,
      latencyClassLabel: 'MEDIUM',
      privacyClassLabel: 'local',
    },
  },
  {
    match: 'qwen-coder',
    enrichment: {
      supportsStreaming: true,
      supportsTools: true,
      supportsStructuredOutput: true,
      supportsVision: false,
      supportsAudioInput: false,
      supportsAudioOutput: false,
      supportsVideoInput: false,
      supportsFileInput: false,
      supportsEmbeddings: false,
      supportsLongContext: true,
      domainStrengths: ['coding'],
      roleStrengths: ['software_engineer'],
      weakDomains: ['multimodal'],
      bestFor: ['local_code_completion'],
      avoidFor: ['vision', 'voice_chat'],
      languageStrengths: ['en', 'zh'],
      qualityTierLabel: 'STANDARD',
      costClassLabel: 'FREE',
      costConfidenceLabel: 'EXACT',
      estimatedInputCostPer1M: 0,
      estimatedOutputCostPer1M: 0,
      latencyClassLabel: 'MEDIUM',
      privacyClassLabel: 'local',
    },
  },
  {
    match: 'deepseek-coder',
    enrichment: {
      supportsStreaming: true,
      supportsTools: true,
      supportsStructuredOutput: true,
      supportsVision: false,
      supportsAudioInput: false,
      supportsAudioOutput: false,
      supportsVideoInput: false,
      supportsFileInput: false,
      supportsEmbeddings: false,
      supportsLongContext: false,
      domainStrengths: ['coding'],
      roleStrengths: ['software_engineer'],
      weakDomains: ['multimodal', 'audio'],
      bestFor: ['local_code_completion'],
      avoidFor: ['vision'],
      languageStrengths: ['en', 'zh'],
      qualityTierLabel: 'STANDARD',
      costClassLabel: 'FREE',
      costConfidenceLabel: 'EXACT',
      estimatedInputCostPer1M: 0,
      estimatedOutputCostPer1M: 0,
      latencyClassLabel: 'MEDIUM',
      privacyClassLabel: 'local',
    },
  },
  // Reasoning-specialist families
  {
    match: 'deepseek-r1',
    enrichment: {
      supportsStreaming: true,
      supportsTools: false,
      supportsStructuredOutput: true,
      supportsVision: false,
      supportsAudioInput: false,
      supportsAudioOutput: false,
      supportsVideoInput: false,
      supportsFileInput: false,
      supportsEmbeddings: false,
      supportsLongContext: true,
      domainStrengths: ['reasoning', 'math'],
      roleStrengths: ['mathematician', 'researcher'],
      weakDomains: ['tool_use', 'multimodal'],
      bestFor: ['local_hard_reasoning', 'planning'],
      avoidFor: ['tool_calling', 'voice_chat'],
      languageStrengths: ['en', 'zh'],
      qualityTierLabel: 'PRO',
      costClassLabel: 'FREE',
      costConfidenceLabel: 'EXACT',
      estimatedInputCostPer1M: 0,
      estimatedOutputCostPer1M: 0,
      latencyClassLabel: 'SLOW',
      privacyClassLabel: 'local',
    },
  },
  {
    match: 'qwq',
    enrichment: {
      supportsStreaming: true,
      supportsTools: false,
      supportsStructuredOutput: true,
      supportsVision: false,
      supportsAudioInput: false,
      supportsAudioOutput: false,
      supportsVideoInput: false,
      supportsFileInput: false,
      supportsEmbeddings: false,
      supportsLongContext: true,
      domainStrengths: ['reasoning'],
      roleStrengths: ['researcher'],
      weakDomains: ['multimodal'],
      bestFor: ['local_reasoning'],
      avoidFor: ['voice_chat'],
      languageStrengths: ['en', 'zh'],
      qualityTierLabel: 'STANDARD',
      costClassLabel: 'FREE',
      costConfidenceLabel: 'EXACT',
      estimatedInputCostPer1M: 0,
      estimatedOutputCostPer1M: 0,
      latencyClassLabel: 'SLOW',
      privacyClassLabel: 'local',
    },
  },
  // General-purpose families
  {
    match: 'llama3.3',
    enrichment: {
      supportsStreaming: true,
      supportsTools: true,
      supportsStructuredOutput: true,
      supportsVision: false,
      supportsAudioInput: false,
      supportsAudioOutput: false,
      supportsVideoInput: false,
      supportsFileInput: false,
      supportsEmbeddings: false,
      supportsLongContext: true,
      domainStrengths: ['general', 'reasoning'],
      roleStrengths: ['writer', 'analyst'],
      weakDomains: ['multimodal'],
      bestFor: ['local_general_chat'],
      avoidFor: ['vision', 'voice_chat'],
      languageStrengths: ['en'],
      qualityTierLabel: 'STANDARD',
      costClassLabel: 'FREE',
      costConfidenceLabel: 'EXACT',
      estimatedInputCostPer1M: 0,
      estimatedOutputCostPer1M: 0,
      latencyClassLabel: 'MEDIUM',
      privacyClassLabel: 'local',
    },
  },
  {
    match: 'llama3',
    enrichment: {
      supportsStreaming: true,
      supportsTools: false,
      supportsStructuredOutput: false,
      supportsVision: false,
      supportsAudioInput: false,
      supportsAudioOutput: false,
      supportsVideoInput: false,
      supportsFileInput: false,
      supportsEmbeddings: false,
      supportsLongContext: false,
      domainStrengths: ['general'],
      roleStrengths: ['writer'],
      weakDomains: ['multimodal', 'audio'],
      bestFor: ['local_general_chat'],
      avoidFor: ['vision', 'voice_chat'],
      languageStrengths: ['en'],
      qualityTierLabel: 'BASIC',
      costClassLabel: 'FREE',
      costConfidenceLabel: 'EXACT',
      estimatedInputCostPer1M: 0,
      estimatedOutputCostPer1M: 0,
      latencyClassLabel: 'FAST',
      privacyClassLabel: 'local',
    },
  },
  {
    match: 'gemma',
    enrichment: {
      supportsStreaming: true,
      supportsTools: false,
      supportsStructuredOutput: true,
      supportsVision: false,
      supportsAudioInput: false,
      supportsAudioOutput: false,
      supportsVideoInput: false,
      supportsFileInput: false,
      supportsEmbeddings: false,
      supportsLongContext: false,
      domainStrengths: ['general', 'translation'],
      roleStrengths: ['writer'],
      weakDomains: ['multimodal'],
      bestFor: ['local_general_chat', 'router_fallback'],
      avoidFor: ['vision', 'voice_chat'],
      languageStrengths: ['en'],
      qualityTierLabel: 'BASIC',
      costClassLabel: 'FREE',
      costConfidenceLabel: 'EXACT',
      estimatedInputCostPer1M: 0,
      estimatedOutputCostPer1M: 0,
      latencyClassLabel: 'FAST',
      privacyClassLabel: 'local',
    },
  },
  {
    match: 'phi',
    enrichment: {
      supportsStreaming: true,
      supportsTools: false,
      supportsStructuredOutput: true,
      supportsVision: false,
      supportsAudioInput: false,
      supportsAudioOutput: false,
      supportsVideoInput: false,
      supportsFileInput: false,
      supportsEmbeddings: false,
      supportsLongContext: false,
      domainStrengths: ['general'],
      roleStrengths: ['writer', 'analyst'],
      weakDomains: ['multimodal'],
      bestFor: ['local_router', 'low_latency_chat'],
      avoidFor: ['vision'],
      languageStrengths: ['en'],
      qualityTierLabel: 'BASIC',
      costClassLabel: 'FREE',
      costConfidenceLabel: 'EXACT',
      estimatedInputCostPer1M: 0,
      estimatedOutputCostPer1M: 0,
      latencyClassLabel: 'FAST',
      privacyClassLabel: 'local',
    },
  },
  {
    match: 'mistral',
    enrichment: {
      supportsStreaming: true,
      supportsTools: false,
      supportsStructuredOutput: true,
      supportsVision: false,
      supportsAudioInput: false,
      supportsAudioOutput: false,
      supportsVideoInput: false,
      supportsFileInput: false,
      supportsEmbeddings: false,
      supportsLongContext: false,
      domainStrengths: ['general'],
      roleStrengths: ['writer'],
      weakDomains: ['multimodal'],
      bestFor: ['local_general_chat'],
      avoidFor: ['vision', 'voice_chat'],
      languageStrengths: ['en', 'fr'],
      qualityTierLabel: 'BASIC',
      costClassLabel: 'FREE',
      costConfidenceLabel: 'EXACT',
      estimatedInputCostPer1M: 0,
      estimatedOutputCostPer1M: 0,
      latencyClassLabel: 'FAST',
      privacyClassLabel: 'local',
    },
  },
  // Embedding-specialist families
  {
    match: 'nomic-embed',
    enrichment: {
      supportsStreaming: false,
      supportsTools: false,
      supportsStructuredOutput: false,
      supportsVision: false,
      supportsAudioInput: false,
      supportsAudioOutput: false,
      supportsVideoInput: false,
      supportsFileInput: false,
      supportsEmbeddings: true,
      supportsLongContext: false,
      domainStrengths: ['embedding'],
      roleStrengths: [],
      weakDomains: [],
      bestFor: ['local_embedding'],
      avoidFor: ['chat'],
      languageStrengths: ['en'],
      qualityTierLabel: 'STANDARD',
      costClassLabel: 'FREE',
      costConfidenceLabel: 'EXACT',
      estimatedInputCostPer1M: 0,
      estimatedOutputCostPer1M: 0,
      latencyClassLabel: 'FAST',
      privacyClassLabel: 'local',
    },
  },
]);
