export enum FeedbackSignal {
  POSITIVE = 'POSITIVE',
  NEGATIVE = 'NEGATIVE',
  JUDGE_VERIFIED = 'JUDGE_VERIFIED',
  JUDGE_REVISED = 'JUDGE_REVISED',
  JUDGE_ESCALATED = 'JUDGE_ESCALATED',
  FALLBACK_TRIGGERED = 'FALLBACK_TRIGGERED',
}
