export const INVOICE_DELIVERY_BATCH_SIZE = 20;
export const INVOICE_DELIVERY_JOB_NAME = 'invoice-delivery';
export const INVOICE_DELIVERY_LOCK_KEY = 'payment:jobs:invoice-delivery';
export const INVOICE_DELIVERY_LOCK_TTL_SECONDS = 30;
export const INVOICE_DELIVERY_POLL_INTERVAL_MS = 10_000;
export const INVOICE_DELIVERY_RETRY_BASE_DELAY_MS = 30_000;
export const INVOICE_DELIVERY_RETRY_MAX_DELAY_MS = 3_600_000;
export const INVOICE_DELIVERY_ERROR_CODE = 'INVOICE_EMAIL_DELIVERY_FAILED';
