// SCAFFOLD: stream R.4 (05-r4-cost-budget-intelligence)

export const BUDGET_DEFAULT_WARN_AT_PERCENT = 80;
export const BUDGET_DEFAULT_RESET_INTERVAL_DAYS = 30;

export const BUDGET_MESSAGE_KEY_NEAR_LIMIT = 'BUDGET_NEAR_LIMIT';
export const BUDGET_MESSAGE_KEY_EXCEEDED_FORCED_LOCAL = 'BUDGET_EXCEEDED_FORCED_LOCAL';
export const BUDGET_MESSAGE_KEY_EXCEEDED_OVERRIDDEN = 'BUDGET_EXCEEDED_OVERRIDDEN';
export const BUDGET_MESSAGE_KEY_UNKNOWN_COST_BLOCKED = 'BUDGET_UNKNOWN_COST_BLOCKED';
