export enum AuditAction {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  ACCESS = "ACCESS",
  EXPORT = "EXPORT",
  IMPORT = "IMPORT",
  SETTINGS_CHANGE = "SETTINGS_CHANGE",
  CONNECTOR_SYNC = "CONNECTOR_SYNC",
  ROUTING_DECISION = "ROUTING_DECISION",
}
