export const SD_PROGRESS_POLL_MIN_INTERVAL_MS = 300;
export const SD_PROGRESS_POLL_DEFAULT_INTERVAL_MS = 1000;
export const SD_PROGRESS_MAX_CONSECUTIVE_ERRORS = 5;
export const SD_PROGRESS_HTTP_TIMEOUT_MS = 8000;
export const SD_INTERRUPT_HTTP_TIMEOUT_MS = 5000;
