export enum StreamEventType {
  CHUNK = 'chunk',
  // Rich streaming events (live token/reasoning/metric deltas).
  LIFECYCLE = 'lifecycle',
  CONTENT_DELTA = 'content_delta',
  REASONING_DELTA = 'reasoning_delta',
  METRICS = 'metrics',
  USAGE = 'usage',
  REQUEST_ACCEPTED = 'request_accepted',
  ROUTER_STARTED = 'router_started',
  ROUTER_COMPLETED = 'router_completed',
  TOOL_STARTED = 'tool_started',
  TOOL_COMPLETED = 'tool_completed',
  RESEARCH_STARTED = 'research_started',
  RESEARCH_COMPLETED = 'research_completed',
  DONE = 'done',
  ERROR = 'error',
  FALLBACK_ATTEMPT = 'fallback_attempt',
  JUDGE_EVALUATING = 'judge_evaluating',
  PROVIDER_SELECTED = 'provider_selected',
  MODEL_PROGRESS = 'model_progress',
  RESPONSE_STREAMING = 'response_streaming',
}
