export enum GatewayConfigErrorCode {
  INVALID_FIELDS = 'GATEWAY_CONFIG_INVALID_FIELDS',
  UNAVAILABLE = 'GATEWAY_CONFIG_UNAVAILABLE',
  SEED_CHECKSUM_MISMATCH = 'GATEWAY_CONFIG_SEED_CHECKSUM_MISMATCH',
}
