export enum RuntimeProbeStatus {
  REACHABLE = 'REACHABLE',
  UNREACHABLE = 'UNREACHABLE',
  DEGRADED = 'DEGRADED',
  BINARY_MISSING = 'BINARY_MISSING',
  NOT_CONFIGURED = 'NOT_CONFIGURED',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
}
