export enum RuntimeProgressEventType {
  LIFECYCLE = 'LIFECYCLE',
  REASONING_DELTA = 'REASONING_DELTA',
  CONTENT_DELTA = 'CONTENT_DELTA',
  IMAGE_PREVIEW = 'IMAGE_PREVIEW',
  NODE_PROGRESS = 'NODE_PROGRESS',
  STEP_PROGRESS = 'STEP_PROGRESS',
  PROMPT_EVAL_PROGRESS = 'PROMPT_EVAL_PROGRESS',
  METRICS = 'METRICS',
  USAGE = 'USAGE',
  ARTIFACT_SAVED = 'ARTIFACT_SAVED',
  ERROR = 'ERROR',
}
