import { type RuntimeModality } from './runtime-modality.enum';
import { type RuntimeProgressConfidence } from './runtime-progress-confidence.enum';
import { type RuntimeProgressEventType } from './runtime-progress-event-type.enum';
import { type RuntimeProgressStage } from './runtime-progress-stage.enum';
import { type RuntimeProvider } from './runtime-provider.enum';
import { type StreamingErrorType } from './streaming-error-type.enum';
import { type VisibleReasoningSource } from './visible-reasoning-source.enum';

export type RuntimeProgressMetrics = {
  startedAtMs: number;
  elapsedMs: number;
  timeToFirstByteMs?: number;
  timeToFirstTokenMs?: number;
  timeToFirstThinkingMs?: number;
  modelLoadMs?: number;
  promptEvalMs?: number;
  generationMs?: number;
  samplingMs?: number;
  saveMs?: number;
  promptTokens?: number;
  outputTokens?: number;
  totalTokens?: number;
  tokensPerSecond?: number;
  currentStep?: number;
  totalSteps?: number;
  stepsPerSecond?: number;
  queuePosition?: number;
  progressPercent?: number;
  progressConfidence: RuntimeProgressConfidence;
  bottleneckStage?: RuntimeProgressStage;
};

export type ClawRuntimeProgressEvent = {
  id: string;
  runId: string;
  version: 'runtime-progress-v1';
  conversationId?: string;
  messageId?: string;
  jobId?: string;
  laneId?: string;
  parallelGroupId?: string;
  provider: RuntimeProvider;
  modality: RuntimeModality;
  modelId?: string;
  runtimeUrl?: string;
  eventType: RuntimeProgressEventType;
  stage: RuntimeProgressStage;
  createdAtMs: number;
  sequence: number;
  contentDelta?: string;
  reasoningDelta?: string;
  visibleReasoningSource?: VisibleReasoningSource;
  nodeId?: string;
  nodeName?: string;
  imagePreviewBase64?: string;
  artifactId?: string;
  metrics?: RuntimeProgressMetrics;
  rawProviderEventType?: string;
  errorType?: StreamingErrorType;
  errorMessage?: string;
};
