export enum StreamingErrorType {
  NETWORK_TIMEOUT = 'NETWORK_TIMEOUT',
  RUNTIME_UNREACHABLE = 'RUNTIME_UNREACHABLE',
  BINARY_NOT_INSTALLED = 'BINARY_NOT_INSTALLED',
  WEIGHTS_MISSING = 'WEIGHTS_MISSING',
  MODEL_LOAD_FAILED = 'MODEL_LOAD_FAILED',
  OOM = 'OOM',
  GPU_DRIVER_ERROR = 'GPU_DRIVER_ERROR',
  CONTEXT_OVERFLOW = 'CONTEXT_OVERFLOW',
  DECODER_ERROR = 'DECODER_ERROR',
  WORKFLOW_INVALID = 'WORKFLOW_INVALID',
  USER_CANCELLED = 'USER_CANCELLED',
  PROVIDER_RATE_LIMITED = 'PROVIDER_RATE_LIMITED',
}
