export enum VisibleReasoningSource {
  NONE = 'NONE',
  OLLAMA_THINKING_FIELD = 'OLLAMA_THINKING_FIELD',
  THINK_TAG = 'THINK_TAG',
  THINKING_TAG = 'THINKING_TAG',
  REASONING_TAG = 'REASONING_TAG',
  LLAMACPP_REASONING_CONTENT = 'LLAMACPP_REASONING_CONTENT',
  MODEL_VISIBLE_TEXT = 'MODEL_VISIBLE_TEXT',
  PROVIDER_EXPOSED = 'PROVIDER_EXPOSED',
}
