ALTER TYPE "SearchProviderKind" ADD VALUE IF NOT EXISTS 'EXA';
ALTER TYPE "SearchProviderKind" ADD VALUE IF NOT EXISTS 'FIRECRAWL';
ALTER TYPE "SearchProviderKind" ADD VALUE IF NOT EXISTS 'BRAVE';
ALTER TYPE "SearchProviderKind" ADD VALUE IF NOT EXISTS 'SERPAPI';
