import { AUTH_EMAIL_DICTIONARIES } from '../copy';
import { AUTH_EMAIL_RTL_LOCALES, AUTH_EMAIL_THEME } from '../constants/auth-email-theme.constants';
import type { AuthEmailRenderInput, RenderedAuthEmail } from '../types/auth-email-render.type';

// Every character that can change the meaning of an HTML document. Applied to
// EVERY interpolated value without exception — including ones that look safe,
// like a one-time code — because "this one is generated by us" is the
// assumption that turns into an injection the day the source changes. It
// replaces the unescaped template literals the adapter used to build by hand,
// one of which interpolated a user-supplied email address.
function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function fill(template: string, value: string | null, expiry: string | null): string {
  let filled = template;
  if (value !== null) {
    filled = filled.replaceAll('{value}', value);
  }
  if (expiry !== null) {
    filled = filled.replaceAll('{expiry}', expiry);
  }
  return filled;
}

function paragraph(text: string, align: string): string {
  return `<p style="margin:0 0 16px;font-size:15px;line-height:1.65;color:${AUTH_EMAIL_THEME.bodyColor};text-align:${align}">${text}</p>`;
}

function resolveGreeting(template: string, fallback: string, name: string | null): string {
  if (name === null || name.trim().length === 0) {
    return fallback;
  }
  return template.replaceAll('{value}', name);
}

/**
 * Render one transactional auth email in the account holder's own language.
 *
 * Two deliberate constraints shape the markup:
 *
 *   - **Tables and inline styles only.** Every serious email client strips
 *     `<style>` blocks, ignores flexbox and disagrees about `class`. A layout
 *     that renders in a browser and collapses in Outlook is not a layout.
 *   - **The renderer owns every tag.** Copy files carry text, never markup, and
 *     all of it is escaped on the way in. That is what makes translating an
 *     email a safe, non-engineering change.
 *
 * Arabic and Persian get `dir="rtl"` and right-aligned text throughout, with
 * one exception: the literal URL stays `dir="ltr"`, because an RTL paragraph
 * reorders a link into an address that does not survive copy-and-paste.
 */
export function renderAuthEmail(input: AuthEmailRenderInput): RenderedAuthEmail {
  const dictionary = AUTH_EMAIL_DICTIONARIES[input.locale];
  const copy = dictionary.emails[input.kind];
  const chrome = dictionary.chrome;
  const isRtl = AUTH_EMAIL_RTL_LOCALES.has(input.locale);
  const dir = isRtl ? 'rtl' : 'ltr';
  const align = isRtl ? 'right' : 'left';

  const safeValue = input.value === null ? null : escapeHtml(input.value);
  const safeExpiry = input.expiry === null ? null : escapeHtml(input.expiry);

  const htmlBlocks: string[] = [
    `<h1 style="margin:0 0 20px;font-size:22px;line-height:1.3;font-weight:700;color:${AUTH_EMAIL_THEME.headingColor};text-align:${align}">${escapeHtml(copy.heading)}</h1>`,
    paragraph(
      escapeHtml(resolveGreeting(chrome.greeting, chrome.greetingFallback, input.recipientName)),
      align,
    ),
    paragraph(fill(escapeHtml(copy.intro), safeValue, safeExpiry), align),
    ...copy.bodyLines.map((line) =>
      paragraph(fill(escapeHtml(line), safeValue, safeExpiry), align),
    ),
  ];

  const textBlocks: string[] = [
    copy.heading,
    '',
    resolveGreeting(chrome.greeting, chrome.greetingFallback, input.recipientName),
    '',
    fill(copy.intro, input.value, input.expiry),
    ...copy.bodyLines.map((line) => fill(line, input.value, input.expiry)),
  ];

  if (input.actionUrl !== null && copy.actionLabel !== null) {
    const safeUrl = escapeHtml(input.actionUrl);
    htmlBlocks.push(
      `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 20px"><tr><td align="center" bgcolor="${AUTH_EMAIL_THEME.accentColor}" style="border-radius:10px"><a href="${safeUrl}" style="display:inline-block;padding:13px 28px;font-size:15px;font-weight:600;color:${AUTH_EMAIL_THEME.accentTextColor};text-decoration:none;border-radius:10px">${escapeHtml(copy.actionLabel)}</a></td></tr></table>`,
    );
    if (copy.fallbackNote !== null) {
      htmlBlocks.push(
        `<p style="margin:0 0 8px;font-size:13px;line-height:1.6;color:${AUTH_EMAIL_THEME.mutedColor};text-align:${align}">${escapeHtml(copy.fallbackNote)}</p>`,
        `<p dir="ltr" style="margin:0 0 20px;font-size:13px;line-height:1.6;word-break:break-all;text-align:left"><a href="${safeUrl}" style="color:${AUTH_EMAIL_THEME.accentColor}">${safeUrl}</a></p>`,
      );
    }
    textBlocks.push('', `${copy.actionLabel}: ${input.actionUrl}`);
  }

  if (copy.expiryNote !== null) {
    htmlBlocks.push(
      `<p style="margin:0 0 16px;font-size:13px;line-height:1.6;color:${AUTH_EMAIL_THEME.mutedColor};text-align:${align}">${fill(escapeHtml(copy.expiryNote), safeValue, safeExpiry)}</p>`,
    );
    textBlocks.push('', fill(copy.expiryNote, input.value, input.expiry));
  }

  htmlBlocks.push(
    `<p style="margin:0 0 4px;font-size:13px;line-height:1.6;color:${AUTH_EMAIL_THEME.mutedColor};text-align:${align}">${escapeHtml(copy.securityNote)}</p>`,
    `<p style="margin:24px 0 0;font-size:15px;line-height:1.6;color:${AUTH_EMAIL_THEME.bodyColor};text-align:${align}">${escapeHtml(chrome.signOff)}<br>${escapeHtml(chrome.teamName)}</p>`,
  );
  textBlocks.push('', copy.securityNote, '', chrome.signOff, chrome.teamName);

  const safeSiteUrl = escapeHtml(input.siteUrl);
  const html = [
    `<!doctype html><html lang="${input.locale.toLowerCase()}" dir="${dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(copy.subject)}</title></head>`,
    `<body dir="${dir}" style="margin:0;padding:0;background:${AUTH_EMAIL_THEME.pageColor};font-family:${AUTH_EMAIL_THEME.fontStack}">`,
    // The preheader: shown by the inbox beside the subject, hidden inside the
    // message. Without one, clients pull the first words of the body — which
    // is the greeting, and tells the reader nothing.
    `<div style="display:none;max-height:0;overflow:hidden;opacity:0">${escapeHtml(copy.preheader)}</div>`,
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${AUTH_EMAIL_THEME.pageColor};padding:32px 16px"><tr><td align="center">`,
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;background:${AUTH_EMAIL_THEME.cardColor};border:1px solid ${AUTH_EMAIL_THEME.borderColor};border-radius:16px">`,
    `<tr><td style="padding:28px 32px 0;text-align:${align}"><span style="font-size:18px;font-weight:700;color:${AUTH_EMAIL_THEME.headingColor};letter-spacing:-0.01em">${AUTH_EMAIL_THEME.brandName}</span></td></tr>`,
    `<tr><td style="padding:20px 32px 28px">${htmlBlocks.join('')}</td></tr>`,
    `<tr><td style="padding:0 32px 28px"><hr style="border:none;border-top:1px solid ${AUTH_EMAIL_THEME.borderColor};margin:0 0 16px"><p style="margin:0;font-size:12px;line-height:1.6;color:${AUTH_EMAIL_THEME.mutedColor};text-align:${align}">${escapeHtml(chrome.footerNote)}</p><p dir="ltr" style="margin:8px 0 0;font-size:12px;text-align:left"><a href="${safeSiteUrl}" style="color:${AUTH_EMAIL_THEME.mutedColor}">${safeSiteUrl}</a></p></td></tr>`,
    `</table></td></tr></table></body></html>`,
  ].join('');

  textBlocks.push('', chrome.footerNote, input.siteUrl);

  return { subject: copy.subject, text: textBlocks.join('\n'), html };
}
