export const COMMAND_EXPIRY_MINUTES = 10;
export const COMMAND_EXPIRY_MS = COMMAND_EXPIRY_MINUTES * 60 * 1000;
export const SESSION_HEARTBEAT_TIMEOUT_SECONDS = 120;
export const SESSION_KEY_BYTE_LENGTH = 32;
export const MAX_COMMAND_BATCH_POLL = 5;
export const FILE_EVENT_BATCH_MAX = 100;
export const CLEANUP_INTERVAL_MS = 60_000;
export const STUCK_EXECUTING_TIMEOUT_MS = 5 * 60 * 1000;
