// Stable, machine-readable billing error codes returned to clients.
//
// These are part of the public API contract: the frontend maps each to an i18n
// key. They never carry provider payloads, stack traces, secret identifiers, or
// internal cost-budget values.
export enum BillingErrorCode {
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',
  PLAN_INACTIVE = 'PLAN_INACTIVE',
  PLAN_NOT_PURCHASABLE = 'PLAN_NOT_PURCHASABLE',
  // The price source of truth could not be reached or did not validate. A
  // checkout fails on this rather than proceeding with a price we invented.
  PLAN_CATALOG_UNAVAILABLE = 'PLAN_CATALOG_UNAVAILABLE',
  PLAN_PRICE_NOT_FOUND = 'PLAN_PRICE_NOT_FOUND',
  SUBSCRIPTION_ALREADY_ACTIVE = 'SUBSCRIPTION_ALREADY_ACTIVE',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  CHECKOUT_SESSION_EXPIRED = 'CHECKOUT_SESSION_EXPIRED',
  CHECKOUT_SESSION_NOT_FOUND = 'CHECKOUT_SESSION_NOT_FOUND',
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
  PAYMENT_NOT_VERIFIED = 'PAYMENT_NOT_VERIFIED',
  PAYMENT_AMOUNT_MISMATCH = 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_CURRENCY_MISMATCH = 'PAYMENT_CURRENCY_MISMATCH',
  PAYMENT_REFERENCE_MISMATCH = 'PAYMENT_REFERENCE_MISMATCH',
  WEBHOOK_SIGNATURE_INVALID = 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_REPLAYED = 'WEBHOOK_REPLAYED',
  PRORATION_QUOTE_EXPIRED = 'PRORATION_QUOTE_EXPIRED',
  PRORATION_QUOTE_NOT_FOUND = 'PRORATION_QUOTE_NOT_FOUND',
  SUBSCRIPTION_CHANGE_CONFLICT = 'SUBSCRIPTION_CHANGE_CONFLICT',
  PAYMENT_METHOD_UNAVAILABLE = 'PAYMENT_METHOD_UNAVAILABLE',
  PAYMENT_METHOD_NOT_FOUND = 'PAYMENT_METHOD_NOT_FOUND',
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  REFUND_NOT_FOUND = 'REFUND_NOT_FOUND',
  REFUND_TRANSACTION_NOT_REFUNDABLE = 'REFUND_TRANSACTION_NOT_REFUNDABLE',
  REFUND_AMOUNT_INVALID = 'REFUND_AMOUNT_INVALID',
  REFUND_AMOUNT_EXCEEDS_REMAINING = 'REFUND_AMOUNT_EXCEEDS_REMAINING',
  GATEWAY_UNAVAILABLE = 'GATEWAY_UNAVAILABLE',
  GATEWAY_NOT_CONFIGURED = 'GATEWAY_NOT_CONFIGURED',
  CURRENCY_UNSUPPORTED = 'CURRENCY_UNSUPPORTED',
  FX_QUOTE_EXPIRED = 'FX_QUOTE_EXPIRED',
  FX_RATE_UNAVAILABLE = 'FX_RATE_UNAVAILABLE',
  IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED',
  QUOTA_DAILY_EXCEEDED = 'QUOTA_DAILY_EXCEEDED',
  QUOTA_WEEKLY_EXCEEDED = 'QUOTA_WEEKLY_EXCEEDED',
  QUOTA_MONTHLY_EXCEEDED = 'QUOTA_MONTHLY_EXCEEDED',
  QUOTA_BILLING_PERIOD_EXCEEDED = 'QUOTA_BILLING_PERIOD_EXCEEDED',
  PROVIDER_COST_BUDGET_EXCEEDED = 'PROVIDER_COST_BUDGET_EXCEEDED',
  FEATURE_TRIAL_EXHAUSTED = 'FEATURE_TRIAL_EXHAUSTED',
  FEATURE_LIMIT_EXCEEDED = 'FEATURE_LIMIT_EXCEEDED',
  FEATURE_DISABLED = 'FEATURE_DISABLED',
  MODEL_NOT_ALLOWED_FOR_PLAN = 'MODEL_NOT_ALLOWED_FOR_PLAN',
  ADMIN_GRANT_REASON_REQUIRED = 'ADMIN_GRANT_REASON_REQUIRED',
  // --- PAYG connector credit (ADR-078) ---
  // Distinct from QUOTA_* on purpose: a token quota and a dollar balance are
  // different things to the user and have different remedies. A quota resets
  // tomorrow; credit needs a top-up. Mapping both to one code is what makes an
  // error message tell someone to wait when they should be buying.
  PAYG_CREDIT_EXHAUSTED = 'PAYG_CREDIT_EXHAUSTED',
  // The prompt alone costs more than the whole remaining balance, so no
  // shortening of the answer can make the request fit.
  PAYG_PROMPT_TOO_EXPENSIVE = 'PAYG_PROMPT_TOO_EXPENSIVE',
  // The model has no published price. An unpriced model on a metered provider
  // is UNSAFE, not free — it is unbounded liability. Fails closed.
  PAYG_MODEL_UNPRICED = 'PAYG_MODEL_UNPRICED',
  // The price registry could not be reached and nothing is cached. OUR outage,
  // not the user's empty wallet — the copy must say so, or we sell a top-up
  // that was never needed.
  PAYG_PRICING_UNAVAILABLE = 'PAYG_PRICING_UNAVAILABLE',
  CREDIT_PACKAGE_NOT_FOUND = 'CREDIT_PACKAGE_NOT_FOUND',
  CREDIT_PACKAGE_INACTIVE = 'CREDIT_PACKAGE_INACTIVE',
  // A refund or chargeback exceeds the unspent PURCHASED balance. Spent credit
  // is consumed irreversibly and is not refundable.
  CREDIT_REVERSAL_EXCEEDS_UNSPENT = 'CREDIT_REVERSAL_EXCEEDS_UNSPENT',
  CREDIT_ADJUSTMENT_REASON_REQUIRED = 'CREDIT_ADJUSTMENT_REASON_REQUIRED',
}
