export enum FeedbackType {
  BUG_REPORT = 'BUG_REPORT',
  GENERAL_FEEDBACK = 'GENERAL_FEEDBACK',
  FEATURE_REQUEST = 'FEATURE_REQUEST',
  UI_UX = 'UI_UX',
  PERFORMANCE = 'PERFORMANCE',
  DATA_ISSUE = 'DATA_ISSUE',
  INTEGRATION_ISSUE = 'INTEGRATION_ISSUE',
  DOCUMENTATION = 'DOCUMENTATION',
  SECURITY_CONCERN = 'SECURITY_CONCERN',
  OTHER = 'OTHER',
}
