export enum JudgeCriterionKey {
  CORRECTNESS = 'CORRECTNESS',
  COMPLETENESS = 'COMPLETENESS',
  CLARITY = 'CLARITY',
  HELPFULNESS = 'HELPFULNESS',
  SAFETY = 'SAFETY',
  INSTRUCTION_FOLLOWING = 'INSTRUCTION_FOLLOWING',
}
