export enum LocalModelRole {
  ROUTER = 'ROUTER',
  LOCAL_FALLBACK_CHAT = 'LOCAL_FALLBACK_CHAT',
  LOCAL_REASONING = 'LOCAL_REASONING',
  LOCAL_CODING = 'LOCAL_CODING',
  LOCAL_FILE_GENERATION = 'LOCAL_FILE_GENERATION',
  LOCAL_THINKING = 'LOCAL_THINKING',
  LOCAL_IMAGE_GENERATION = 'LOCAL_IMAGE_GENERATION',
}
