export enum MemoryAuditAction {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  USED = 'USED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  TOGGLED = 'TOGGLED',
  PAUSED = 'PAUSED',
  RESUMED = 'RESUMED',
  REDACTED = 'REDACTED',
  IMPORTED = 'IMPORTED',
  EXPORTED = 'EXPORTED',
}
