export enum ModelCapability {
  TEXT = 'TEXT',
  VISION = 'VISION',
  AUDIO = 'AUDIO',
  TOOLS = 'TOOLS',
  STRUCTURED_OUTPUT = 'STRUCTURED_OUTPUT',
  IMAGE_GENERATION = 'IMAGE_GENERATION',
  FILE_GENERATION = 'FILE_GENERATION',
  JUDGE = 'JUDGE',
}
