export enum RetrievalReason {
  PINNED = 'PINNED',
  INTENT_MATCH = 'INTENT_MATCH',
  PREFERENCE = 'PREFERENCE',
  EXPLICIT_ATTACH = 'EXPLICIT_ATTACH',
  WORKSPACE_HIT = 'WORKSPACE_HIT',
  RESEARCH_EVIDENCE = 'RESEARCH_EVIDENCE',
  FILE_ATTACHED = 'FILE_ATTACHED',
  PROVENANCE_LINK = 'PROVENANCE_LINK',
}
