export const BILLING_DASHBOARD_DAY_MS = 86_400_000;
export const BILLING_DASHBOARD_BASIS_POINTS = 10_000;
export const ACTIVE_SUBSCRIPTION_STATUSES = new Set(['ACTIVE', 'PAST_DUE', 'CANCEL_AT_PERIOD_END']);
