export const EMAIL_CHANGE_OTP_DIGITS = 6;
export const EMAIL_CHANGE_OTP_TTL_MS = 10 * 60 * 1000;
export const EMAIL_CHANGE_OTP_MAX_ATTEMPTS = 5;
export const EMAIL_CHANGE_RESEND_COOLDOWN_MS = 60 * 1000;
export const EMAIL_CHANGE_MAX_REQUESTS_PER_DAY = 5;
export const EMAIL_CHANGE_NEW_EMAIL_TOKEN_BYTES = 32;
export const EMAIL_CHANGE_NEW_EMAIL_TOKEN_TTL_MS = 30 * 60 * 1000;
