import { EventPattern } from '@claw/shared-types';

export const BILLING_AUDIT_SUBSCRIPTIONS = [
  [EventPattern.BILLING_SUBSCRIPTION_ACTIVATED, 'BILLING_SUBSCRIPTION_ACTIVATED', 'MEDIUM'],
  [EventPattern.BILLING_SUBSCRIPTION_RENEWED, 'BILLING_SUBSCRIPTION_RENEWED', 'LOW'],
  [EventPattern.BILLING_SUBSCRIPTION_UPGRADED, 'BILLING_SUBSCRIPTION_UPGRADED', 'MEDIUM'],
  [
    EventPattern.BILLING_SUBSCRIPTION_DOWNGRADE_SCHEDULED,
    'BILLING_SUBSCRIPTION_DOWNGRADE_SCHEDULED',
    'LOW',
  ],
  [EventPattern.BILLING_SUBSCRIPTION_DOWNGRADED, 'BILLING_SUBSCRIPTION_DOWNGRADED', 'MEDIUM'],
  [EventPattern.BILLING_SUBSCRIPTION_CANCELLED, 'BILLING_SUBSCRIPTION_CANCELLED', 'MEDIUM'],
  [EventPattern.BILLING_SUBSCRIPTION_EXPIRED, 'BILLING_SUBSCRIPTION_EXPIRED', 'MEDIUM'],
  [EventPattern.BILLING_SUBSCRIPTION_PAST_DUE, 'BILLING_SUBSCRIPTION_PAST_DUE', 'HIGH'],
  [EventPattern.BILLING_SUBSCRIPTION_SUSPENDED, 'BILLING_SUBSCRIPTION_SUSPENDED', 'HIGH'],
  [EventPattern.BILLING_PAYMENT_REFUNDED, 'BILLING_PAYMENT_REFUNDED', 'HIGH'],
  [EventPattern.BILLING_PAYMENT_CHARGEBACK, 'BILLING_PAYMENT_CHARGEBACK', 'HIGH'],
  [
    EventPattern.BILLING_ENTITLEMENT_RECONCILE_REQUESTED,
    'BILLING_ENTITLEMENT_RECONCILE_REQUESTED',
    'HIGH',
  ],
] as const;
