export const USER_DELETION_OUTBOX_BATCH_SIZE = 20;
export const USER_DELETION_OUTBOX_POLL_INTERVAL_MS = 10_000;
export const USER_DELETION_OUTBOX_STALE_PUBLISHING_MS = 5 * 60_000;
export const USER_DELETION_OUTBOX_RETRY_BASE_DELAY_MS = 5_000;
export const USER_DELETION_OUTBOX_RETRY_MAX_DELAY_MS = 5 * 60_000;
