import { PrismaClient } from '../src/generated/prisma';

const prisma = new PrismaClient();

const CATALOG_ENTRIES = [
  // ─── CODING (5 models) ──────────────────────────────────────────────
  {
    name: 'qwen2.5-coder',
    tag: '32b',
    displayName: 'Qwen 2.5 Coder 32B',
    category: 'CODING',
    description: 'Best local coding model, 300+ languages. Matches GPT-4o on HumanEval (73.7).',
    sizeBytes: BigInt(21_474_836_480),
    parameterCount: '32B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen2.5-coder:32b',
    isRecommended: true,
    capabilities: [
      'code_generation',
      'code_review',
      'debugging',
      'refactoring',
      'multilingual_code',
    ],
  },
  {
    name: 'qwen2.5-coder',
    tag: '14b',
    displayName: 'Qwen 2.5 Coder 14B',
    category: 'CODING',
    description: 'Sweet spot for quality vs hardware. Top-rated coding model under 20B params.',
    sizeBytes: BigInt(9_663_676_416),
    parameterCount: '14B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen2.5-coder:14b',
    isRecommended: false,
    capabilities: ['code_generation', 'code_review', 'debugging', 'refactoring'],
  },
  {
    name: 'qwen2.5-coder',
    tag: '7b',
    displayName: 'Qwen 2.5 Coder 7B',
    category: 'CODING',
    description: 'Best coding model for 8-12GB VRAM. HumanEval 76.0 in 7B class.',
    sizeBytes: BigInt(5_046_586_573),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen2.5-coder:7b',
    isRecommended: false,
    capabilities: ['code_generation', 'debugging', 'code_completion'],
  },
  {
    name: 'deepseek-coder-v2',
    tag: '16b',
    displayName: 'DeepSeek Coder V2 16B',
    category: 'CODING',
    description: 'Specialist in debugging and code completion. LiveCodeBench 90%.',
    sizeBytes: BigInt(10_737_418_240),
    parameterCount: '16B',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-coder-v2:16b',
    isRecommended: false,
    capabilities: ['code_generation', 'debugging', 'code_completion', 'code_explanation'],
  },
  {
    name: 'starcoder2',
    tag: '7b',
    displayName: 'StarCoder2 7B',
    category: 'CODING',
    description: 'Lightweight model good for autocomplete and code completion.',
    sizeBytes: BigInt(4_831_838_208),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'starcoder2:7b',
    isRecommended: false,
    capabilities: ['code_completion', 'code_generation'],
  },

  // ─── FILE GENERATION (5 models) ─────────────────────────────────────
  {
    name: 'qwen3',
    tag: '7b',
    displayName: 'Qwen 3 7B',
    category: 'FILE_GENERATION',
    description: 'Best instruction following for structured output (markdown, JSON, CSV).',
    sizeBytes: BigInt(5_046_586_573),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3:7b',
    isRecommended: true,
    capabilities: ['structured_output', 'markdown', 'json', 'csv', 'instruction_following'],
  },
  {
    name: 'llama3.3',
    tag: '8b',
    displayName: 'Llama 3.3 8B',
    category: 'FILE_GENERATION',
    description: 'Best all-around content writer with clean formatting.',
    sizeBytes: BigInt(5_368_709_120),
    parameterCount: '8B',
    runtime: 'OLLAMA',
    ollamaName: 'llama3.3:8b',
    isRecommended: false,
    capabilities: ['content_writing', 'formatting', 'structured_output'],
  },
  {
    name: 'mistral-small3',
    tag: '7b',
    displayName: 'Mistral Small 3 7B',
    category: 'FILE_GENERATION',
    description: 'Fastest throughput — ideal for bulk file generation.',
    sizeBytes: BigInt(4_831_838_208),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'mistral-small3:7b',
    isRecommended: false,
    capabilities: ['fast_generation', 'structured_output', 'content_writing'],
  },
  {
    name: 'phi4',
    tag: '14b',
    displayName: 'Phi-4 14B',
    category: 'FILE_GENERATION',
    description: 'Best analytical writing (reports, technical docs). Beats GPT-4o on MATH.',
    sizeBytes: BigInt(9_663_676_416),
    parameterCount: '14B',
    runtime: 'OLLAMA',
    ollamaName: 'phi4:14b',
    isRecommended: false,
    capabilities: ['analytical_writing', 'technical_docs', 'reports', 'reasoning'],
  },
  {
    name: 'gemma3',
    tag: '9b',
    displayName: 'Gemma 3 9B',
    category: 'FILE_GENERATION',
    description: 'Strong multilingual content generation from Google.',
    sizeBytes: BigInt(6_442_450_944),
    parameterCount: '9B',
    runtime: 'OLLAMA',
    ollamaName: 'gemma3:9b',
    isRecommended: false,
    capabilities: ['multilingual', 'content_writing', 'structured_output'],
  },

  // ─── IMAGE GENERATION (5 models) ────────────────────────────────────
  {
    name: 'flux.2-dev',
    tag: 'latest',
    displayName: 'FLUX.2 Dev',
    category: 'IMAGE_GENERATION',
    description: 'Most photorealistic open-source image model in 2026. 12B parameters.',
    sizeBytes: BigInt(25_769_803_776),
    parameterCount: '12B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: true,
    capabilities: ['photorealistic', 'text_to_image', 'high_quality'],
  },
  {
    name: 'flux.1-schnell',
    tag: 'latest',
    displayName: 'FLUX.1 Schnell',
    category: 'IMAGE_GENERATION',
    description: 'Fast variant (1-4 steps), free for local use.',
    sizeBytes: BigInt(12_884_901_888),
    parameterCount: '12B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: false,
    capabilities: ['fast_generation', 'text_to_image'],
  },
  {
    name: 'sd-3.5',
    tag: 'latest',
    displayName: 'Stable Diffusion 3.5',
    category: 'IMAGE_GENERATION',
    description: 'Stability AI flagship. Great quality/speed ratio.',
    sizeBytes: BigInt(8_589_934_592),
    parameterCount: '8B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: false,
    capabilities: ['text_to_image', 'image_to_image', 'inpainting'],
  },
  {
    name: 'sdxl-lightning',
    tag: 'latest',
    displayName: 'SDXL-Lightning',
    category: 'IMAGE_GENERATION',
    description: 'Ultra-fast (1-4 step generation), real-time capable.',
    sizeBytes: BigInt(8_589_934_592),
    parameterCount: '6.6B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: false,
    capabilities: ['ultra_fast', 'text_to_image', 'realtime'],
  },
  {
    name: 'z-image-turbo',
    tag: 'latest',
    displayName: 'Z-Image-Turbo',
    category: 'IMAGE_GENERATION',
    description: 'Matches larger models. Apache 2.0, bilingual text rendering.',
    sizeBytes: BigInt(6_442_450_944),
    parameterCount: '~6B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: false,
    capabilities: ['text_to_image', 'bilingual_text', 'fast_generation'],
  },

  // ─── ROUTING (5 models) ─────────────────────────────────────────────
  {
    name: 'qwen3',
    tag: '1.7b',
    displayName: 'Qwen 3 1.7B',
    category: 'ROUTING',
    description: 'Purpose-built for intent classification + structured JSON. <200ms routing.',
    sizeBytes: BigInt(1_288_490_189),
    parameterCount: '1.7B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3:1.7b',
    isRecommended: true,
    capabilities: ['intent_classification', 'structured_output', 'json', 'ultra_fast'],
  },
  {
    name: 'phi4-mini',
    tag: '3.8b',
    displayName: 'Phi-4-mini 3.8B',
    category: 'ROUTING',
    description: 'Best reasoning per GB — accurate routing on tiny hardware. <300ms.',
    sizeBytes: BigInt(2_469_606_195),
    parameterCount: '3.8B',
    runtime: 'OLLAMA',
    ollamaName: 'phi4-mini',
    isRecommended: false,
    capabilities: ['intent_classification', 'reasoning', 'structured_output'],
  },
  {
    name: 'smollm2',
    tag: '1.7b',
    displayName: 'SmolLM2 1.7B',
    category: 'ROUTING',
    description: 'Ultra-fast, smallest viable classifier. <150ms.',
    sizeBytes: BigInt(1_073_741_824),
    parameterCount: '1.7B',
    runtime: 'OLLAMA',
    ollamaName: 'smollm2:1.7b',
    isRecommended: false,
    capabilities: ['ultra_fast', 'classification', 'lightweight'],
  },
  {
    name: 'gemma3',
    tag: '4b',
    displayName: 'Gemma 3 4B',
    category: 'ROUTING',
    description: 'Google quality, reliable structured output. <350ms.',
    sizeBytes: BigInt(3_543_348_019),
    parameterCount: '4B',
    runtime: 'OLLAMA',
    ollamaName: 'gemma3:4b',
    isRecommended: false,
    capabilities: ['structured_output', 'classification', 'reliable'],
  },
  {
    name: 'mistral-small3',
    tag: '7b-routing',
    displayName: 'Mistral Small 3 7B',
    category: 'ROUTING',
    description: 'Highest accuracy router but slower. <400ms.',
    sizeBytes: BigInt(4_831_838_208),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'mistral-small3:7b',
    isRecommended: false,
    capabilities: ['high_accuracy', 'classification', 'structured_output'],
  },

  // ─── REASONING (5 models) ───────────────────────────────────────────
  {
    name: 'deepseek-r1',
    tag: '32b',
    displayName: 'DeepSeek R1 32B',
    category: 'REASONING',
    description: 'Near-perfect math (97.3% MATH-500). Explicit chain-of-thought.',
    sizeBytes: BigInt(21_474_836_480),
    parameterCount: '32B',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-r1:32b',
    isRecommended: true,
    capabilities: ['chain_of_thought', 'math', 'logic', 'analysis', 'problem_solving'],
  },
  {
    name: 'deepseek-r1',
    tag: '14b',
    displayName: 'DeepSeek R1 14B',
    category: 'REASONING',
    description: 'Best reasoning under 16GB VRAM. 93.2% MATH-500.',
    sizeBytes: BigInt(9_663_676_416),
    parameterCount: '14B',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-r1:14b',
    isRecommended: false,
    capabilities: ['chain_of_thought', 'math', 'logic', 'analysis'],
  },
  {
    name: 'deepseek-r1',
    tag: '7b',
    displayName: 'DeepSeek R1 7B',
    category: 'REASONING',
    description: 'Chain-of-thought on 8GB RAM. 85%+ MATH-500.',
    sizeBytes: BigInt(5_046_586_573),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-r1:7b',
    isRecommended: false,
    capabilities: ['chain_of_thought', 'math', 'logic'],
  },
  {
    name: 'qwq',
    tag: '32b',
    displayName: 'QwQ 32B (Qwen)',
    category: 'REASONING',
    description: 'Outperforms instruction-tuned models on logic and planning. 90%+ MATH.',
    sizeBytes: BigInt(21_474_836_480),
    parameterCount: '32B',
    runtime: 'OLLAMA',
    ollamaName: 'qwq:32b',
    isRecommended: false,
    capabilities: ['logic', 'planning', 'multi_step_reasoning', 'math'],
  },
  {
    name: 'phi4',
    tag: '14b-reasoning',
    displayName: 'Phi-4 14B (Reasoning)',
    category: 'REASONING',
    description: 'Beats GPT-4o on MATH & GPQA per-parameter. 80.4% MATH-500.',
    sizeBytes: BigInt(9_663_676_416),
    parameterCount: '14B',
    runtime: 'OLLAMA',
    ollamaName: 'phi4:14b',
    isRecommended: false,
    capabilities: ['math', 'science', 'analytical_reasoning', 'stem'],
  },

  // ─── THINKING & SEARCH (5 models) ───────────────────────────────────
  {
    name: 'glm-4.7-thinking',
    tag: 'latest',
    displayName: 'GLM-4.7 Thinking',
    category: 'THINKING',
    description: '90%+ Terminal-Bench Hard. Best self-hostable agentic model.',
    sizeBytes: BigInt(5_046_586_573),
    parameterCount: '4.7B',
    runtime: 'OLLAMA',
    ollamaName: 'glm4:latest',
    isRecommended: true,
    capabilities: ['agentic', 'tool_use', 'web_search', 'research', 'thinking'],
  },
  {
    name: 'deepseek-v3.2',
    tag: 'latest',
    displayName: 'DeepSeek V3.2',
    category: 'THINKING',
    description: 'Integrated thinking + tool-use. First model with think-in-tool-calls.',
    sizeBytes: BigInt(39_728_447_488),
    parameterCount: '671B (37B active)',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-v3.2',
    isRecommended: false,
    capabilities: ['thinking', 'tool_use', 'agentic', 'research', 'deep_analysis'],
  },
  {
    name: 'mimo-v2-flash',
    tag: 'latest',
    displayName: 'MiMo-V2-Flash',
    category: 'THINKING',
    description: 'Ultra-fast reasoning + agentic. 256K context window.',
    sizeBytes: BigInt(16_106_127_360),
    parameterCount: '309B (15B active)',
    runtime: 'OLLAMA',
    ollamaName: 'mimo-v2-flash',
    isRecommended: false,
    capabilities: ['ultra_fast', 'agentic', 'long_context', 'thinking'],
  },
  {
    name: 'qwen3.5',
    tag: '27b',
    displayName: 'Qwen 3.5 27B',
    category: 'THINKING',
    description: '<think> tag for forced reasoning. Strong tool-use.',
    sizeBytes: BigInt(18_253_611_008),
    parameterCount: '27B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3.5:27b',
    isRecommended: false,
    capabilities: ['thinking', 'tool_use', 'structured_reasoning', 'long_context'],
  },
  {
    name: 'llama4-maverick',
    tag: 'latest',
    displayName: 'Llama 4 Maverick',
    category: 'THINKING',
    description: 'Best general-purpose MoE. Strong function calling. 400B (17B active).',
    sizeBytes: BigInt(18_253_611_008),
    parameterCount: '400B (17B active)',
    runtime: 'OLLAMA',
    ollamaName: 'llama4-maverick',
    isRecommended: false,
    capabilities: ['general_purpose', 'function_calling', 'agentic', 'multimodal'],
  },
] as const;

async function seedCatalog(): Promise<void> {
  for (const entry of CATALOG_ENTRIES) {
    await prisma.modelCatalogEntry.upsert({
      where: {
        name_tag_runtime: {
          name: entry.name,
          tag: entry.tag,
          runtime: entry.runtime as 'OLLAMA' | 'COMFYUI',
        },
      },
      update: {
        displayName: entry.displayName,
        category: entry.category as
          | 'CODING'
          | 'FILE_GENERATION'
          | 'IMAGE_GENERATION'
          | 'ROUTING'
          | 'REASONING'
          | 'THINKING',
        description: entry.description,
        sizeBytes: entry.sizeBytes,
        parameterCount: entry.parameterCount,
        ollamaName: entry.ollamaName,
        isRecommended: entry.isRecommended,
        capabilities: [...entry.capabilities],
      },
      create: {
        name: entry.name,
        tag: entry.tag,
        displayName: entry.displayName,
        category: entry.category as
          | 'CODING'
          | 'FILE_GENERATION'
          | 'IMAGE_GENERATION'
          | 'ROUTING'
          | 'REASONING'
          | 'THINKING',
        description: entry.description,
        sizeBytes: entry.sizeBytes,
        parameterCount: entry.parameterCount,
        runtime: entry.runtime as 'OLLAMA' | 'COMFYUI',
        ollamaName: entry.ollamaName,
        isRecommended: entry.isRecommended,
        capabilities: [...entry.capabilities],
      },
    });
  }

  const count = await prisma.modelCatalogEntry.count();
  process.stdout.write(`Seeded ${String(count)} model catalog entries\n`);
}

seedCatalog()
  .catch((error: unknown) => {
    process.stderr.write(`Catalog seed failed: ${String(error)}\n`);
    process.exit(1);
  })
  .finally(() => {
    void prisma.$disconnect();
  });
