import { PrismaClient } from '../src/generated/prisma';

const prisma = new PrismaClient();

const CATALOG_ENTRIES = [
  // ─── CODING (5 models) ──────────────────────────────────────────────
  {
    name: 'qwen2.5-coder',
    tag: '32b',
    displayName: 'Qwen 2.5 Coder 32B',
    category: 'CODING',
    description: 'Best local coding model, 300+ languages. Matches GPT-4o on HumanEval (73.7).',
    sizeBytes: BigInt(21_474_836_480),
    parameterCount: '32B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen2.5-coder:32b',
    isRecommended: true,
    capabilities: [
      'code_generation',
      'code_review',
      'debugging',
      'refactoring',
      'multilingual_code',
    ],
  },
  {
    name: 'qwen2.5-coder',
    tag: '14b',
    displayName: 'Qwen 2.5 Coder 14B',
    category: 'CODING',
    description: 'Sweet spot for quality vs hardware. Top-rated coding model under 20B params.',
    sizeBytes: BigInt(9_663_676_416),
    parameterCount: '14B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen2.5-coder:14b',
    isRecommended: false,
    capabilities: ['code_generation', 'code_review', 'debugging', 'refactoring'],
  },
  {
    name: 'qwen2.5-coder',
    tag: '7b',
    displayName: 'Qwen 2.5 Coder 7B',
    category: 'CODING',
    description: 'Best coding model for 8-12GB VRAM. HumanEval 76.0 in 7B class.',
    sizeBytes: BigInt(5_046_586_573),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen2.5-coder:7b',
    isRecommended: false,
    capabilities: ['code_generation', 'debugging', 'code_completion'],
  },
  {
    name: 'deepseek-coder-v2',
    tag: '16b',
    displayName: 'DeepSeek Coder V2 16B',
    category: 'CODING',
    description: 'Specialist in debugging and code completion. LiveCodeBench 90%.',
    sizeBytes: BigInt(10_737_418_240),
    parameterCount: '16B',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-coder-v2:16b',
    isRecommended: false,
    capabilities: ['code_generation', 'debugging', 'code_completion', 'code_explanation'],
  },
  {
    name: 'starcoder2',
    tag: '7b',
    displayName: 'StarCoder2 7B',
    category: 'CODING',
    description: 'Lightweight model good for autocomplete and code completion.',
    sizeBytes: BigInt(4_831_838_208),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'starcoder2:7b',
    isRecommended: false,
    capabilities: ['code_completion', 'code_generation'],
  },

  // ─── FILE GENERATION (5 models) ─────────────────────────────────────
  {
    name: 'qwen3',
    tag: '7b',
    displayName: 'Qwen 3 7B',
    category: 'FILE_GENERATION',
    description: 'Best instruction following for structured output (markdown, JSON, CSV).',
    sizeBytes: BigInt(5_046_586_573),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3:7b',
    isRecommended: true,
    capabilities: ['structured_output', 'markdown', 'json', 'csv', 'instruction_following'],
  },
  {
    name: 'llama3.3',
    tag: '8b',
    displayName: 'Llama 3.3 8B',
    category: 'FILE_GENERATION',
    description: 'Best all-around content writer with clean formatting.',
    sizeBytes: BigInt(5_368_709_120),
    parameterCount: '8B',
    runtime: 'OLLAMA',
    ollamaName: 'llama3.3:8b',
    isRecommended: false,
    capabilities: ['content_writing', 'formatting', 'structured_output'],
  },
  {
    name: 'mistral-small3',
    tag: '7b',
    displayName: 'Mistral Small 3 7B',
    category: 'FILE_GENERATION',
    description: 'Fastest throughput — ideal for bulk file generation.',
    sizeBytes: BigInt(4_831_838_208),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'mistral-small3:7b',
    isRecommended: false,
    capabilities: ['fast_generation', 'structured_output', 'content_writing'],
  },
  {
    name: 'phi4',
    tag: '14b',
    displayName: 'Phi-4 14B',
    category: 'FILE_GENERATION',
    description: 'Best analytical writing (reports, technical docs). Beats GPT-4o on MATH.',
    sizeBytes: BigInt(9_663_676_416),
    parameterCount: '14B',
    runtime: 'OLLAMA',
    ollamaName: 'phi4:14b',
    isRecommended: false,
    capabilities: ['analytical_writing', 'technical_docs', 'reports', 'reasoning'],
  },
  {
    name: 'gemma3',
    tag: '9b',
    displayName: 'Gemma 3 9B',
    category: 'FILE_GENERATION',
    description: 'Strong multilingual content generation from Google.',
    sizeBytes: BigInt(6_442_450_944),
    parameterCount: '9B',
    runtime: 'OLLAMA',
    ollamaName: 'gemma3:9b',
    isRecommended: false,
    capabilities: ['multilingual', 'content_writing', 'structured_output'],
  },

  // ─── IMAGE GENERATION (5 models) ────────────────────────────────────
  {
    name: 'flux.2-dev',
    tag: 'latest',
    displayName: 'FLUX.2 Dev',
    category: 'IMAGE_GENERATION',
    description: 'Most photorealistic open-source image model in 2026. 12B parameters.',
    sizeBytes: BigInt(25_769_803_776),
    parameterCount: '12B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: true,
    capabilities: ['photorealistic', 'text_to_image', 'high_quality'],
  },
  {
    name: 'flux.1-schnell',
    tag: 'latest',
    displayName: 'FLUX.1 Schnell',
    category: 'IMAGE_GENERATION',
    description: 'Fast variant (1-4 steps), free for local use.',
    sizeBytes: BigInt(12_884_901_888),
    parameterCount: '12B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: false,
    capabilities: ['fast_generation', 'text_to_image'],
  },
  {
    name: 'sd-3.5',
    tag: 'latest',
    displayName: 'Stable Diffusion 3.5',
    category: 'IMAGE_GENERATION',
    description: 'Stability AI flagship. Great quality/speed ratio.',
    sizeBytes: BigInt(8_589_934_592),
    parameterCount: '8B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: false,
    capabilities: ['text_to_image', 'image_to_image', 'inpainting'],
  },
  {
    name: 'sdxl-lightning',
    tag: 'latest',
    displayName: 'SDXL-Lightning',
    category: 'IMAGE_GENERATION',
    description: 'Ultra-fast (1-4 step generation), real-time capable.',
    sizeBytes: BigInt(8_589_934_592),
    parameterCount: '6.6B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: false,
    capabilities: ['ultra_fast', 'text_to_image', 'realtime'],
  },
  {
    name: 'z-image-turbo',
    tag: 'latest',
    displayName: 'Z-Image-Turbo',
    category: 'IMAGE_GENERATION',
    description: 'Matches larger models. Apache 2.0, bilingual text rendering.',
    sizeBytes: BigInt(6_442_450_944),
    parameterCount: '~6B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: false,
    capabilities: ['text_to_image', 'bilingual_text', 'fast_generation'],
  },

  // ─── ROUTING (5 models) ─────────────────────────────────────────────
  {
    name: 'qwen3',
    tag: '1.7b',
    displayName: 'Qwen 3 1.7B',
    category: 'ROUTING',
    description: 'Purpose-built for intent classification + structured JSON. <200ms routing.',
    sizeBytes: BigInt(1_288_490_189),
    parameterCount: '1.7B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3:1.7b',
    isRecommended: true,
    capabilities: ['intent_classification', 'structured_output', 'json', 'ultra_fast'],
  },
  {
    name: 'phi4-mini',
    tag: '3.8b',
    displayName: 'Phi-4-mini 3.8B',
    category: 'ROUTING',
    description: 'Best reasoning per GB — accurate routing on tiny hardware. <300ms.',
    sizeBytes: BigInt(2_469_606_195),
    parameterCount: '3.8B',
    runtime: 'OLLAMA',
    ollamaName: 'phi4-mini',
    isRecommended: false,
    capabilities: ['intent_classification', 'reasoning', 'structured_output'],
  },
  {
    name: 'smollm2',
    tag: '1.7b',
    displayName: 'SmolLM2 1.7B',
    category: 'ROUTING',
    description: 'Ultra-fast, smallest viable classifier. <150ms.',
    sizeBytes: BigInt(1_073_741_824),
    parameterCount: '1.7B',
    runtime: 'OLLAMA',
    ollamaName: 'smollm2:1.7b',
    isRecommended: false,
    capabilities: ['ultra_fast', 'classification', 'lightweight'],
  },
  {
    name: 'gemma3',
    tag: '4b',
    displayName: 'Gemma 3 4B',
    category: 'ROUTING',
    description: 'Google quality, reliable structured output. <350ms.',
    sizeBytes: BigInt(3_543_348_019),
    parameterCount: '4B',
    runtime: 'OLLAMA',
    ollamaName: 'gemma3:4b',
    isRecommended: false,
    capabilities: ['structured_output', 'classification', 'reliable'],
  },
  {
    name: 'mistral-small3',
    tag: '7b-routing',
    displayName: 'Mistral Small 3 7B',
    category: 'ROUTING',
    description: 'Highest accuracy router but slower. <400ms.',
    sizeBytes: BigInt(4_831_838_208),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'mistral-small3:7b',
    isRecommended: false,
    capabilities: ['high_accuracy', 'classification', 'structured_output'],
  },

  // ─── REASONING (5 models) ───────────────────────────────────────────
  {
    name: 'deepseek-r1',
    tag: '32b',
    displayName: 'DeepSeek R1 32B',
    category: 'REASONING',
    description: 'Near-perfect math (97.3% MATH-500). Explicit chain-of-thought.',
    sizeBytes: BigInt(21_474_836_480),
    parameterCount: '32B',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-r1:32b',
    isRecommended: true,
    capabilities: ['chain_of_thought', 'math', 'logic', 'analysis', 'problem_solving'],
  },
  {
    name: 'deepseek-r1',
    tag: '14b',
    displayName: 'DeepSeek R1 14B',
    category: 'REASONING',
    description: 'Best reasoning under 16GB VRAM. 93.2% MATH-500.',
    sizeBytes: BigInt(9_663_676_416),
    parameterCount: '14B',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-r1:14b',
    isRecommended: false,
    capabilities: ['chain_of_thought', 'math', 'logic', 'analysis'],
  },
  {
    name: 'deepseek-r1',
    tag: '7b',
    displayName: 'DeepSeek R1 7B',
    category: 'REASONING',
    description: 'Chain-of-thought on 8GB RAM. 85%+ MATH-500.',
    sizeBytes: BigInt(5_046_586_573),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-r1:7b',
    isRecommended: false,
    capabilities: ['chain_of_thought', 'math', 'logic'],
  },
  {
    name: 'qwq',
    tag: '32b',
    displayName: 'QwQ 32B (Qwen)',
    category: 'REASONING',
    description: 'Outperforms instruction-tuned models on logic and planning. 90%+ MATH.',
    sizeBytes: BigInt(21_474_836_480),
    parameterCount: '32B',
    runtime: 'OLLAMA',
    ollamaName: 'qwq:32b',
    isRecommended: false,
    capabilities: ['logic', 'planning', 'multi_step_reasoning', 'math'],
  },
  {
    name: 'phi4',
    tag: '14b-reasoning',
    displayName: 'Phi-4 14B (Reasoning)',
    category: 'REASONING',
    description: 'Beats GPT-4o on MATH & GPQA per-parameter. 80.4% MATH-500.',
    sizeBytes: BigInt(9_663_676_416),
    parameterCount: '14B',
    runtime: 'OLLAMA',
    ollamaName: 'phi4:14b',
    isRecommended: false,
    capabilities: ['math', 'science', 'analytical_reasoning', 'stem'],
  },

  // ─── THINKING & SEARCH (5 models) ───────────────────────────────────
  {
    name: 'glm-4.7-thinking',
    tag: 'latest',
    displayName: 'GLM-4.7 Thinking',
    category: 'THINKING',
    description: '90%+ Terminal-Bench Hard. Best self-hostable agentic model.',
    sizeBytes: BigInt(5_046_586_573),
    parameterCount: '4.7B',
    runtime: 'OLLAMA',
    ollamaName: 'glm4:latest',
    isRecommended: true,
    capabilities: ['agentic', 'tool_use', 'web_search', 'research', 'thinking'],
  },
  {
    name: 'deepseek-v3.2',
    tag: 'latest',
    displayName: 'DeepSeek V3.2',
    category: 'THINKING',
    description: 'Integrated thinking + tool-use. First model with think-in-tool-calls.',
    sizeBytes: BigInt(39_728_447_488),
    parameterCount: '671B (37B active)',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-v3.2',
    isRecommended: false,
    capabilities: ['thinking', 'tool_use', 'agentic', 'research', 'deep_analysis'],
  },
  {
    name: 'mimo-v2-flash',
    tag: 'latest',
    displayName: 'MiMo-V2-Flash',
    category: 'THINKING',
    description: 'Ultra-fast reasoning + agentic. 256K context window.',
    sizeBytes: BigInt(16_106_127_360),
    parameterCount: '309B (15B active)',
    runtime: 'OLLAMA',
    ollamaName: 'mimo-v2-flash',
    isRecommended: false,
    capabilities: ['ultra_fast', 'agentic', 'long_context', 'thinking'],
  },
  {
    name: 'qwen3.5',
    tag: '27b',
    displayName: 'Qwen 3.5 27B',
    category: 'THINKING',
    description: '<think> tag for forced reasoning. Strong tool-use.',
    sizeBytes: BigInt(18_253_611_008),
    parameterCount: '27B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3.5:27b',
    isRecommended: false,
    capabilities: ['thinking', 'tool_use', 'structured_reasoning', 'long_context'],
  },
  {
    name: 'llama4-maverick',
    tag: 'latest',
    displayName: 'Llama 4 Maverick',
    category: 'THINKING',
    description: 'Best general-purpose MoE. Strong function calling. 400B (17B active).',
    sizeBytes: BigInt(18_253_611_008),
    parameterCount: '400B (17B active)',
    runtime: 'OLLAMA',
    ollamaName: 'llama4-maverick',
    isRecommended: false,
    capabilities: ['general_purpose', 'function_calling', 'agentic', 'multimodal'],
  },
  // ─── CODING (10 more models) ──────────────────────────────────────
  {
    name: 'codellama',
    tag: '34b',
    displayName: 'CodeLlama 34B',
    category: 'CODING',
    description: 'Meta large code model with infilling support. Strong on HumanEval.',
    sizeBytes: BigInt(22_000_000_000),
    parameterCount: '34B',
    runtime: 'OLLAMA',
    ollamaName: 'codellama:34b',
    isRecommended: false,
    capabilities: ['code_generation', 'code_completion', 'infilling'],
  },
  {
    name: 'codellama',
    tag: '13b',
    displayName: 'CodeLlama 13B',
    category: 'CODING',
    description: 'Mid-size Meta code model, good balance of quality and speed.',
    sizeBytes: BigInt(8_500_000_000),
    parameterCount: '13B',
    runtime: 'OLLAMA',
    ollamaName: 'codellama:13b',
    isRecommended: false,
    capabilities: ['code_generation', 'code_completion'],
  },
  {
    name: 'codellama',
    tag: '7b',
    displayName: 'CodeLlama 7B',
    category: 'CODING',
    description: 'Lightweight Meta code model for fast code completion.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'codellama:7b',
    isRecommended: false,
    capabilities: ['code_generation', 'code_completion'],
  },
  {
    name: 'codegemma',
    tag: '7b',
    displayName: 'CodeGemma 7B',
    category: 'CODING',
    description: 'Google code-specialized Gemma variant with strong completion.',
    sizeBytes: BigInt(5_000_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'codegemma:7b',
    isRecommended: false,
    capabilities: ['code_generation', 'code_completion'],
  },
  {
    name: 'deepseek-coder',
    tag: '33b',
    displayName: 'DeepSeek Coder 33B',
    category: 'CODING',
    description: 'Large DeepSeek code model with broad language support.',
    sizeBytes: BigInt(21_000_000_000),
    parameterCount: '33B',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-coder:33b',
    isRecommended: false,
    capabilities: ['code_generation', 'debugging', 'code_completion'],
  },
  {
    name: 'deepseek-coder',
    tag: '6.7b',
    displayName: 'DeepSeek Coder 6.7B',
    category: 'CODING',
    description: 'Compact DeepSeek code model for resource-constrained setups.',
    sizeBytes: BigInt(4_300_000_000),
    parameterCount: '6.7B',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-coder:6.7b',
    isRecommended: false,
    capabilities: ['code_generation', 'code_completion'],
  },
  {
    name: 'magicoder',
    tag: '7b',
    displayName: 'MagiCoder 7B',
    category: 'CODING',
    description: 'OSS-instruct trained code model with strong HumanEval scores.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'magicoder:7b',
    isRecommended: false,
    capabilities: ['code_generation', 'code_completion'],
  },
  {
    name: 'wizardcoder',
    tag: '33b',
    displayName: 'WizardCoder 33B',
    category: 'CODING',
    description: 'Evol-instruct fine-tuned code model with high benchmark scores.',
    sizeBytes: BigInt(21_000_000_000),
    parameterCount: '33B',
    runtime: 'OLLAMA',
    ollamaName: 'wizardcoder:33b',
    isRecommended: false,
    capabilities: ['code_generation', 'debugging', 'code_review'],
  },
  {
    name: 'phind-codellama',
    tag: '34b',
    displayName: 'Phind CodeLlama 34B',
    category: 'CODING',
    description: 'Phind fine-tuned CodeLlama optimized for developer Q&A.',
    sizeBytes: BigInt(22_000_000_000),
    parameterCount: '34B',
    runtime: 'OLLAMA',
    ollamaName: 'phind-codellama:34b',
    isRecommended: false,
    capabilities: ['code_generation', 'debugging', 'code_explanation'],
  },
  {
    name: 'yi-coder',
    tag: '9b',
    displayName: 'Yi Coder 9B',
    category: 'CODING',
    description: 'Yi-series code specialist with strong multilingual code support.',
    sizeBytes: BigInt(6_000_000_000),
    parameterCount: '9B',
    runtime: 'OLLAMA',
    ollamaName: 'yi-coder:9b',
    isRecommended: false,
    capabilities: ['code_generation', 'code_completion', 'multilingual_code'],
  },

  // ─── GENERAL / CHAT (10 more models) ────────────────────────────────
  {
    name: 'llama3.3',
    tag: '70b',
    displayName: 'Llama 3.3 70B',
    category: 'GENERAL',
    description: 'Meta flagship 70B model with excellent instruction following.',
    sizeBytes: BigInt(45_000_000_000),
    parameterCount: '70B',
    runtime: 'OLLAMA',
    ollamaName: 'llama3.3:70b',
    isRecommended: false,
    capabilities: ['general_chat', 'instruction_following', 'reasoning'],
  },
  {
    name: 'qwen3',
    tag: '14b',
    displayName: 'Qwen 3 14B',
    category: 'GENERAL',
    description: 'Alibaba mid-size general-purpose model with strong multilingual.',
    sizeBytes: BigInt(9_500_000_000),
    parameterCount: '14B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3:14b',
    isRecommended: false,
    capabilities: ['general_chat', 'multilingual', 'instruction_following'],
  },
  {
    name: 'qwen3',
    tag: '32b',
    displayName: 'Qwen 3 32B',
    category: 'GENERAL',
    description: 'Alibaba large general-purpose model with tool-use capabilities.',
    sizeBytes: BigInt(21_000_000_000),
    parameterCount: '32B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3:32b',
    isRecommended: false,
    capabilities: ['general_chat', 'tool_use', 'reasoning', 'multilingual'],
  },
  {
    name: 'mistral',
    tag: '7b',
    displayName: 'Mistral 7B',
    category: 'GENERAL',
    description: 'Mistral AI foundational 7B model with sliding window attention.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'mistral:7b',
    isRecommended: false,
    capabilities: ['general_chat', 'fast_generation'],
  },
  {
    name: 'mixtral',
    tag: '8x7b',
    displayName: 'Mixtral 8x7B',
    category: 'GENERAL',
    description: 'Mixture-of-experts model with 46.7B total params, 12.9B active per token.',
    sizeBytes: BigInt(26_000_000_000),
    parameterCount: '46.7B (12.9B active)',
    runtime: 'OLLAMA',
    ollamaName: 'mixtral:8x7b',
    isRecommended: true,
    capabilities: ['general_chat', 'reasoning', 'multilingual', 'moe'],
  },
  {
    name: 'gemma3',
    tag: '27b',
    displayName: 'Gemma 3 27B',
    category: 'GENERAL',
    description: 'Google large Gemma model with vision and multilingual support.',
    sizeBytes: BigInt(17_000_000_000),
    parameterCount: '27B',
    runtime: 'OLLAMA',
    ollamaName: 'gemma3:27b',
    isRecommended: false,
    capabilities: ['general_chat', 'multilingual', 'vision', 'reasoning'],
  },
  {
    name: 'command-r',
    tag: '35b',
    displayName: 'Command R 35B',
    category: 'GENERAL',
    description: 'Cohere RAG-optimized model with citation and grounding.',
    sizeBytes: BigInt(22_000_000_000),
    parameterCount: '35B',
    runtime: 'OLLAMA',
    ollamaName: 'command-r:35b',
    isRecommended: false,
    capabilities: ['general_chat', 'rag', 'citation', 'grounding'],
  },
  {
    name: 'yi',
    tag: '34b',
    displayName: 'Yi 34B',
    category: 'GENERAL',
    description: '01.AI bilingual (EN/ZH) model with strong reasoning.',
    sizeBytes: BigInt(22_000_000_000),
    parameterCount: '34B',
    runtime: 'OLLAMA',
    ollamaName: 'yi:34b',
    isRecommended: false,
    capabilities: ['general_chat', 'bilingual', 'reasoning'],
  },
  {
    name: 'solar',
    tag: '10.7b',
    displayName: 'Solar 10.7B',
    category: 'GENERAL',
    description: 'Upstage depth-upscaled model optimized for single-turn tasks.',
    sizeBytes: BigInt(7_000_000_000),
    parameterCount: '10.7B',
    runtime: 'OLLAMA',
    ollamaName: 'solar:10.7b',
    isRecommended: false,
    capabilities: ['general_chat', 'instruction_following'],
  },
  {
    name: 'internlm2',
    tag: '20b',
    displayName: 'InternLM2 20B',
    category: 'GENERAL',
    description: 'Shanghai AI Lab model with strong tool-use and long-context.',
    sizeBytes: BigInt(13_000_000_000),
    parameterCount: '20B',
    runtime: 'OLLAMA',
    ollamaName: 'internlm2:20b',
    isRecommended: false,
    capabilities: ['general_chat', 'tool_use', 'long_context'],
  },

  // ─── REASONING (5 more models) ──────────────────────────────────────
  {
    name: 'wizard-math',
    tag: '70b',
    displayName: 'WizardMath 70B',
    category: 'REASONING',
    description: 'Math-specialized model with reinforced evol-instruct training.',
    sizeBytes: BigInt(45_000_000_000),
    parameterCount: '70B',
    runtime: 'OLLAMA',
    ollamaName: 'wizard-math:70b',
    isRecommended: false,
    capabilities: ['math', 'problem_solving', 'chain_of_thought'],
  },
  {
    name: 'abel',
    tag: '13b',
    displayName: 'Abel 13B',
    category: 'REASONING',
    description: 'Math reasoning specialist trained on step-by-step solutions.',
    sizeBytes: BigInt(8_500_000_000),
    parameterCount: '13B',
    runtime: 'OLLAMA',
    ollamaName: 'abel:13b',
    isRecommended: false,
    capabilities: ['math', 'step_by_step', 'problem_solving'],
  },
  {
    name: 'mathstral',
    tag: '7b',
    displayName: 'Mathstral 7B',
    category: 'REASONING',
    description: 'Mistral math-specialized variant with strong MATH benchmark scores.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'mathstral:7b',
    isRecommended: false,
    capabilities: ['math', 'science', 'analytical_reasoning'],
  },
  {
    name: 'deepseek-r1',
    tag: '70b',
    displayName: 'DeepSeek R1 70B',
    category: 'REASONING',
    description: 'Largest DeepSeek R1 with near-perfect math and logic scores.',
    sizeBytes: BigInt(45_000_000_000),
    parameterCount: '70B',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-r1:70b',
    isRecommended: true,
    capabilities: ['chain_of_thought', 'math', 'logic', 'analysis', 'problem_solving'],
  },
  {
    name: 'qwen-qwq',
    tag: '72b',
    displayName: 'QwQ 72B',
    category: 'REASONING',
    description: 'Largest QwQ model with top-tier multi-step reasoning.',
    sizeBytes: BigInt(46_000_000_000),
    parameterCount: '72B',
    runtime: 'OLLAMA',
    ollamaName: 'qwq:72b',
    isRecommended: false,
    capabilities: ['logic', 'planning', 'multi_step_reasoning', 'math'],
  },

  // ─── FILE GENERATION (5 more models) ────────────────────────────────
  {
    name: 'llama3.3',
    tag: '70b-filegen',
    displayName: 'Llama 3.3 70B (File Gen)',
    category: 'FILE_GENERATION',
    description: 'Large Llama model for high-quality document and report generation.',
    sizeBytes: BigInt(45_000_000_000),
    parameterCount: '70B',
    runtime: 'OLLAMA',
    ollamaName: 'llama3.3:70b',
    isRecommended: false,
    capabilities: ['content_writing', 'structured_output', 'formatting'],
  },
  {
    name: 'qwen3',
    tag: '14b-filegen',
    displayName: 'Qwen 3 14B (File Gen)',
    category: 'FILE_GENERATION',
    description: 'Mid-size Qwen model for structured file output with multilingual.',
    sizeBytes: BigInt(9_500_000_000),
    parameterCount: '14B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3:14b',
    isRecommended: false,
    capabilities: ['structured_output', 'multilingual', 'content_writing'],
  },
  {
    name: 'gemma3',
    tag: '27b-filegen',
    displayName: 'Gemma 3 27B (File Gen)',
    category: 'FILE_GENERATION',
    description: 'Large Gemma model for high-quality multilingual file generation.',
    sizeBytes: BigInt(17_000_000_000),
    parameterCount: '27B',
    runtime: 'OLLAMA',
    ollamaName: 'gemma3:27b',
    isRecommended: false,
    capabilities: ['multilingual', 'content_writing', 'structured_output'],
  },
  {
    name: 'mistral-small3',
    tag: '24b',
    displayName: 'Mistral Small 3 24B',
    category: 'FILE_GENERATION',
    description: 'Mistral mid-size model optimized for fast structured generation.',
    sizeBytes: BigInt(15_000_000_000),
    parameterCount: '24B',
    runtime: 'OLLAMA',
    ollamaName: 'mistral-small3:24b',
    isRecommended: false,
    capabilities: ['fast_generation', 'structured_output', 'content_writing'],
  },
  {
    name: 'command-r-plus',
    tag: '104b',
    displayName: 'Command R+ 104B',
    category: 'FILE_GENERATION',
    description: 'Cohere largest model with RAG grounding for document generation.',
    sizeBytes: BigInt(67_000_000_000),
    parameterCount: '104B',
    runtime: 'OLLAMA',
    ollamaName: 'command-r-plus:104b',
    isRecommended: false,
    capabilities: ['content_writing', 'rag', 'structured_output', 'citation'],
  },

  // ─── THINKING (5 more models) ───────────────────────────────────────
  {
    name: 'llama4-scout',
    tag: 'latest',
    displayName: 'Llama 4 Scout',
    category: 'THINKING',
    description: 'Meta 109B MoE (17B active) with strong agentic capabilities.',
    sizeBytes: BigInt(30_000_000_000),
    parameterCount: '109B (17B active)',
    runtime: 'OLLAMA',
    ollamaName: 'llama4-scout',
    isRecommended: false,
    capabilities: ['agentic', 'tool_use', 'thinking', 'multimodal'],
  },
  {
    name: 'qwen3',
    tag: '72b',
    displayName: 'Qwen 3 72B',
    category: 'THINKING',
    description: 'Alibaba largest dense model with deep thinking capabilities.',
    sizeBytes: BigInt(46_000_000_000),
    parameterCount: '72B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3:72b',
    isRecommended: false,
    capabilities: ['thinking', 'tool_use', 'long_context', 'reasoning'],
  },
  {
    name: 'deepseek-v3',
    tag: 'latest',
    displayName: 'DeepSeek V3',
    category: 'THINKING',
    description: 'DeepSeek 685B MoE (37B active) with strong multi-step reasoning.',
    sizeBytes: BigInt(38_000_000_000),
    parameterCount: '685B (37B active)',
    runtime: 'OLLAMA',
    ollamaName: 'deepseek-v3',
    isRecommended: false,
    capabilities: ['thinking', 'agentic', 'research', 'deep_analysis'],
  },
  {
    name: 'phi4-reasoning',
    tag: '14b',
    displayName: 'Phi-4 Reasoning Plus 14B',
    category: 'THINKING',
    description: 'Microsoft reasoning-enhanced Phi-4 with extended chain-of-thought.',
    sizeBytes: BigInt(9_500_000_000),
    parameterCount: '14B',
    runtime: 'OLLAMA',
    ollamaName: 'phi4-reasoning:14b',
    isRecommended: false,
    capabilities: ['thinking', 'chain_of_thought', 'reasoning', 'math'],
  },
  {
    name: 'exaone',
    tag: '32b',
    displayName: 'EXAONE 3.5 32B',
    category: 'THINKING',
    description: 'LG AI Research model with strong agentic and research capabilities.',
    sizeBytes: BigInt(21_000_000_000),
    parameterCount: '32B',
    runtime: 'OLLAMA',
    ollamaName: 'exaone:32b',
    isRecommended: false,
    capabilities: ['thinking', 'agentic', 'research', 'long_context'],
  },

  // ─── ROUTING (5 more models) ────────────────────────────────────────
  {
    name: 'gemma3',
    tag: '1b',
    displayName: 'Gemma 3 1B',
    category: 'ROUTING',
    description: 'Ultra-lightweight Google model for fast intent classification.',
    sizeBytes: BigInt(815_000_000),
    parameterCount: '1B',
    runtime: 'OLLAMA',
    ollamaName: 'gemma3:1b',
    isRecommended: false,
    capabilities: ['ultra_fast', 'classification', 'lightweight'],
  },
  {
    name: 'qwen3',
    tag: '0.6b',
    displayName: 'Qwen 3 0.6B',
    category: 'ROUTING',
    description: 'Smallest Qwen model for minimal-latency routing decisions.',
    sizeBytes: BigInt(500_000_000),
    parameterCount: '0.6B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3:0.6b',
    isRecommended: false,
    capabilities: ['ultra_fast', 'classification', 'lightweight'],
  },
  {
    name: 'smollm2',
    tag: '360m',
    displayName: 'SmolLM2 360M',
    category: 'ROUTING',
    description: 'Hugging Face sub-400M model for ultra-low-latency classification.',
    sizeBytes: BigInt(300_000_000),
    parameterCount: '360M',
    runtime: 'OLLAMA',
    ollamaName: 'smollm2:360m',
    isRecommended: false,
    capabilities: ['ultra_fast', 'classification', 'lightweight'],
  },
  {
    name: 'tinyllama',
    tag: '1.1b',
    displayName: 'TinyLlama 1.1B',
    category: 'ROUTING',
    description: 'Compact TinyLlama for basic intent classification and routing.',
    sizeBytes: BigInt(637_000_000),
    parameterCount: '1.1B',
    runtime: 'OLLAMA',
    ollamaName: 'tinyllama:1.1b',
    isRecommended: false,
    capabilities: ['ultra_fast', 'classification', 'lightweight'],
  },
  {
    name: 'phi3',
    tag: '3.8b',
    displayName: 'Phi-3 3.8B',
    category: 'ROUTING',
    description: 'Microsoft Phi-3 with good reasoning for accurate routing.',
    sizeBytes: BigInt(2_300_000_000),
    parameterCount: '3.8B',
    runtime: 'OLLAMA',
    ollamaName: 'phi3:3.8b',
    isRecommended: false,
    capabilities: ['classification', 'reasoning', 'structured_output'],
  },

  // ─── MULTILINGUAL (3 models, GENERAL category) ──────────────────────
  {
    name: 'aya',
    tag: '35b',
    displayName: 'Aya 35B',
    category: 'GENERAL',
    description: 'Cohere multilingual model supporting 101 languages.',
    sizeBytes: BigInt(22_000_000_000),
    parameterCount: '35B',
    runtime: 'OLLAMA',
    ollamaName: 'aya:35b',
    isRecommended: false,
    capabilities: ['multilingual', '101_languages'],
  },
  {
    name: 'qwen3',
    tag: '4b',
    displayName: 'Qwen 3 4B',
    category: 'GENERAL',
    description: 'Compact Qwen model with strong Chinese and Japanese support.',
    sizeBytes: BigInt(2_800_000_000),
    parameterCount: '4B',
    runtime: 'OLLAMA',
    ollamaName: 'qwen3:4b',
    isRecommended: false,
    capabilities: ['multilingual', 'chinese', 'japanese'],
  },
  {
    name: 'sea-lion',
    tag: '7b',
    displayName: 'SEA-LION 7B',
    category: 'GENERAL',
    description: 'AI Singapore model optimized for Southeast Asian languages.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'sea-lion:7b',
    isRecommended: false,
    capabilities: ['multilingual', 'southeast_asian'],
  },

  // ─── VISION (3 models, GENERAL category) ────────────────────────────
  {
    name: 'llava',
    tag: '34b',
    displayName: 'LLaVA 34B',
    category: 'GENERAL',
    description: 'Large Language-and-Vision Assistant for image understanding.',
    sizeBytes: BigInt(22_000_000_000),
    parameterCount: '34B',
    runtime: 'OLLAMA',
    ollamaName: 'llava:34b',
    isRecommended: false,
    capabilities: ['vision', 'image_understanding', 'multimodal'],
  },
  {
    name: 'llava',
    tag: '13b',
    displayName: 'LLaVA 13B',
    category: 'GENERAL',
    description: 'Mid-size vision-language model for image analysis.',
    sizeBytes: BigInt(8_500_000_000),
    parameterCount: '13B',
    runtime: 'OLLAMA',
    ollamaName: 'llava:13b',
    isRecommended: false,
    capabilities: ['vision', 'multimodal'],
  },
  {
    name: 'moondream',
    tag: '2b',
    displayName: 'Moondream 2B',
    category: 'GENERAL',
    description: 'Ultra-lightweight vision model for fast image understanding.',
    sizeBytes: BigInt(1_500_000_000),
    parameterCount: '2B',
    runtime: 'OLLAMA',
    ollamaName: 'moondream:2b',
    isRecommended: false,
    capabilities: ['vision', 'lightweight', 'multimodal'],
  },

  // ─── MEDICAL / HEALTHCARE (5 models) ──────────────────────────────
  {
    name: 'meditron',
    tag: '70b',
    displayName: 'Meditron 70B',
    category: 'GENERAL',
    description:
      'Medical domain LLM trained on clinical guidelines and PubMed. Best for healthcare professionals.',
    sizeBytes: BigInt(45_000_000_000),
    parameterCount: '70B',
    runtime: 'OLLAMA',
    ollamaName: 'meditron:70b',
    isRecommended: false,
    capabilities: ['medical', 'clinical', 'diagnosis', 'drug_interaction'],
  },
  {
    name: 'meditron',
    tag: '7b',
    displayName: 'Meditron 7B',
    category: 'GENERAL',
    description:
      'Compact medical domain model for clinical guidelines and basic healthcare Q&A.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'meditron:7b',
    isRecommended: false,
    capabilities: ['medical', 'clinical'],
  },
  {
    name: 'biomistral',
    tag: '7b',
    displayName: 'BioMistral 7B',
    category: 'GENERAL',
    description:
      'Biomedical NLP model for research papers, clinical notes, drug info.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'biomistral:7b',
    isRecommended: false,
    capabilities: ['biomedical', 'research', 'clinical_notes'],
  },
  {
    name: 'medllama',
    tag: '13b',
    displayName: 'MedLlama 13B',
    category: 'GENERAL',
    description:
      'Medical QA model for patient queries and clinical decision support.',
    sizeBytes: BigInt(8_500_000_000),
    parameterCount: '13B',
    runtime: 'OLLAMA',
    ollamaName: 'medllama:13b',
    isRecommended: false,
    capabilities: ['medical_qa', 'patient_education'],
  },
  {
    name: 'clinical-camel',
    tag: '70b',
    displayName: 'Clinical Camel 70B',
    category: 'GENERAL',
    description:
      'Clinical reasoning model trained on medical case studies.',
    sizeBytes: BigInt(45_000_000_000),
    parameterCount: '70B',
    runtime: 'OLLAMA',
    ollamaName: 'clinical-camel:70b',
    isRecommended: false,
    capabilities: ['clinical_reasoning', 'case_study'],
  },

  // ─── LEGAL (3 models) ─────────────────────────────────────────────
  {
    name: 'saul',
    tag: '7b',
    displayName: 'SaulLM 7B',
    category: 'GENERAL',
    description:
      'Legal domain model for contract analysis, case law, regulatory compliance.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'saul:7b',
    isRecommended: false,
    capabilities: ['legal', 'contract_analysis', 'compliance'],
  },
  {
    name: 'legallama',
    tag: '13b',
    displayName: 'LegalLlama 13B',
    category: 'GENERAL',
    description: 'Legal research and document analysis model.',
    sizeBytes: BigInt(8_500_000_000),
    parameterCount: '13B',
    runtime: 'OLLAMA',
    ollamaName: 'legallama:13b',
    isRecommended: false,
    capabilities: ['legal_research', 'document_review'],
  },
  {
    name: 'lawgpt',
    tag: '7b',
    displayName: 'LawGPT 7B',
    category: 'GENERAL',
    description:
      'Legal Q&A model for common legal questions and explanations.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'lawgpt:7b',
    isRecommended: false,
    capabilities: ['legal_qa', 'statute_lookup'],
  },

  // ─── FINANCE (3 models) ───────────────────────────────────────────
  {
    name: 'financellama',
    tag: '13b',
    displayName: 'FinanceLlama 13B',
    category: 'GENERAL',
    description:
      'Financial analysis, valuation, and market research model.',
    sizeBytes: BigInt(8_500_000_000),
    parameterCount: '13B',
    runtime: 'OLLAMA',
    ollamaName: 'financellama:13b',
    isRecommended: false,
    capabilities: ['financial_analysis', 'valuation', 'market_research'],
  },
  {
    name: 'finma',
    tag: '7b',
    displayName: 'FinMA 7B',
    category: 'GENERAL',
    description:
      'Financial mathematics and quantitative analysis model.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'finma:7b',
    isRecommended: false,
    capabilities: ['quantitative', 'risk_modeling', 'derivatives'],
  },
  {
    name: 'bloomberg-gpt',
    tag: '7b',
    displayName: 'BloombergGPT-Open 7B',
    category: 'GENERAL',
    description:
      'Financial NLP model for news, earnings, and sentiment.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'bloomberg-gpt:7b',
    isRecommended: false,
    capabilities: ['financial_nlp', 'sentiment', 'earnings'],
  },

  // ─── SCIENCE / RESEARCH (4 models) ────────────────────────────────
  {
    name: 'sciglm',
    tag: '7b',
    displayName: 'SciGLM 7B',
    category: 'REASONING',
    description:
      'Scientific reasoning model for research papers and experimental design.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'sciglm:7b',
    isRecommended: false,
    capabilities: ['scientific_reasoning', 'paper_analysis', 'hypothesis'],
  },
  {
    name: 'galactica',
    tag: '30b',
    displayName: 'Galactica 30B',
    category: 'REASONING',
    description:
      'Scientific knowledge model trained on papers, textbooks, encyclopedias.',
    sizeBytes: BigInt(19_000_000_000),
    parameterCount: '30B',
    runtime: 'OLLAMA',
    ollamaName: 'galactica:30b',
    isRecommended: false,
    capabilities: ['scientific_knowledge', 'citations', 'math'],
  },
  {
    name: 'chemllm',
    tag: '7b',
    displayName: 'ChemLLM 7B',
    category: 'REASONING',
    description:
      'Chemistry-focused model for molecular analysis, reactions, synthesis.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'chemllm:7b',
    isRecommended: false,
    capabilities: ['chemistry', 'molecular', 'synthesis'],
  },
  {
    name: 'darwin',
    tag: '7b',
    displayName: 'Darwin 7B',
    category: 'REASONING',
    description: 'Biology and life sciences reasoning model.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'darwin:7b',
    isRecommended: false,
    capabilities: ['biology', 'genetics', 'ecology'],
  },

  // ─── EDUCATION (2 models) ─────────────────────────────────────────
  {
    name: 'educhat',
    tag: '13b',
    displayName: 'EduChat 13B',
    category: 'GENERAL',
    description:
      'Educational assistant for tutoring, curriculum design, and assessment.',
    sizeBytes: BigInt(8_500_000_000),
    parameterCount: '13B',
    runtime: 'OLLAMA',
    ollamaName: 'educhat:13b',
    isRecommended: false,
    capabilities: ['tutoring', 'curriculum', 'assessment', 'pedagogy'],
  },
  {
    name: 'learnlm',
    tag: '7b',
    displayName: 'LearnLM 7B',
    category: 'GENERAL',
    description:
      'Learning-focused model for explanations, study guides, quizzes.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'learnlm:7b',
    isRecommended: false,
    capabilities: ['learning', 'explanation', 'quiz_generation'],
  },

  // ─── BUSINESS / ANALYTICS (4 models) ──────────────────────────────
  {
    name: 'tableGPT',
    tag: '7b',
    displayName: 'TableGPT 7B',
    category: 'FILE_GENERATION',
    description:
      'Specialized in tabular data analysis, SQL, spreadsheet formulas.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'tablegpt:7b',
    isRecommended: false,
    capabilities: ['tabular_data', 'sql', 'spreadsheet', 'csv'],
  },
  {
    name: 'sqlcoder',
    tag: '15b',
    displayName: 'SQLCoder 15B',
    category: 'CODING',
    description:
      'SQL-specialized model. Outperforms GPT-4 on SQL generation.',
    sizeBytes: BigInt(10_000_000_000),
    parameterCount: '15B',
    runtime: 'OLLAMA',
    ollamaName: 'sqlcoder:15b',
    isRecommended: true,
    capabilities: ['sql_generation', 'database', 'query_optimization'],
  },
  {
    name: 'markitdown',
    tag: '7b',
    displayName: 'MarkItDown 7B',
    category: 'FILE_GENERATION',
    description:
      'Document-to-markdown conversion and structured content generation.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'markitdown:7b',
    isRecommended: false,
    capabilities: ['markdown', 'document_conversion', 'structured_output'],
  },
  {
    name: 'nous-hermes',
    tag: '13b',
    displayName: 'Nous Hermes 13B',
    category: 'GENERAL',
    description:
      'Business-focused model for strategy, analysis, and consulting.',
    sizeBytes: BigInt(8_500_000_000),
    parameterCount: '13B',
    runtime: 'OLLAMA',
    ollamaName: 'nous-hermes:13b',
    isRecommended: false,
    capabilities: ['business_analysis', 'strategy', 'consulting'],
  },

  // ─── SECURITY / CYBER (2 models) ──────────────────────────────────
  {
    name: 'securityllm',
    tag: '13b',
    displayName: 'SecurityLLM 13B',
    category: 'CODING',
    description:
      'Cybersecurity model for vulnerability analysis, code audit, threat modeling.',
    sizeBytes: BigInt(8_500_000_000),
    parameterCount: '13B',
    runtime: 'OLLAMA',
    ollamaName: 'securityllm:13b',
    isRecommended: false,
    capabilities: ['vulnerability_analysis', 'code_audit', 'threat_modeling'],
  },
  {
    name: 'hackerllm',
    tag: '7b',
    displayName: 'HackerLLM 7B',
    category: 'CODING',
    description:
      'Offensive security model for penetration testing and CTF challenges.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'hackerllm:7b',
    isRecommended: false,
    capabilities: ['pentest', 'exploit_analysis', 'ctf'],
  },

  // ─── CREATIVE / DESIGN (3 models) ─────────────────────────────────
  {
    name: 'stable-diffusion-xl',
    tag: 'turbo',
    displayName: 'SDXL Turbo',
    category: 'IMAGE_GENERATION',
    description:
      'Ultra-fast SDXL variant. 1-step generation for real-time image creation.',
    sizeBytes: BigInt(6_500_000_000),
    parameterCount: '6.6B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: false,
    capabilities: ['ultra_fast', 'text_to_image', 'realtime', '1_step'],
  },
  {
    name: 'kandinsky',
    tag: '3.1',
    displayName: 'Kandinsky 3.1',
    category: 'IMAGE_GENERATION',
    description:
      'Multilingual image generation with strong text rendering.',
    sizeBytes: BigInt(8_000_000_000),
    parameterCount: '~8B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: false,
    capabilities: ['multilingual_image', 'text_rendering', 'artistic'],
  },
  {
    name: 'playground-v2.5',
    tag: 'latest',
    displayName: 'Playground v2.5',
    category: 'IMAGE_GENERATION',
    description:
      'High-quality image generation with excellent aesthetics.',
    sizeBytes: BigInt(7_000_000_000),
    parameterCount: '~7B',
    runtime: 'COMFYUI',
    ollamaName: null,
    isRecommended: false,
    capabilities: ['high_quality', 'aesthetic', 'photorealistic'],
  },

  // ─── TRANSLATION / MULTILINGUAL (3 models) ────────────────────────
  {
    name: 'nllb',
    tag: '3.3b',
    displayName: 'NLLB 3.3B',
    category: 'GENERAL',
    description:
      'No Language Left Behind - 200 language translation model from Meta.',
    sizeBytes: BigInt(2_200_000_000),
    parameterCount: '3.3B',
    runtime: 'OLLAMA',
    ollamaName: 'nllb:3.3b',
    isRecommended: false,
    capabilities: ['translation', '200_languages', 'low_resource'],
  },
  {
    name: 'madlad',
    tag: '7b',
    displayName: 'MADLAD-400 7B',
    category: 'GENERAL',
    description: 'Multilingual model covering 400+ languages.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'madlad:7b',
    isRecommended: false,
    capabilities: ['multilingual', '400_languages', 'translation'],
  },
  {
    name: 'tower',
    tag: '13b',
    displayName: 'Tower 13B',
    category: 'GENERAL',
    description:
      'Translation-specialized model with high BLEU scores.',
    sizeBytes: BigInt(8_500_000_000),
    parameterCount: '13B',
    runtime: 'OLLAMA',
    ollamaName: 'tower:13b',
    isRecommended: false,
    capabilities: ['translation', 'high_quality', 'european_languages'],
  },

  // ─── EMBEDDING / SEARCH (3 models) ────────────────────────────────
  {
    name: 'nomic-embed',
    tag: 'v1.5',
    displayName: 'Nomic Embed v1.5',
    category: 'GENERAL',
    description: 'Text embedding model for semantic search and RAG.',
    sizeBytes: BigInt(550_000_000),
    parameterCount: '137M',
    runtime: 'OLLAMA',
    ollamaName: 'nomic-embed-text:v1.5',
    isRecommended: false,
    capabilities: ['embedding', 'semantic_search', 'rag'],
  },
  {
    name: 'mxbai-embed',
    tag: 'large',
    displayName: 'MixedBread Embed Large',
    category: 'GENERAL',
    description:
      'High-quality embedding model for retrieval and classification.',
    sizeBytes: BigInt(1_300_000_000),
    parameterCount: '335M',
    runtime: 'OLLAMA',
    ollamaName: 'mxbai-embed-large',
    isRecommended: false,
    capabilities: ['embedding', 'retrieval', 'classification'],
  },
  {
    name: 'snowflake-arctic',
    tag: 'embed',
    displayName: 'Snowflake Arctic Embed',
    category: 'GENERAL',
    description:
      'Enterprise-grade embedding for search and analytics.',
    sizeBytes: BigInt(800_000_000),
    parameterCount: '110M',
    runtime: 'OLLAMA',
    ollamaName: 'snowflake-arctic-embed',
    isRecommended: false,
    capabilities: ['embedding', 'enterprise', 'analytics'],
  },

  // ─── DEVOPS / INFRASTRUCTURE (2 models) ───────────────────────────
  {
    name: 'gorilla',
    tag: '7b',
    displayName: 'Gorilla 7B',
    category: 'CODING',
    description:
      'API and tool-use specialist. Generates correct API calls from natural language.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'gorilla:7b',
    isRecommended: false,
    capabilities: ['api_generation', 'tool_use', 'function_calling'],
  },
  {
    name: 'k8sgpt',
    tag: '7b',
    displayName: 'K8sGPT 7B',
    category: 'CODING',
    description:
      'Kubernetes-specialized model for cluster management and troubleshooting.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'k8sgpt:7b',
    isRecommended: false,
    capabilities: ['kubernetes', 'devops', 'troubleshooting'],
  },

  // ─── AUDIO / SPEECH (2 models) ────────────────────────────────────
  {
    name: 'whisper',
    tag: 'large-v3',
    displayName: 'Whisper Large v3',
    category: 'GENERAL',
    description:
      'Speech-to-text transcription model. 99 languages, timestamps, translation.',
    sizeBytes: BigInt(3_000_000_000),
    parameterCount: '1.5B',
    runtime: 'OLLAMA',
    ollamaName: 'whisper:large-v3',
    isRecommended: false,
    capabilities: ['transcription', 'translation', '99_languages', 'timestamps'],
  },
  {
    name: 'bark',
    tag: 'latest',
    displayName: 'Bark TTS',
    category: 'GENERAL',
    description:
      'Text-to-speech model with voice cloning and emotion control.',
    sizeBytes: BigInt(5_000_000_000),
    parameterCount: '~5B',
    runtime: 'OLLAMA',
    ollamaName: 'bark',
    isRecommended: false,
    capabilities: ['text_to_speech', 'voice_cloning', 'emotion', 'music'],
  },

  // ─── SPECIALIZED REASONING (3 models) ─────────────────────────────
  {
    name: 'llemma',
    tag: '34b',
    displayName: 'Llemma 34B',
    category: 'REASONING',
    description:
      'Mathematics-specialized LLM. Formal proofs, LaTeX, theorem proving.',
    sizeBytes: BigInt(22_000_000_000),
    parameterCount: '34B',
    runtime: 'OLLAMA',
    ollamaName: 'llemma:34b',
    isRecommended: false,
    capabilities: ['mathematics', 'formal_proof', 'latex', 'theorem'],
  },
  {
    name: 'llemma',
    tag: '7b',
    displayName: 'Llemma 7B',
    category: 'REASONING',
    description:
      'Compact mathematics model for formal proofs and LaTeX generation.',
    sizeBytes: BigInt(4_500_000_000),
    parameterCount: '7B',
    runtime: 'OLLAMA',
    ollamaName: 'llemma:7b',
    isRecommended: false,
    capabilities: ['mathematics', 'formal_proof'],
  },
  {
    name: 'metamath',
    tag: '13b',
    displayName: 'MetaMath 13B',
    category: 'REASONING',
    description:
      'Math reasoning model trained on augmented mathematical datasets.',
    sizeBytes: BigInt(8_500_000_000),
    parameterCount: '13B',
    runtime: 'OLLAMA',
    ollamaName: 'metamath:13b',
    isRecommended: false,
    capabilities: ['math_reasoning', 'word_problems', 'algebra'],
  },
] as const;

type ModelCategory =
  | 'CODING'
  | 'FILE_GENERATION'
  | 'IMAGE_GENERATION'
  | 'ROUTING'
  | 'REASONING'
  | 'THINKING'
  | 'GENERAL';

async function seedCatalog(): Promise<void> {
  for (const entry of CATALOG_ENTRIES) {
    await prisma.modelCatalogEntry.upsert({
      where: {
        name_tag_runtime: {
          name: entry.name,
          tag: entry.tag,
          runtime: entry.runtime as 'OLLAMA' | 'COMFYUI',
        },
      },
      update: {
        displayName: entry.displayName,
        category: entry.category as ModelCategory,
        description: entry.description,
        sizeBytes: entry.sizeBytes,
        parameterCount: entry.parameterCount,
        ollamaName: entry.ollamaName,
        isRecommended: entry.isRecommended,
        capabilities: [...entry.capabilities],
      },
      create: {
        name: entry.name,
        tag: entry.tag,
        displayName: entry.displayName,
        category: entry.category as ModelCategory,
        description: entry.description,
        sizeBytes: entry.sizeBytes,
        parameterCount: entry.parameterCount,
        runtime: entry.runtime as 'OLLAMA' | 'COMFYUI',
        ollamaName: entry.ollamaName,
        isRecommended: entry.isRecommended,
        capabilities: [...entry.capabilities],
      },
    });
  }

  const count = await prisma.modelCatalogEntry.count();
  process.stdout.write(`Seeded ${String(count)} model catalog entries\n`);
}

seedCatalog()
  .catch((error: unknown) => {
    process.stderr.write(`Catalog seed failed: ${String(error)}\n`);
    process.exit(1);
  })
  .finally(() => {
    void prisma.$disconnect();
  });
