export const DEFAULT_AUTO_APPROVE_THRESHOLD = 0.85;
export const DEFAULT_SEMANTIC_BUDGET_MEMORY = 5;
export const DEFAULT_SEMANTIC_BUDGET_CONTEXT = 12;
export const MEMORY_RETRIEVAL_MAX = 50;
export const CONTEXT_RETRIEVAL_MAX = 100;
