// Renders .ai/packs/*.md from the canonical task-pack data (single source of
// truth shared with the context resolver's classifier). Generated, not
// hand-edited — so a pack and its classifier can never drift apart.
import { TASK_PACKS } from './classify-task.mjs';

export function renderPacks() {
  const files = {};
  for (const p of TASK_PACKS) {
    files[`.ai/packs/${p.pack}.md`] = renderPack(p);
  }
  files['.ai/packs/README.md'] = renderIndex(TASK_PACKS);
  return files;
}

function renderPack(p) {
  return `<!-- GENERATED by tools/knowledge/build.mjs — DO NOT EDIT. -->
# Task pack: ${p.pack}

${p.summary}.

**Trigger keywords:** ${p.keywords.join(', ')}

## Reviewers to involve
${p.reviewers.map((r) => `- \`agents/${r}.md\``).join('\n')}

## Validation lane
${p.validation.map((v) => `- \`${v}\``).join('\n')}

## Known pitfalls
${p.pitfalls.map((x) => `- ${x}`).join('\n')}

## How to use
\`\`\`
npm run knowledge:context -- --task="<your task>"
\`\`\`
Then read \`.ai/local/current-context.md\`, follow the governing rules it cites,
and apply the pitfalls above.
`;
}

function renderIndex(packs) {
  return `<!-- GENERATED by tools/knowledge/build.mjs — DO NOT EDIT. -->
# Task packs

Curated bundles that map a kind of task to its reviewers, validation lane, and
pitfalls. The context resolver (\`npm run knowledge:context\`) classifies your
task into one of these automatically.

${packs.map((p) => `- **${p.pack}** — ${p.summary}`).join('\n')}
`;
}
