// Mirrors the `code` field on backend `BusinessException` payloads so the
// frontend can map machine-readable error codes to UX (e.g. plan upgrade CTA
// for PLAN_FEATURE_DISABLED, permission CTA for INSUFFICIENT_PERMISSIONS).
// Keep in lock-step with apps/claw-*-service/src/common/errors/*.exception.ts.
export enum ApiErrorCode {
  PLAN_FEATURE_DISABLED = 'PLAN_FEATURE_DISABLED',
  PLAN_TRIAL_EXPIRED = 'PLAN_TRIAL_EXPIRED',
  QUOTA_DAILY_EXCEEDED = 'QUOTA_DAILY_EXCEEDED',
  QUOTA_WEEKLY_EXCEEDED = 'QUOTA_WEEKLY_EXCEEDED',
  QUOTA_MONTHLY_EXCEEDED = 'QUOTA_MONTHLY_EXCEEDED',
  PLAN_DAILY_CHAT_LIMIT_EXCEEDED = 'PLAN_DAILY_CHAT_LIMIT_EXCEEDED',
  PLAN_DAILY_MESSAGE_LIMIT_EXCEEDED = 'PLAN_DAILY_MESSAGE_LIMIT_EXCEEDED',
  PLAN_WORKSPACE_CONNECTION_LIMIT_EXCEEDED = 'PLAN_WORKSPACE_CONNECTION_LIMIT_EXCEEDED',
  PLAN_CONTEXT_PACK_LIMIT_EXCEEDED = 'PLAN_CONTEXT_PACK_LIMIT_EXCEEDED',
  PLAN_MEMORY_ITEM_LIMIT_EXCEEDED = 'PLAN_MEMORY_ITEM_LIMIT_EXCEEDED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
}
