export enum CapabilityBlastRadius {
  NONE = 'NONE',
  SINGLE_RESOURCE = 'SINGLE_RESOURCE',
  MANY_RESOURCES = 'MANY_RESOURCES',
  USER_SCOPE = 'USER_SCOPE',
  SYSTEM_SCOPE = 'SYSTEM_SCOPE',
  EXTERNAL = 'EXTERNAL',
}
