export enum CapabilityInvocationStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  AUTO_APPROVED = 'AUTO_APPROVED',
  APPROVED = 'APPROVED',
  EXECUTING = 'EXECUTING',
  EXECUTED = 'EXECUTED',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  ROLLED_BACK = 'ROLLED_BACK',
  ROLLBACK_FAILED = 'ROLLBACK_FAILED',
  DENIED = 'DENIED',
}
