export enum FileGenerationStatus {
  QUEUED = 'QUEUED',
  STARTING = 'STARTING',
  GENERATING_CONTENT = 'GENERATING_CONTENT',
  CONVERTING = 'CONVERTING',
  FINALIZING = 'FINALIZING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  TIMED_OUT = 'TIMED_OUT',
  CANCELLED = 'CANCELLED',
}
