export enum ImageGenerationStatus {
  QUEUED = 'QUEUED',
  STARTING = 'STARTING',
  GENERATING = 'GENERATING',
  FINALIZING = 'FINALIZING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  TIMED_OUT = 'TIMED_OUT',
  CANCELLED = 'CANCELLED',
}
