export enum LaunchPublicPageSlug {
  HOME = 'home',
  ABOUT = 'about',
  ACCEPTABLE_USE = 'acceptable-use',
  ARCHITECTURE = 'architecture',
  CONTACT = 'contact',
  COOKIES = 'cookies',
  FAQ = 'faq',
  FEATURES = 'features',
  HOW_IT_WORKS = 'how-it-works',
  LOCAL_FIRST_AI = 'local-first-ai',
  PRICING = 'pricing',
  PRIVACY = 'privacy',
  SECURITY_AND_PRIVACY = 'security-and-privacy',
  SUPPORTED_MODELS = 'supported-models',
  TERMS = 'terms',
  USE_CASES = 'use-cases',
}
