export enum ModelCapability {
  TEXT = 'TEXT',
  CODE = 'CODE',
  IMAGE_INPUT = 'IMAGE_INPUT',
  IMAGE_OUTPUT = 'IMAGE_OUTPUT',
  AUDIO_INPUT = 'AUDIO_INPUT',
  VIDEO_INPUT = 'VIDEO_INPUT',
  PDF_INPUT = 'PDF_INPUT',
  WEB_SEARCH = 'WEB_SEARCH',
  TOOL_CALLING = 'TOOL_CALLING',
  STRUCTURED_OUTPUT = 'STRUCTURED_OUTPUT',
  OCR = 'OCR',
  REASONING = 'REASONING',
}
