export enum PlanModelAccessMode {
  ALLOW_ALL = 'ALLOW_ALL',
  DENY_ALL = 'DENY_ALL',
  ALLOW_LIST = 'ALLOW_LIST',
  ALLOW_COST_CLASSES = 'ALLOW_COST_CLASSES',
  LEGACY_UNRESTRICTED = 'LEGACY_UNRESTRICTED',
}
