export enum RouteVisibility {
  STATIC_PUBLIC = 'STATIC_PUBLIC',
  DYNAMIC_PUBLIC_CANDIDATE = 'DYNAMIC_PUBLIC_CANDIDATE',
  PUBLIC_MACHINE_ROUTE = 'PUBLIC_MACHINE_ROUTE',
  PRIVATE = 'PRIVATE',
  UNKNOWN = 'UNKNOWN',
}
