export enum RouterModelLifecycle {
  ACTIVE = 'ACTIVE',
  PREVIEW = 'PREVIEW',
  DEPRECATED = 'DEPRECATED',
  DISABLED = 'DISABLED',
  REMOVED = 'REMOVED',
}

export enum CostConfidence {
  EXACT = 'EXACT',
  ESTIMATED = 'ESTIMATED',
  UNKNOWN = 'UNKNOWN',
}

export enum CostClass {
  FREE = 'FREE',
  CHEAP = 'CHEAP',
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
  ULTRA = 'ULTRA',
}

export enum LatencyClass {
  REALTIME = 'REALTIME',
  FAST = 'FAST',
  MEDIUM = 'MEDIUM',
  SLOW = 'SLOW',
  HEAVY = 'HEAVY',
}

export enum QualityTier {
  S = 'S',
  A = 'A',
  B = 'B',
  C = 'C',
  D = 'D',
}

export enum PrivacyClass {
  PUBLIC_OK = 'PUBLIC_OK',
  CLOUD_PERMITTED = 'CLOUD_PERMITTED',
  LOCAL_PREFERRED = 'LOCAL_PREFERRED',
  LOCAL_ONLY = 'LOCAL_ONLY',
}

export enum ModalityKind {
  TEXT = 'TEXT',
  CODE = 'CODE',
  IMAGE_INPUT = 'IMAGE_INPUT',
  IMAGE_OUTPUT = 'IMAGE_OUTPUT',
  AUDIO_INPUT = 'AUDIO_INPUT',
  AUDIO_OUTPUT = 'AUDIO_OUTPUT',
  VIDEO_INPUT = 'VIDEO_INPUT',
  VIDEO_OUTPUT = 'VIDEO_OUTPUT',
  FILE_INPUT = 'FILE_INPUT',
  PDF_INPUT = 'PDF_INPUT',
  SPREADSHEET_INPUT = 'SPREADSHEET_INPUT',
  WEB_INPUT = 'WEB_INPUT',
  YOUTUBE_INPUT = 'YOUTUBE_INPUT',
  STRUCTURED_OUTPUT = 'STRUCTURED_OUTPUT',
  TOOL_CALLING = 'TOOL_CALLING',
  STREAMING = 'STREAMING',
  EMBEDDING = 'EMBEDDING',
}

export enum DomainTag {
  GENERAL = 'GENERAL',
  CODING = 'CODING',
  MEDICAL = 'MEDICAL',
  LEGAL = 'LEGAL',
  FINANCE = 'FINANCE',
  MARKETING = 'MARKETING',
  EDUCATION = 'EDUCATION',
  CREATIVE_WRITING = 'CREATIVE_WRITING',
  RESEARCH = 'RESEARCH',
  MECHANICAL = 'MECHANICAL',
  AUTOMOTIVE = 'AUTOMOTIVE',
  BIOLOGY = 'BIOLOGY',
  CHEMISTRY = 'CHEMISTRY',
  PHYSICS = 'PHYSICS',
  MULTIMEDIA = 'MULTIMEDIA',
  BUSINESS = 'BUSINESS',
  HR = 'HR',
  SALES = 'SALES',
  TRANSLATION = 'TRANSLATION',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  LITERATURE = 'LITERATURE',
}
