export enum RoutingMode {
  AUTO = 'AUTO',
  MANUAL_MODEL = 'MANUAL_MODEL',
  LOCAL_ONLY = 'LOCAL_ONLY',
  PRIVACY_FIRST = 'PRIVACY_FIRST',
  LOW_LATENCY = 'LOW_LATENCY',
  HIGH_REASONING = 'HIGH_REASONING',
  COST_SAVER = 'COST_SAVER',
}
