export enum SemanticAnalysisStatusEnum {
  SUCCESS = 'SUCCESS',
  INVALID_JSON_AFTER_RETRY = 'INVALID_JSON_AFTER_RETRY',
  OLLAMA_TIMEOUT = 'OLLAMA_TIMEOUT',
  OLLAMA_ERROR = 'OLLAMA_ERROR',
  SKIPPED_FLAG_DISABLED = 'SKIPPED_FLAG_DISABLED',
  SKIPPED_ROUTER_UNAVAILABLE = 'SKIPPED_ROUTER_UNAVAILABLE',
}
