export enum StructuredDataType {
  NONE = 'NONE',
  WEBSITE = 'WEBSITE',
  ORGANIZATION = 'ORGANIZATION',
  SOFTWARE_APPLICATION = 'SOFTWARE_APPLICATION',
  FAQ_PAGE = 'FAQ_PAGE',
  BREADCRUMB_LIST = 'BREADCRUMB_LIST',
  TECH_ARTICLE = 'TECH_ARTICLE',
  WEB_PAGE = 'WEB_PAGE',
}
