/** The product tours. The value is stable: it is stored as "completed" in the browser. */
export enum TourId {
  ThreadsIntro = 'threads-intro',
  ThreadCreate = 'thread-create',
  ThreadReview = 'thread-review',
  ChatIntro = 'chat-intro',
  ChatModels = 'chat-models',
  ChatResearch = 'chat-research',
  ChatContext = 'chat-context',
  ChatToThread = 'chat-to-thread',
  CompareIntro = 'compare-intro',
  ContextPacks = 'context-packs',
  ChatList = 'chat-list',
  ChatMessages = 'chat-messages',
  ChatHeader = 'chat-header',
  ChatShare = 'chat-share',
  ChatSettings = 'chat-settings',
  CompareResults = 'compare-results',
  LabsIntro = 'labs-intro',
  DashboardIntro = 'dashboard-intro',
  PlanIntro = 'plan-intro',
  BillingIntro = 'billing-intro',
  UsageIntro = 'usage-intro',
  FilesIntro = 'files-intro',
  SettingsIntro = 'settings-intro',
  MemoryIntro = 'memory-intro',
  ConnectorsIntro = 'connectors-intro',
}
