export enum WorkspaceConnectorStatus {
  CONNECTED = 'CONNECTED',
  DEGRADED = 'DEGRADED',
  DISCONNECTED = 'DISCONNECTED',
  PENDING_AUTH = 'PENDING_AUTH',
  PAUSED = 'PAUSED',
  UNKNOWN = 'UNKNOWN',
}
