export enum ReconciliationClassification {
  LOCAL_PENDING_PROVIDER_PAID = 'LOCAL_PENDING_PROVIDER_PAID',
  LOCAL_PENDING_PROVIDER_PENDING = 'LOCAL_PENDING_PROVIDER_PENDING',
  LOCAL_PENDING_PROVIDER_ACTIVE = 'LOCAL_PENDING_PROVIDER_ACTIVE',
  LOCAL_ACTIVE_PROVIDER_INACTIVE = 'LOCAL_ACTIVE_PROVIDER_INACTIVE',
  LOCAL_PAST_DUE_PROVIDER_ACTIVE = 'LOCAL_PAST_DUE_PROVIDER_ACTIVE',
  AMOUNT_MISMATCH = 'AMOUNT_MISMATCH',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  SESSION_MISMATCH = 'SESSION_MISMATCH',
  PAYMENT_REVERSED = 'PAYMENT_REVERSED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  MISSING_PROVIDER_REFERENCE = 'MISSING_PROVIDER_REFERENCE',
  UNSUPPORTED_GATEWAY = 'UNSUPPORTED_GATEWAY',
  GATEWAY_UNAVAILABLE = 'GATEWAY_UNAVAILABLE',
  GRACE_PERIOD_EXPIRED = 'GRACE_PERIOD_EXPIRED',
  SCHEDULED_DOWNGRADE_DUE = 'SCHEDULED_DOWNGRADE_DUE',
}

export enum ReconciliationEntityType {
  CHECKOUT_SESSION = 'CHECKOUT_SESSION',
  PAYMENT_TRANSACTION = 'PAYMENT_TRANSACTION',
  SUBSCRIPTION = 'SUBSCRIPTION',
}

export enum ReconciliationResolution {
  REPAIRED = 'REPAIRED',
  QUARANTINED = 'QUARANTINED',
  SUPERSEDED = 'SUPERSEDED',
}

export enum ReconciliationRunStatus {
  RUNNING = 'RUNNING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
}
