export const MAX_FILENAME_LENGTH = 255;

export const DANGEROUS_EXTENSIONS = new Set([
  '.exe',
  '.bat',
  '.cmd',
  '.com',
  '.scr',
  '.pif',
  '.vbs',
  '.vbe',
  '.wsf',
  '.wsh',
  '.msi',
  '.msp',
  '.dll',
  '.sys',
  '.drv',
  '.cpl',
  '.inf',
  '.reg',
  '.ps1',
  '.psm1',
  '.psd1',
  '.gadget',
  '.hta',
  '.lnk',
  '.scf',
  '.url',
  '.jar',
  '.jnlp',
  '.application',
  '.appref-ms',
  '.action',
  '.command',
  '.workflow',
]);

export const MIME_TO_MAGIC_BYTES: Record<string, Buffer[]> = {
  'application/pdf': [Buffer.from([0x25, 0x50, 0x44, 0x46])],
  'image/png': [Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])],
  'image/jpeg': [
    Buffer.from([0xff, 0xd8, 0xff, 0xe0]),
    Buffer.from([0xff, 0xd8, 0xff, 0xe1]),
    Buffer.from([0xff, 0xd8, 0xff, 0xe2]),
    Buffer.from([0xff, 0xd8, 0xff, 0xdb]),
    Buffer.from([0xff, 0xd8, 0xff, 0xee]),
  ],
  'image/gif': [Buffer.from('GIF87a'), Buffer.from('GIF89a')],
  'image/webp': [Buffer.from('RIFF')],
  'application/zip': [Buffer.from([0x50, 0x4b, 0x03, 0x04])],
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': [
    Buffer.from([0x50, 0x4b, 0x03, 0x04]),
  ],
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': [
    Buffer.from([0x50, 0x4b, 0x03, 0x04]),
  ],
  'application/vnd.openxmlformats-officedocument.presentationml.presentation': [
    Buffer.from([0x50, 0x4b, 0x03, 0x04]),
  ],
};

export const VIDEO_MIME_DETECTION_ALIASES: Readonly<Record<string, readonly string[]>> = {
  'video/mp4': ['video/mp4'],
  'video/quicktime': ['video/quicktime'],
  'video/mov': ['video/quicktime'],
  'video/webm': ['video/webm'],
  'video/x-msvideo': ['video/vnd.avi'],
  'video/avi': ['video/vnd.avi'],
  'video/mpeg': ['video/mpeg'],
};

export const MP4_MAJOR_BRANDS = new Set([
  '3g2a',
  '3g2b',
  '3g2c',
  '3ge6',
  '3ge7',
  '3gg6',
  '3gp1',
  '3gp2',
  '3gp3',
  '3gp4',
  '3gp5',
  '3gp6',
  '3gp7',
  'avc1',
  'dash',
  'f4v ',
  'iso2',
  'iso3',
  'iso4',
  'iso5',
  'iso6',
  'isom',
  'm4v ',
  'mp41',
  'mp42',
  'msnv',
]);
