export const PAYMENT_ENTITLEMENT_TIMEOUT_MS = 5_000;
export const PAYMENT_ENTITLEMENT_PATH_PREFIX = '/internal/payments/users';
export const PAYMENT_ENTITLEMENT_MAX_ID_LENGTH = 100;
export const PAYMENT_ENTITLEMENT_MAX_REASON_LENGTH = 128;
export const PAYMENT_ENTITLEMENT_DATE_LENGTH = 40;
