/**
 * The keyword tables that recognise an image-GENERATION request in a user
 * message. Moved here from routing-service (`IMAGE_KEYWORDS` in
 * routing.constants.ts and image-detection.constants.ts) so routing and
 * chat-service read ONE table: `classifyImageIntent` and routing's
 * `ImageDetectionManager` both use `detectImageGenerationSignals`, and the
 * edit decision can no longer drift from the generation decision.
 *
 * Matching is by lowercase SUBSTRING (unchanged from routing), which is why
 * the Arabic entries are whole phrases (ADR-119).
 */
export const IMAGE_GENERATION_KEYWORDS: readonly string[] = [
  // ar — exact phrases only: the detector matches substrings, and a loose
  // "صورة" (image) would catch "summarize the attached image" (ADR-119).
  'ارسم لي',
  'ارسملي',
  'ارسم صورة',
  'اعمل لي صورة',
  'اعمل صورة',
  'اعملي صورة',
  'اصنع لي صورة',
  'اصنع صورة',
  'انشئ صورة',
  'أنشئ صورة',
  'ولد صورة',
  'ولّد صورة',
  'صمم لي شعار',
  'صمم شعار',
  // de — verb + image noun phrases; a bare "Bild" would catch "beschreibe das
  // Bild" (describe the image). Negations ("kein Bild") are removed upstream
  // by generationRequestText before these are matched.
  'erstelle ein bild',
  'erstelle mir ein bild',
  'erzeuge ein bild',
  'erzeug ein bild',
  'generiere ein bild',
  'generier ein bild',
  'mach ein bild',
  'mach mir ein bild',
  'male ein bild',
  'male mir',
  'zeichne ein',
  'zeichne mir',
  'erstelle ein foto',
  'erstelle eine illustration',
  // zh — verb + image noun; "图片" alone would catch "这张图片是什么" (what is
  // this picture). 不要/别 clauses are removed upstream.
  '生成一张',
  '生成图片',
  '生成一幅',
  '生成图像',
  '画一张',
  '画一幅',
  '画一个',
  '帮我画',
  '给我画',
  '创建一张图',
  '制作一张图',
  '做一张图',
  'generate an image',
  'generate image',
  'generate a picture',
  'generate picture',
  'create an image',
  'create image',
  'create a picture',
  'create picture',
  'draw me',
  'draw a',
  'draw an',
  'draw the',
  'make an image',
  'make a picture',
  'make me an image',
  'make me a picture',
  'design an image',
  'design a logo',
  'sketch',
  'illustration of',
  'paint me',
  'paint a',
  'photo of',
  'photograph of',
  'render an image',
  'render a',
  'visualize',
  'depict',
  // Reference-based image generation phrases
  'generate similar',
  'similar to this',
  'like this image',
  'recreate this',
  'recreate the image',
  'reproduce this',
  'copy this image',
  'same style as',
  'based on this image',
  'inspired by this',
  'variation of this',
  'generate from this',
  'create from this',
  'make one like this',
  'make something like',
  'generate like this',
  'create similar',
  'similar image',
  'image like this',
  'remake this',
  'redo this image',
  // Scene/location prompts that imply image generation
  'fantasy map',
  'travel poster',
  'floor plan',
  'book cover',
  'album cover',
  'movie poster',
  'game character',
  'profile picture',
  'social media post',
  'app icon',
  // Single-word strong indicators
  'render ',
  'photo ',
  'portrait ',
  'illustration ',
  'poster ',
  'sticker ',
  'logo ',
  'banner ',
  'mascot ',
];

export const IMAGE_GENERATION_VERBS: readonly string[] = [
  'generate',
  'create',
  'draw',
  'make',
  'paint',
  'render',
  'design',
  'produce',
  'recreate',
  'reproduce',
  'remake',
  'redo',
];

export const IMAGE_GENERATION_WORDS: readonly string[] = [
  'image',
  'picture',
  'photo',
  'portrait',
  'illustration',
  'sketch',
  'artwork',
  'graphic',
  'poster',
  'banner',
  'icon',
  'logo',
  'wallpaper',
  'avatar',
  'cartoon',
  'anime',
  'manga',
  'comic',
  'sticker',
  'mascot',
  'character',
  'scene',
  'landscape',
  'cityscape',
  'infographic',
  'diagram',
  'wireframe',
  'mockup',
  'thumbnail',
  'cover',
  'texture',
  'pattern',
  'meme',
  'gif',
];

export const IMAGE_GENERATION_STRONG_NOUNS: readonly string[] = [
  'illustration',
  'portrait',
  'poster',
  'logo',
  'banner',
  'sticker',
  'mascot',
  'wallpaper',
  'avatar',
  'icon',
  'infographic',
  'wireframe',
  'mockup',
  'thumbnail',
  'cartoon',
  'comic strip',
  'manga',
  'anime',
];

export const IMAGE_GENERATION_ART_STYLES: readonly string[] = [
  'photorealistic',
  'watercolor',
  'oil painting',
  'impressionist',
  'cyberpunk',
  'pixel art',
  'abstract art',
  'digital art',
  'concept art',
  'fan art',
  'line art',
  'pop art',
  'vintage poster',
  'retro style',
  'minimalist design',
  'botanical illustration',
  'still life',
  'floor plan',
  'anime style',
  'comic strip',
  'sticker design',
];

export const IMAGE_GENERATION_REFERENCE_VERBS: readonly string[] = [
  'recreate',
  'reproduce',
  'remake',
];

export const IMAGE_GENERATION_REFERENCE_NOUNS: readonly string[] = ['this', 'attached'];
