import type { PaygLedgerEntryView } from '@claw/shared-types';

import type { BillingGateway } from '@/enums/billing.enum';

/**
 * One page of the user's credit ledger.
 *
 * `nextCursor` is an opaque row id, never an offset: rows are appended while the
 * user reads, and an offset would repeat or skip a line every time a request
 * settled mid-scroll.
 *
 * The row type itself comes from `@claw/shared-types` rather than being
 * redeclared here, so the field names stay verbatim identical to the backend
 * DTO and a rename cannot pass typecheck on one side only.
 */
export type CreditLedgerPage = {
  entries: PaygLedgerEntryView[];
  nextCursor: string | null;
};

/**
 * What the browser is told about a top-up checkout.
 *
 * Structurally a `CheckoutSessionView` plus the credit figure, which is what
 * lets the existing `GatewayCheckoutDialog` drive a top-up unchanged. The one
 * extra field is the only thing a top-up confirmation must show that a plan
 * checkout does not: what you are actually buying.
 */
export type CreditTopupSessionView = {
  id: string;
  status: string;
  gateway: string;
  chargeAmountMinor: number;
  chargeCurrency: string;
  /** Integer micro-USD. A package is far below 2^53, so a number is safe. */
  creditMicroUsd: number;
  hostedCheckoutUrl: string | null;
  expiresAt: string;
};

/**
 * What the browser is allowed to say when it buys credit.
 *
 * Note what is absent: no amount, no currency, no credit figure, no userId. The
 * package is named by id and every number is resolved server-side from the
 * immutable package version. A browser that could name its own price would be
 * able to buy $100 of credit for a cent.
 */
export type CreditTopupRequest = {
  packageId: string;
  gateway: BillingGateway;
  idempotencyKey: string;
};

/** What the caller supplies; the idempotency key is generated by the hook. */
export type CreditTopupStartInput = {
  packageId: string;
  gateway: BillingGateway;
};

export type AdjustCreditRequest = {
  /** Signed integer micro-USD. Negative debits the wallet. */
  amountMicroUsd: number;
  /**
   * Mandatory and of real length. An unattributed adjustment is
   * indistinguishable from a fabricated payment when finance asks where a
   * balance came from.
   */
  reason: string;
};

export type CreateCreditPackageRequest = {
  slug: string;
  displayOrder: number;
};

/**
 * A NEW immutable price version — there is no update route by design.
 *
 * `priceMinor` and `creditMicroUsd` are independent inputs, never derived from
 * one another: the gap between them is the platform's margin on a top-up, and
 * computing one from the other would freeze that decision into a deploy.
 */
export type PublishCreditPackageVersionRequest = {
  priceMinor: number;
  currency: string;
  creditMicroUsd: number;
};

/** Controlled-input state for the admin package editor. Strings, coerced on submit. */
export type CreditPackageFormState = {
  slug: string;
  displayOrder: string;
  priceMajor: string;
  currency: string;
  creditMajor: string;
};

/** Controlled-input state for the admin wallet adjustment form. */
export type CreditAdjustmentFormState = {
  userId: string;
  amountMajor: string;
  reason: string;
};

export type CreditPackageFormErrors = Partial<Record<keyof CreditPackageFormState, string>>;

export type CreditAdjustmentFormErrors = Partial<Record<keyof CreditAdjustmentFormState, string>>;

/**
 * A parse attempt: either a request the caller may send, or the reasons it may
 * not. Never both, and never a half-built request — a money form that submits
 * what it managed to parse is how an operator publishes a price they did not type.
 */
export type CreditFormParse<T> = {
  value: T | null;
  errors: Partial<Record<string, string>>;
};
