export enum RuntimeV2RedisOperation {
  START = 'START',
  ADMIT_INVOCATION = 'ADMIT_INVOCATION',
  RESULT = 'RESULT',
  STEERING = 'STEERING',
  CANCEL = 'CANCEL',
  CLAIM_ROUTED = 'CLAIM_ROUTED',
  MARK_DISPATCHED = 'MARK_DISPATCHED',
  APPEND_MODEL_OUTPUT = 'APPEND_MODEL_OUTPUT',
  TERMINAL = 'TERMINAL',
  READ_EVENTS = 'READ_EVENTS',
  READ_BINDING = 'READ_BINDING',
  READ_MESSAGE_BINDING = 'READ_MESSAGE_BINDING',
}
