import { BillingGateway, BillingInterval } from '@claw/shared-types';
import { z } from 'zod';

// What a browser is allowed to say.
//
// Note what is absent: no amount, no currency, no userId, no price version.
// The plan is named by id and everything financial is resolved server-side from
// the immutable price version. A client that could name its own price could buy
// Unlimited for a cent.
export const createCheckoutSessionSchema = z.object({
  planId: z.string().min(1).max(64),
  billingInterval: z.nativeEnum(BillingInterval),
  gateway: z.nativeEnum(BillingGateway),
  // Generated by the caller and reused on retry, so a double-submit returns the
  // same session instead of creating a second payable order.
  idempotencyKey: z.string().min(8).max(128),
});

export type CreateCheckoutSessionDto = z.infer<typeof createCheckoutSessionSchema>;

export const createPaymentMethodSetupSessionSchema = z
  .object({
    idempotencyKey: z.string().min(8).max(128),
    consentToStore: z.literal(true),
  })
  .strict();

export type CreatePaymentMethodSetupSessionDto = z.infer<
  typeof createPaymentMethodSetupSessionSchema
>;

export const checkoutSessionParamSchema = z.object({
  id: z.string().min(1).max(64),
});

export type CheckoutSessionParamDto = z.infer<typeof checkoutSessionParamSchema>;

export const completePaypalCheckoutSchema = z
  .object({
    providerOrderId: z.string().min(1).max(64),
    state: z.string().regex(/^[a-f0-9]{64}$/),
  })
  .strict();

export type CompletePaypalCheckoutDto = z.infer<typeof completePaypalCheckoutSchema>;

export const completePaypalSdkCheckoutSchema = z
  .object({
    providerOrderId: z.string().min(1).max(64),
  })
  .strict();

export type CompletePaypalSdkCheckoutDto = z.infer<typeof completePaypalSdkCheckoutSchema>;

export const planChangeQuoteSchema = z.object({
  targetPlanId: z.string().min(1).max(64),
  billingInterval: z.nativeEnum(BillingInterval),
});

export type PlanChangeQuoteDto = z.infer<typeof planChangeQuoteSchema>;

// Confirm references the quote by id rather than restating the amount. The user
// agreed to a specific number; re-deriving it here would let the price move
// between the two calls.
export const planChangeConfirmSchema = z.object({
  quoteId: z.string().min(1).max(64),
  gateway: z.nativeEnum(BillingGateway),
  idempotencyKey: z.string().min(8).max(128),
});

export type PlanChangeConfirmDto = z.infer<typeof planChangeConfirmSchema>;

export const cancelSubscriptionSchema = z.object({
  // Self-service cancellation is always at period end. Immediate revocation is
  // a refund decision and belongs to an operator, not a button.
  atPeriodEnd: z.literal(true),
});

export type CancelSubscriptionDto = z.infer<typeof cancelSubscriptionSchema>;
