import { BillingGateway } from '@claw/shared-types';
import { z } from 'zod';

/**
 * What a browser is allowed to say when it buys credit.
 *
 * Note what is absent, and note that `.strict()` makes the absence enforceable:
 * no amount, no currency, no credit figure, no price version, no userId. The
 * package is named by id and everything financial is resolved server-side from
 * the immutable `CreditPackageVersion` in auth-service.
 *
 * `.strict()` is not decoration here. Without it an extra `amountMinor` in the
 * body would be silently dropped, which is safe today and one careless
 * `...dto` spread away from being a price the buyer chose.
 */
export const createCreditTopupSessionSchema = z
  .object({
    packageId: z.string().min(1).max(64),
    gateway: z.nativeEnum(BillingGateway),
    // Generated by the caller and reused on retry, so a double-submit returns
    // the same session instead of creating a second payable order.
    idempotencyKey: z.string().min(8).max(128),
  })
  .strict();

export type CreateCreditTopupSessionDto = z.infer<typeof createCreditTopupSessionSchema>;
