-- Stream 20: GitLab + Bitbucket write actions

ALTER TYPE "WorkspaceActionType" ADD VALUE 'CREATE_MR_COMMENT';
ALTER TYPE "WorkspaceActionType" ADD VALUE 'APPROVE_MR';
ALTER TYPE "WorkspaceActionType" ADD VALUE 'CREATE_GITLAB_ISSUE';
ALTER TYPE "WorkspaceActionType" ADD VALUE 'COMMENT_GITLAB_ISSUE';
ALTER TYPE "WorkspaceActionType" ADD VALUE 'UPDATE_MR_DESCRIPTION';
ALTER TYPE "WorkspaceActionType" ADD VALUE 'CREATE_PR_COMMENT_BB';
ALTER TYPE "WorkspaceActionType" ADD VALUE 'APPROVE_PR_BB';
ALTER TYPE "WorkspaceActionType" ADD VALUE 'CREATE_BITBUCKET_ISSUE';
